### ISSUE TITLE
latest version does not execute - fails during load

### ISSUE THREAD

**Issue by krimple** [angular/quickstart#10]
I had to revert to commit a5f4882ece790b420876e3daae2687405145d8f4 to fix the problems with the currently checked-in version of the quickstart. I did not roll forward to others as I was about to give a demo today and on the way over I made the mistake of updating. 

I'm getting this error:

```text
ncaught (in promise) TypeError: Cannot read property 'annotations' of undefinedmessage: "Cannot read property 'annotations' of undefined"
"TypeError: Cannot read property 'annotations' of undefined
    at ReflectionCapabilities.$__export.annotations (http://localhost:3456/quickstart/angular2/src/reflection/reflection_capabilities.js:81:40)
    at Reflector.$__export.annotations (http://localhost:3456/quickstart/angular2/src/reflection/reflector.js:81:50)
    at DirectiveMetadataReader.$__export.read (http://localhost:3456/quickstart/angular2/src/core/compiler/directive_metadata_reader.js:31:41)
    at http://localhost:3456/quickstart/angular2/src/core/compiler/compiler.js:127:35
    at Array.map (native)
    at Function.$__export.map (http://localhost:3456/quickstart/angular2/src/facade/collection.js:172:26)
    at Compiler.$__export.createSteps (http://localhost:3456/quickstart/angular2/src/core/compiler/compiler.js:126:43)
    at Compiler.$__export._compileTemplate (http://localhost:3456/quickstart/angular2/src/core/compiler/compiler.js:164:53)
    at http://localhost:3456/quickstart/angular2/src/core/compiler/compiler.js:154:29
    at Zone.run (http://localhost:3456/quickstart/dist/es6-shim.js:29889:19)"
```

**Comment by huytd** [comment]
Confirmed same problem. Please check it.

**Comment by davideast** [comment]
@krimple and @huytd Can you provide the code you are using so I can reproduce?

**Comment by huytd** [comment]
Here you are https://www.dropbox.com/s/4g9a95ipc1zpj1m/todo_a2beta14.zip?dl=0
I run it with a python command: 
```
python -m SimpleHTTPServer
```

**Comment by krimple** [comment]
I am just following the quickstart 'getting started' and running todo.html

Ken

**Comment by huytd** [comment]
May be there are some changes from `beta 14`, for example, I see they don't include the `directives/foreach` anymore, and replaced with `directives/for`
If this is true, all the demo app and other tutorials will become outdated!

**Comment by krimple** [comment]
It's going to be hard to not be brittle there...  I suggest maybe creating
branches and committing to them and keeping the mainline functional -
perhaps you can branch for beta-14 and work in there, and people could
maybe contribute pull requests to help you fix them.


Ken Rimple
Training and Mentoring Services
Chariot Solutions
610-608-3935
@krimple

**Comment by huytd** [comment]
https://github.com/angular/angular/commit/b61b8d60b7cfd10786ccd9ba4071738d4f2bf15a
`foreach` changed to `for-of`
One of the most dangerous change. Agreed that we cannot ask for more clearly document at this time. But it's still dangerous :tired_face:

**Comment by huytd** [comment]
@krimple check it out
https://github.com/angular/angular/tree/master/modules/examples/src/todo
This is the latest version of `todo` app. With the new API. 
A lot of changes.

**Comment by davideast** [comment]
@krimple @huytd 

It sounds like you're running into issues with the changing API. Angular is still in alpha so this will happen. The documentation won't be available while in alpha since everything is rapidly changing.

Were you able to successfully run the basic "Hello Alice" example?

**Comment by huytd** [comment]
I digged into the new sample source code and fixed my problems :+1: it's OK now.

**Comment by NIshantDesaiJumpbyte** [comment]
What was the issue can you please share it ?
