### ISSUE TITLE
Package missing in npm

### ISSUE THREAD

**Issue by SparK-Cruz** [angular/quickstart#103]
Tried following the tutorial and got some nasty 404s from npm from package https://registry.npmjs.org/angular/http/2.0.0-rc.1 to the end...

**Comment by ahwizzang** [comment]
I am having same issue. Reported to npm support, but also commented here if I can get help.

**Comment by Foxandxss** [comment]
What npm version do you both have?

**Comment by gonzalemi** [comment]
same issue, npm version 2.15.1 and node 4.4.4

**Comment by ahwizzang** [comment]
These are my versions. node: 0.10.36, npm: "3.8.9".

**Comment by Foxandxss** [comment]
0.10.x is really old, you need to update yes or yes.

You all need a 5.x node and npm 3.x

**Comment by ahwizzang** [comment]
I upgraded them like this but it still doesn't work.
node: 6.2.0
npm: 3.9.0

I wonder if angular rc version has been published since npm page for angular2 says "2.0.0-beta.17 is the latest of 68 releases"
https://www.npmjs.com/package/angular2

**Comment by Foxandxss** [comment]
You are looking at a different package, you need https://www.npmjs.com/~angular

**Comment by ahwizzang** [comment]
Ok, I was still getting same issue. I could resolve this issue by trying to specify the registry with the install command. 

npm install <packagename> --registry http://registry.npmjs.org/
