### ISSUE TITLE
unable to run tests if change name of "app" directory and references

### ISSUE THREAD

**Issue by jwhite1802** [angular/quickstart#106]
I've successfully implemented this into applications that follow exactly your file naming convention using the "app" directory in the root of the project.  But I am having trouble using this in projects that are really modules and not apps.  

Essentially, I would like to emulate what was done in the angular/angular project where components are modularized in a "modules" directory instead of an "app" directory.  I've changed the "app" references in all the obvious places, but must be missing something.  Are all the hardcoded references to "app" in the karma-conf.js and karma-test-shim.js files?  Somewhere else I should look?

Any guidance is appreciated!

Thanks for such great tools.

**Comment by wardbell** [comment]
Yes ... hardcoded refs to `app` in karma-shim, wallaby, and systemjs.config
