### ISSUE TITLE
unable to execute npm run postinstall(The content of the issue is npm-debug.log)

### ISSUE THREAD

**Issue by giorbismiguel** [angular/quickstart#107]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'postinstall' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'postinstall' ]
5 info postinstall angular2-quickstart@1.0.0
6 verbose unsafe-perm in lifecycle true
7 info angular2-quickstart@1.0.0 Failed to exec postinstall script
8 verbose stack Error: angular2-quickstart@1.0.0 postinstall: `typings install`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at EventEmitter.emit (events.js:172:7)
8 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at ChildProcess.emit (events.js:172:7)
8 verbose stack     at maybeClose (internal/child_process.js:827:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
9 verbose pkgid angular2-quickstart@1.0.0
10 verbose cwd C:\wamp\www\estudio\angular2\angular2-quickstart
11 error Windows_NT 6.1.7600
12 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "postinstall"
13 error node v4.4.2
14 error npm  v2.15.0
15 error code ELIFECYCLE
16 error angular2-quickstart@1.0.0 postinstall: `typings install`
16 error Exit status 1
17 error Failed at the angular2-quickstart@1.0.0 postinstall script 'typings install'.
17 error This is most likely a problem with the angular2-quickstart package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     typings install
17 error You can get information on how to open an issue for this project with:
17 error     npm bugs angular2-quickstart
17 error Or if that isn't available, you can get their info via:
17 error
17 error     npm owner ls angular2-quickstart
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]

**Comment by wardbell** [comment]
Please do not dump stack traces in here. It appears that your postinstall step failed. You can run `npm run typings install` separately.
