### ISSUE TITLE
systemjs.config.js BAD FILENAME:

### ISSUE THREAD

**Issue by mattfricker** [angular/quickstart#108]
Thank you for providing this great resource for getting started with Angular.

When following the Quick Start, I received the following when clicking on the systemjs.config.js tab.in Step 1b.

BAD FILENAME: ../../_fragments/quickstart/ts/systemjs.config.1.js.md   Current path: docs,ts,latest,quickstart PathToDocs: ../../

**Comment by Foxandxss** [comment]
Tutorial issues go to the angular.io repo and that one is fixed, site will be updated soon.
