### ISSUE TITLE
broken symbolic link to systemjs.config.js

### ISSUE THREAD

**Issue by vance** [angular/quickstart#110]
[Quickstart](https://angular.io/docs/ts/latest/quickstart.html#!#create-and-configure) guide. click the tab for `systemjs.config.js` does not link to the file:

```
BAD FILENAME: ../../_fragments/quickstart/ts/systemjs.config.1.js.md   Current path: docs,ts,latest,quickstart PathToDocs: ../../
```

**Comment by Foxandxss** [comment]
Dup from #108 

Please, it doesn't cost much checking the recent closed issues.

**Comment by vance** [comment]
heh oops. github needs a feature like stackoverflow where as you type a new question/issue it auto populates a list next to the input of relevant issues. I usually do due diligence if there's open tickets and it's a bug, but if the bug is still there and not in an open ticket I usually assume it's not been reported, otherwise it wouldn't be visible in the latest build. 🌴

**Comment by Foxandxss** [comment]
Yes, but keep in mind that this repo is not for the quickstart guide. Quickstart guide lives in another repo with it own issue tracker
