### ISSUE TITLE
Cannot find module 'angular2-in-memory-web-api'

### ISSUE THREAD

**Issue by christo8989** [angular/quickstart#114]
http://stackoverflow.com/questions/37377529/angular2-tutorial-tour-of-heroes-cannot-find-module-angular2-in-memory-web-a

I'm having this issue and none of the answers from stackoverflow are helping.

I've triple checked my spellings in both the main.ts and system.config.js files.
I've tried the solutions on stackoverflow.
I've tried adding the reference explicitly with `'./../node_modules/angular2-in-memory-web-api';`

It doesn't recognize it. Here's what VS Code gives me with the red squigly line: `[ts] Cannot find module 'angular2-in-memory-web-api'.`
![main](https://cloud.githubusercontent.com/assets/1092511/15464281/3c911686-2083-11e6-88a2-2b3d85b9504d.png)
![system config js](https://cloud.githubusercontent.com/assets/1092511/15464280/3c8d55fa-2083-11e6-8fc6-335278515e30.png)

**Comment by Foxandxss** [comment]
You need to add:

```
'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
```

We changed how the lib work in the past few days.

Sorry for the troubles.

**Comment by christo8989** [comment]
In the **package.json** upgrade to `"angular2-in-memory-web-api": "0.0.10",` as well.

Thank you!

Here's the solution on [StackOverflow](http://stackoverflow.com/a/37390321/2573621).
