### ISSUE TITLE
Overuse of "hero"

### ISSUE THREAD

**Issue by jerlich** [angular/quickstart#120]
I am a relatively experienced programmer and software engineer and I've been doing the "heroes" example to learn angular.

The examples use the variable name `hero` and `heroes` in many different places which makes it confusing for a new angular user to understand variable scope and how data is passed around between components / templates / services, etc.

For example in lesson 4 there is a `heroes` that is passed from the service to the AppComponent. But this does not have to have the same variable name. 

in the `<li *ngFor="let hero of heroes"...` the `heroes` there must match the variable name in the exported `AppComponent` class, but because of the overuse, that isn't clear. The `hero` in the list element only has to match the variable name within that list element and is independent of the `hero` variable in the HeroDetailComponent.

I appreciate the time that you have taken to make these tutorials, just added my 2 cents to try to improve them.

I wasn't sure where to post this feedback. Apologies if it is in the wrong place.

**Comment by Foxandxss** [comment]
Please, post it again at the angular.io repo (where we have our documentation). This repo is just a mirror for the quickstart.

Thanks for the feedback.
