### ISSUE TITLE
TSC bundling - simpler - worthwhile?

### ISSUE THREAD

**Issue by kylecordes** [angular/quickstart#122]
In an effort to illustrate variation to bundling approaches, I made the following very minor fork of quickstart. The only difference is that it configures TSC to generate a single file system bundle, instead of generating many separate JS files. This turns out to be slightly fewer lines of configuration in total.

https://github.com/kylecordes/quickstart/commit/3cf3041dd80ee8701a3cffb0cbe6264784017a2b

This might or might not be better, for varying definitions of better. But I'm bringing it up here in case it might be a good change for the quickstart?

(This approach is also much more performant at scale, though I'm pretty confident that does not matter at all for the quickstart.)

**Comment by Foxandxss** [comment]
Thanks, but the quickstart is just a mirror of the quickstart tutorial and we are not planning on adding any new feature to it.

Bundling is a nice feature, but the quickstart itself is not really doing any bundle not it does need that at the moment.

**Comment by kylecordes** [comment]
Thanks. Yes, I know this mirrors the quickstart from angular.io. I'll close the issue, my goal was just to have one of the quickstart contributors glance and assess it... which you just did.

**Comment by VahidN** [comment]
It seems this method should not be used with angular2. [more info here](http://stackoverflow.com/a/33635528/298573)

**Comment by kylecordes** [comment]
That is an interesting opinion expressed by the writer there, but I don't agree with their interpretation of that section of the TypeScript documentation. In fact, the setting appears to work quite well for its intended purpose, and of course the ability to produce a SystemJS bundle is also noted in the TypeScript documentation.  It will take ordinary typescript modules in files as input, and it can produce either a separate file for each module of output, or it can produce a bundle. This demonstrably works, shown in my tiny commit above, and is in use on substantial projects "in the wild".  The sentence references, at the end of the following page, is incorrect.

https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Namespaces%20and%20Modules.md

Of course this is all irrelevant to the actual issue here, which is whether there is merit in using this setting in the quickstart, and I think the answer to that is universally no.
