### ISSUE TITLE
npm start failed with node v6.2.0 and npm v3.8.9

### ISSUE THREAD

**Issue by Roycohen** [angular/quickstart#123]
I'm trying to install this quickstart project but I have some errors.
Will be really appreciate if you help solving this.

[npm-debug.txt](https://github.com/angular/quickstart/files/289550/npm-debug.txt)

**Comment by Foxandxss** [comment]
Weird, I see no hint there of what could be happening.

**Comment by Roycohen** [comment]
Forgot to run npm install first...
It is working now.
