### ISSUE TITLE
'node_modules' should be excluded in tsconfig.json

### ISSUE THREAD

**Issue by DenisVuyka** [angular/quickstart#125]
tsconfig.json is missing exclude for at least "node_modules" folder

**Comment by anik786** [comment]
I though so to, but this is not required if you run typings like so:

`npm run postinstall`

or

`npm run typings install`

or if you have typings installed globally execute:

`typings install`

Thus many of the "Duplicate Identifier errors" go away!

**Comment by DenisVuyka** [comment]
@anik786 Not sure how your answer relates to the initial issue. It is not about typings and postinstall.

**Comment by anik786** [comment]
I had issues when running typescript, when "node_modules" was not in the excludes of "tsconfig.json". However when I installed the typings, all the errors went away. Not sure why. 

But you may still be right in that "node_modules" should still be there.

**Comment by wardbell** [comment]
`node_modules` is automatically excluded unless you specify `files` or `excludes` in the tsconfig in which case you are on your own.

Closing as your issue is old. Please re-open as a new issue if problem persists.
