### ISSUE TITLE
Stuck on "extract -> gunzTarPerm"

### ISSUE THREAD

**Issue by pfernandom** [angular/quickstart#126]
I cloned this project in order to start learning about Angular2. However, when I run "npm install", the installation starts and suddenly it gets stuck in this part:

extract -> gunzTarPerm

I left it there for almost half an hour and it won't go after that.

These are my specs:

- Windows 7 Professional
- Node v6.2.1
- npm v3.7.5

I also tried to follow https://angular.io/docs/ts/latest/quickstart.html and start the project myself and it stays in the same part.

How can I fix this error?

Regards.

**Comment by filipesilva** [comment]
I know it's a hassle, but can you try with node 5? https://github.com/creationix/nvm can help you with multiple versions.

I ask because I've read that it might be related to either npm version or total ram... and it's easier to check npm version.

**Comment by pfernandom** [comment]
Actually, I just tried again in another network and now it builds quick and easy. With the same versions I listed previously.

I'm guessing it was just a network issue, or a repository was temporarily down.

Sorry I rushed to open a defect; and thank you for your really quick response.

Regards.

**Comment by filipesilva** [comment]
Glad it's sorted man!
