### ISSUE TITLE
TypeError: Error loading "rx/dist/rx.all"

### ISSUE THREAD

**Issue by uriklar** [angular/quickstart#13]
Hi guys,
I followed the Hello Alice example and when going to localhost:8080/index.html I received some errors. 
After running ```gulp default``` I got down to only the following error:
```
Uncaught (in promise) 
TypeError: Error loading "rx/dist/rx.all" at <unknown>
Error loading "rx/dist/rx.all" from "app" at http://localhost:8080/app.es6
Cannot read property 'replace' of undefined
```

Any idea what the problem might be?

Thanks! Uri

**Comment by naomiblack** [comment]
This is because angular 2 depends on rx, but it's missing from our quickstart.

*Workaround*: Add it to your package.json and System.path, as patternMiner has here
https://github.com/patternMiner/pattern_search/blob/master/package.json
https://github.com/patternMiner/pattern_search/blob/master/index.html

Thanks for reporting, we'll update the quickstart repo shortly.

**Comment by uriklar** [comment]
Perfect, it works. Thanks alot!

**Comment by rkirov** [comment]
Note that quickstart was made for the steps outlined on http://angular.io . Running `gulp` is not one of those steps. It is required only to move the quickstart to the current head.

**Comment by paulftw** [comment]
This is still broken. For me it was enough to add

    'rx/*': '/node_modules/angular2/node_modules/rx/*.js',

to the System.paths, as it was already in my node_modules.

**Comment by revspringjake** [comment]
As of 04/23/2015 added rx as stated above to system and package.json and get this error:
TypeError: Error loading "app" at <unknown> Cannot read property 'replace' of undefined
message: "Error loading "app" at <unknown>↵Cannot read property 'replace' of undefined"
stack: (...)
get stack: function () { [native code] }
set stack: function () { [native code] }
__proto__: Error

**Comment by relevantmedia** [comment]
I am getting an error with es6-shim. Is this a known error - TypeError: Error loading "rx/dist/rx.all" at <unknown> Error loading "rx/dist/rx.all" from "app" at http://localhost:8080/app.es6 Cannot read property 'replace' of undefined {stack: (...), message: "Error loading "rx/dist/rx.all" at <unknown>↵Error …p.es6↵Cannot read property 'replace' of undefined"}

**Comment by JonWallsten** [comment]
I really can't get this to work. 
I have added rx int he package.json and index.html.
I ran to gulpfile with gulp to build the latest alpha.
All the versions are correct.

I get this error message:
```
Uncaught (in promise) TypeError: Error loading "rx" at <unknown>
```

What am I doing wrong?

**Comment by davideast** [comment]
Hey @JonWallsten, can you try running through the latest tutorial? It has removed the need fo rthis repo. https://angular.io/docs/js/latest/quickstart.html

**Comment by JonWallsten** [comment]
I'm trying to follow this one:
http://www.htmlxprs.com/post/54/creating-a-super-simple-todo-app-using-angular-2-tutorial

I had no problem with the quickstart example. Should have mentioned that. Sorry!
Perhaps because the quickstart example isn't using rx for anything?

**Comment by davideast** [comment]
That tutorial is outdated, try going through the one I linked to above. Let me know if that works for you.

**Comment by JonWallsten** [comment]
Fudge! I'v done it already. Wanted to do something "harder" with ES6. Any other tutorials in mind? Thanks!

**Comment by davideast** [comment]
Angular 2 changes frequently since it's in dev preview. The most accurate tutorials are most likely the ones on the angular.io site.

**Comment by wardbell** [comment]
Closed. Obsolete.
