### ISSUE TITLE
QuickStart Fails on ES6 Features

### ISSUE THREAD

**Issue by jmuharsky** [angular/quickstart#130]
REPRO STEPS
Follow the instructions at either the [Angular.io quickstart](https://angular.io/docs/ts/latest/quickstart.html), or the instructions on the [Angular2 GitHub QuickStart](https://github.com/angular/quickstart).

CURRENT BEHAVIOR
After running ``npm start``, a variety of error messages are raised, along the lines of:

``node_modules/@angular/common/src/facade/async.d.ts(27,33): error TS2304: Cannot find name 'Promise'.``

EXPECTED BEHAVIOR
The QuickStart should run by following the documented instructions.

**Comment by Foxandxss** [comment]
You are missing the typings that for some reason, they fail under certain OS and node versions.

./node_modules/.bin/typings install

**Comment by naomiblack** [comment]
@Foxandxss could you make this update to the QS as well?
