### ISSUE TITLE
QuickStart Docs not updated with proper system.config.js

### ISSUE THREAD

**Issue by eirikdinerp** [angular/quickstart#134]
FYI

Just went through the quickstart (https://angular.io/docs/ts/latest/quickstart.html) and had to get the system.config.js file from the github repo, since the one in the tutorial was off.

From the quickstart web page:
```
 // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: pkgName + '.umd.js', defaultExtension: 'js' };
  }
```

From github repo:

```
 // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
  }
```

the '/bundles/' prefix is missing in the quickstart docs.

**Comment by Foxandxss** [comment]
Sorry about that, that is fixed by now.
