### ISSUE TITLE
Error when npm install the project

### ISSUE THREAD

**Issue by ygmgbg** [angular/quickstart#135]
I got this error when I ran `npm install`

157 error Windows_NT 10.0.10586
158 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
159 error node v4.4.5
160 error npm  v2.15.5
161 error code EPEERINVALID
162 error peerinvalid The package @angular/core@2.0.0-rc.2 does not satisfy its siblings' peerDependencies requirements!
162 error peerinvalid Peer @angular/common@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
162 error peerinvalid Peer @angular/compiler@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
162 error peerinvalid Peer @angular/http@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
162 error peerinvalid Peer @angular/platform-browser@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
162 error peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
162 error peerinvalid Peer @angular/router@2.0.0-rc.2 wants @angular/core@^2.0.0-rc
162 error peerinvalid Peer @angular/router-deprecated@2.0.0-rc.2 wants @angular/core@^2.0.0-rc
162 error peerinvalid Peer @angular/upgrade@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
162 error peerinvalid Peer angular2-in-memory-web-api@0.0.11 wants @angular/core@2.0.0-rc.1
163 verbose exit [ 1, true ]

**Comment by Timz** [comment]
check npm version:
**$ npm --version**
if <3 update to last:
**npm install npm -g**

**Comment by filipesilva** [comment]
Sorry, one of the dependencies was left in a old one. It should be fixed now.

**Comment by ygmgbg** [comment]
thank you

**Comment by airhork** [comment]
@filipesilva 

seems this issue happens again?

npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/core does not satisfy its siblings' pe
erDependencies requirements!
npm ERR! peerinvalid Peer @angular/common@2.0.0-rc.3 wants @angular/core@2.0.0-r
c.3
npm ERR! peerinvalid Peer @angular/compiler@2.0.0-rc.3 wants @angular/core@2.0.0
-rc.3
npm ERR! peerinvalid Peer @angular/forms@0.1.1 wants @angular/core@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/http@2.0.0-rc.3 wants @angular/core@2.0.0-rc.
3
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.3 wants @angular/co
re@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.3 wants @an
gular/core@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/router@3.0.0-alpha.8 wants @angular/core@^2.0
.0-rc.2
npm ERR! peerinvalid Peer @angular/router-deprecated@2.0.0-rc.2 wants @angular/c
ore@^2.0.0-rc
npm ERR! peerinvalid Peer @angular/upgrade@2.0.0-rc.3 wants @angular/core@2.0.0-
rc.3
npm ERR! peerinvalid Peer angular2-in-memory-web-api@0.0.12 wants @angular/core@
2.0.0-rc.2

**Comment by Foxandxss** [comment]
That node is reaaaaaaaaaally old.

**Comment by airhork** [comment]
indeed, it probably an old node
but I assume the error is because of the upgrade from 2.0.0-rc.2 to 2.0.0-rc.
3? No

**Comment by filipesilva** [comment]
@airhork I think it's actually because of node, I know that similar peerDeps issues are solved on newer versions. Can you try node 5 or 6?

**Comment by Foxandxss** [comment]
Is NPM probably the problematic one, but I recommend Node 5 at least.

**Comment by airhork** [comment]
ok, thanks for the quick feedback. installing.

**Comment by airhork** [comment]
Thanks for the help.
I updated to the latest node, it need can skip this issue. 

I saw the major version for node (official site) is still 4.4.6, which also have this issue.
reason seems the angular2-in-memory-web-api@0.0.12 wants @angular/core@2.0.0-rc.2
but core is already 3.
guess still better have a fix on it?

**Comment by Foxandxss** [comment]
That is expected and will be fixed soon. Still with that, it should work.

**Comment by JessRascal** [comment]
I'm having the same issue when trying to deploy to AWS which uses node 4.4.3 (npm 2.15.1) , is there any way around this or am I stuck until a fix is in place?

**Comment by Foxandxss** [comment]
I am not really sure if a solution for npm 2.x is going to come.

Can't it be updated to latest npm?

`npm i -g npm`

**Comment by cooervo** [comment]
Hi there I'm on node v5.10.0 and after trying `meteor npm install --save angular2-meteor` I get the same error:

`The package @angular/commmon@2.0.0-rc.4 does not satisfy its siblings' peerDependencies requirements!

**Comment by filipesilva** [comment]
@cooervo you'll have to ask at the `angular2-meteor` repo. We don't control the dependencies they use.

**Comment by pashaproton** [comment]
Guys, I had the same error. For me helps `npm i -g npm`

**Comment by herlon214** [comment]
Update npm (npm install npm -g) solved for me!

**Comment by madrahimov** [comment]
Thanks you !!! (npm install npm -g) solved my issue also

**Comment by emaalouf** [comment]
I found something awesome in regards to node
anything you have a problem with just uninstall and reinstall it and then reinstall any dependencies they might require!
