### ISSUE TITLE
Windows_NT 6.1.7601 ( Failed at the angular2-quickstart@1.0.0 lite script 'lite-server' )

### ISSUE THREAD

**Issue by sreetej** [angular/quickstart#139]
Following the angular2 quickstart tutorial from https://angular.io/docs/ts/latest/quickstart.html.

installed recommended versions of npm and Node.

using windows os.  

this is the error i am getting... 

 **Error: spawn cmd ENOENT
     at exports._errnoException (util.js:893:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32

     at onErrorNT (internal/child_process.js:348:16)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)

 npm
  ERR! **Windows_NT 6.1.7601**
 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\node
\node_modules\\npm\\bin\\npm-cli.js" "run" "lite"
 npm ERR! node v5.11.1
 npm
 ERR! npm  v3.8.6
 npm ERR! code ELIFECYCLE
 npm ERR! angular2-quickstart@1.0.0 lite: `lite-server`
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the angular2-quickstart@1.0.0 lite script 'lite-server'.
 npm ERR! Make sure you have the latest version of node.js and npm installed.

 npm ERR! If you do, this is most likely a problem with the angular2-quicksta
package,
 npm ERR! not with npm itself.
 npm ERR! Tell the author that this fails on your system:
 npm ERR!     lite-server
 npm ERR!
  You can get information on how to open an issue for this project with:
 npm ERR!     npm bugs angular2-quickstart
 npm ERR! Or if that isn't available, you can get their info via:
 npm ERR!     npm owner ls angular2-quickstart
 npm ERR! There is likely additional logging output above.

 npm ERR! Please include the following file with any support request:
 npm ERR!     C:\BackUp\projects\projects\Angular2.0\angular2-quickstart\npm-
ug.log

**

Attaching the debug.log file 
![capture](https://cloud.githubusercontent.com/assets/8962796/16223569/91ec0f6a-37bb-11e6-9323-05d28b97d79a.PNG)

**Comment by anik786** [comment]
Try the following:

```
rm -r node_modules
rm -r typings
npm install
npm run postinstall
npm start
```

**Comment by sreetej** [comment]
Thanks for the reply @anik786  

i got an error to run the first command. "'rm' is not recognized as an internal or external command,
operable program or batch file."

i tried running the other commands again facing some error. i will attach the screenshot below. 
![capture](https://cloud.githubusercontent.com/assets/8962796/16370669/3763f32a-3c5f-11e6-88fb-9ef65ec7455d.PNG)

**Comment by filipesilva** [comment]
`rm` is the linux command for deleting folders from the command line, which also works on Windows if you are using gitbash.

You don't seem to be using gitbash, so instead you can just delete directories manually. Delete `node_modules` and `typings`, then try running the commands:
```
npm install
npm run postinstall
npm start
```

**Comment by sreetej** [comment]
Hi @filipesilva 

i already tried doing that, again facing the same error.

**Comment by anik786** [comment]
I personally had problems with the "lite-server" myself. 

Consider using a proper server like Apache or PHP's built in server like so:

```
php -S localhost:8080
```

**Comment by jiggy1com** [comment]
I use Windows and Mac. Pushed the typings dir from Win, and pulled it to the Mac; ended up with the same issue (no idea why). Removing the dirs and running those npm install & postinstall commands resolved my issue. **Thanks!** ... I think I'll keep the /typings dir out my repo going forward. BTW, my Mac running NodeJS 4.4.7 seems to work just fine. Both run Apache as a proxy: works! Hitting the port: works!

**Comment by feeleen** [comment]
having the same problem, 
did all the advised steps (delete dirs, install, postinstall) but got the same result

**Comment by filipesilva** [comment]
I can't reproduce this myself on windows, and the logs show an error that I really have no idea what it could be. My recommendation is to open an issue at https://github.com/johnpapa/lite-server itself.
