### ISSUE TITLE
Update angular2 to alpha 18

### ISSUE THREAD

**Issue by jcoyne** [angular/quickstart#14]
If you also document the steps to do the update, other contributors could do this work next time.

**Comment by yleichanok** [comment]
Subscribing. Also it would be great to see how to actually build angular from source code. All quickstarts and samples I've seen use pre-built version for some reason which makes updating painful.

**Comment by artdias90** [comment]
+1, I'm stuck with the annotations problem described here https://github.com/angular/quickstart/issues/12
and a newer version of Angular2 has the fix.

**Comment by thgreasi** [comment]
+1

**Comment by wardbell** [comment]
Closed. Obsolete.
