### ISSUE TITLE
npm start failing

### ISSUE THREAD

**Issue by findjonmos** [angular/quickstart#140]
Hey guys, spent yesterday doing some angular2 stuff

Then this morn I went to do an npm start and get the attached error messages?

Any ideas? I have made sure I have the latest npm and node as you can see in the debug file, and I have made sure that concurrently, lite-server and typescript are all globally installed.

Still nothing seems to work - not sure how it could go from working fine yesterday to not working without making any changes that I can foresee would stop npm start??

[npm-debug.txt](https://github.com/angular/quickstart/files/325175/npm-debug.txt)

**Comment by Foxandxss** [comment]
Did you `npm install` ?

**Comment by findjonmos** [comment]
Yep I did the npm install...think I discovered what it was though I think it is still an issue going forwards.

So I had an export class like this one below - it seems important that npm start is running whilst you write out this code then it will compile and any issues will get reported as a failed build error message in the browser or a console error in the browser

If for some reason the npm start needs to be stopped or in my case you finish for the day and try to restart npm start the next day then it will fail to launch the server.

The below code does have a legitimate error the users; variable should really be users: any[];

But this error does not really justify the difference in the way the build runs

```
export class HomeComponent implements OnInit {
    errorMessage: string;
    users;
    
    constructor (private usersService: UsersService){}

    ngOnInit() { this.getUsers(); }

    getUsers(){
        this.usersService.getUsers()
            .subscribe(
                data => this.users.push(data),
                error => this.errorMessage = <any>error
            )
    }

}
```

**Comment by findjonmos** [comment]
I was getting the below in the console:
But I was paying attention to the red npm ERR! and assuming I had some misconfiguration of my build system

I was missing the line above these npm ERR! 

```
app/home/home.component.ts(15,5): error TS7008: Member 'users' implicitly has an 'any' type.
 
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR!

npm ERR! Failed at the angular2-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-quickstart
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jonathan.mosley/Documents/web-development/moneymanage-ng2-rc2/npm-debug.log
```

**Comment by VahidN** [comment]
If you want to mix typed and untyped coding styles, use
["noImplicitAny": false,](url)
in your `tsconfig.json` file.

**Comment by Timz** [comment]
This solution works for me. Change:
"start": "**tsc &&** concurrently \"tsc -w\" \"lite-server\" ",
to:
"start": "concurrently \"tsc -w\" \"lite-server\" ",
and test: **npm start**

**Comment by anik786** [comment]
if Timz solution did not work try running each node command separately to identify what is giving you problems like so:

`npm run tsc`
`npm run tsc -w`
`npm run lite-server`

Which ones work?

A potential solution to your problem is as follows:

```
rm -r node_modules
rm -r typings
npm install
npm run postinstall
npm start
```

**Comment by kimbaudi** [comment]
@findjonmos, I think the problem was the following code in app.component.spec.ts file:
```
describe('AppComponent with new', function () {
  it('should instantiate component', () => {
    expect(AppComponent).toBeDefined('Whoopie!');
  });
});
```
You either need to remove it or change `new AppComponent()` to `AppComponent`.

This block of code has been removed from this repo for Angular 2 RC4. You most likely encountered this issue because you cloned this repo before a later commit when this block of code was removed. Can you confirm?

**Comment by fdelia** [comment]
In my case `typings install` /  `npm run postinstall` did it. The readme doesn't mention to install that too. Sorry, total noob here.

**Comment by Foxandxss** [comment]
We updated the instructions a bit ago.

Closing this.

**Comment by tamilmovieskaari** [comment]
None of the above solution worked for me 

my package.json:

{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {

    "build": "tsc -p src/",
    "build:watch": "tsc -p src/ -w",
    "build:e2e": "tsc -p e2e/",
    "serve": "lite-server -c=bs-config.json",
    "serve:e2e": "lite-server -c=bs-config.e2e.json",
    "prestart": "npm run build",
    "start": "tsc && concurrently \"npm run tsc:w\"npm run lite",

    "pree2e": "npm run build:e2e",
    "e2e": "concurrently \"npm run serve:e2e\" \"npm run protractor\" --kill-others --success first",
    "preprotractor": "webdriver-manager update",
    "protractor": "protractor protractor.config.js",
    "pretest": "npm run build",
    "test": "concurrently \"npm run build:watch\" \"karma start karma.conf.js\"",
    "pretest:once": "npm run build",
    "test:once": "karma start karma.conf.js --single-run",
    "lint": "tslint ./src/**/*.ts -t verbose"
  },

my error report:
D:\my-proj>npm start

> angular-quickstart@1.0.0 prestart D:\my-proj
> npm run build


> angular-quickstart@1.0.0 build D:\my-proj
> tsc -p src/

src/app/comments/components/comment-form.component.ts(8,10): error TS2305: Module '"D:/my-proj/node_modules/@angular/common/common"' has no exported member 'NgForm'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kaarivanan.e\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! This is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\my-proj\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kaarivanan.e\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! This is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\my-proj\npm-debug.log

**Comment by ShashankPRS** [comment]
Try changing in your package.json file. 
"start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" to "start": "concurrently \"npm run tsc:w\" \"npm run lite\". Worked for me.

**Comment by alfla** [comment]
Same error

**Comment by kumbharamol22** [comment]
Same Issue....

**Comment by ajaykangare** [comment]
same issue

**Comment by PrasadCertprime** [comment]
Found 14 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HALIS\AppData\Roaming\npm-cache\_logs\2019-06-09T06_23_52_517Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HALIS\AppData\Roaming\npm-cache\_logs\2019-06-09T06_23_52_654Z-debug.log
