### ISSUE TITLE
Update to reflect ASP.NET Core and wwwroot

### ISSUE THREAD

**Issue by technoloG** [angular/quickstart#142]
The current Quick-Start structure is geared toward ASP.NET 4.x projects.

With the release of ASP.NET Core all static files are hosted in `wwwroot`, however packages obtained via NPM are in a sibling `node_modules`, which cannot be accessed from files in `wwwroot`.

Ideally, the necessary files could be obtained via Bower, which creates a copy of files in `wwwroot/lib`. At the minimum, there should be additional capabilities to copy the files obtained from NPM to `wwwroot/lib`, or it should be clearly stated in the documentation.

**Comment by VahidN** [comment]
You should not reference to `node_modules` folders directly.
Use [webpack](https://angular.io/docs/ts/latest/guide/webpack.html) to deploy the app.

**Comment by Foxandxss** [comment]
This quickstart was never done with asp.net in mind.

**Comment by technoloG** [comment]
I was under the impression that the Quickstart was for developing Angular 2 projects in Visual Studio 2015. If I am mistaken, please advise.

That being said, as of Step 3 in the QuickStart documentation, it is suggested to open a new ASP.NET project in Visual Studio. While suggested workflow works for ASP.NET 4.x projects, things have changed in ASP.NET 5 - better known as ASP.NET Core - projects. The impression left wasn't one with a focus on ASP.NET development, but more of a workflow with said projects.

As of recent updates to Visual Studio 2015 and the introduction of ASP.NET Core, the project structure has changed slightly, including explicitly having `wwwroot` in the root of the project - where static files are intended to reside and be viewed in the browser. As a result, the steps provided in the QuickStart for Visual Studio 2015 don't necessarily apply.

The assumption was that the QuickStart was intended to help get things up and running quickly in Visual Studio. Doing a full deploy - using Webpack or otherwise - seems like overkill at that point. However, as it stands, some additional consideration for the latest project workflow in Visual Studio would be helpful.

**Comment by Foxandxss** [comment]
We have a guide for visual studio in the page. Do you mean that one?

**Comment by technoloG** [comment]
I'm referring to the Visual Studio 2015 QuickStart documentation, under the Cookbook section:
https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html

**Comment by filipesilva** [comment]
@technoloG this repo contains code for https://angular.io/docs/ts/latest/quickstart.html. The guide you linked is specifically for adapting the code present in this repo for use in a ASP.NET 4.x project.

If you would like the guide to be updated with this information, you should open an issue in https://github.com/angular/angular.io instead, since that is where the guide is.

**Comment by technoloG** [comment]
Done. See here: https://github.com/angular/angular.io/issues/1752

Thanks for the guidance.
