### ISSUE TITLE
nam install hangs for me

### ISSUE THREAD

**Issue by mid0ri** [angular/quickstart#150]
I just wrote the npm install and it's been over an hour and still not done. It's ridiculously slow, why would anyone use this? 

This is what was in my terminal before it began to hang:

MacBook-Air:my-proj$ ls
CHANGELOG.md		favicon.ico		styles.css
Dockerfile		index.html		systemjs.config.js
LICENSE			karma-test-shim.js	tsconfig.json
README.md		karma.conf.js		tslint.json
app			package.json		typings.json
e2e			protractor.config.js	wallaby.js
MacBook-Air:my-proj$ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by Foxandxss** [comment]
Be sure to use npm 3.x

**Comment by mid0ri** [comment]
i am using nam v 3.9.5

**Comment by mid0ri** [comment]
I figured it out; it was on a flash drive
