### ISSUE TITLE
docker and angular watch changes

### ISSUE THREAD

**Issue by andy-dev** [angular/quickstart#153]
Working for the first time with docker and angular, and ran into an issue still not sure how to resolve. 

Is there any way to get the browser to watch changes and refresh on those changes, at the moment, I have to rebuild i.e (docker build -t ng2-quick . ) to see the changes I made in the app.

thanks in advance

**Comment by diegotham** [comment]
You can use a volume, for example with a docker-compose.yml like this:

 version: '2'
 services:
   angular:
     build: .
     ports:
      - 80:3000
     volumes:
      - ./app:/quickstart/app

**Comment by daeiouabc** [comment]
Hi @andy-dev ! i had the same problem, this works for me:

**Dockerfile:**
```
FROM node:latest
WORKDIR /quickstart
COPY package.json /quickstart/
RUN npm install --unsafe-perm=true
CMD npm start
```

1. delete the `.dockerignore` file, or delete the line `node_modules/` in the  `.dockerignore` file.
2. build the image, for example `docker build -t angular2  .`
3. run the container with `docker run -it --rm  -v **host_path**:/quickstart -p 3000:3000 -p 3001:3001 angular2
`

now, when you modify  the project files, the project is 'compiled' again, and the browser is refreshed.

**Comment by wardbell** [comment]
Closing because this repo soon will no longer offer docker support (see PR #287). We think docker is great but it's a separate concern, apart from our goal of providing an _essential_ seed for Angular development that is consistent with the documentation sample. Docker would be good for a documentation cookbook.
