### ISSUE TITLE
angular 2 JS quickstart fail at lite server

### ISSUE THREAD

**Issue by DavidShechtman** [angular/quickstart#154]
I have tried removing my node-modules and then npm-installing but to no avail. I am unsure why this is failing. Thoughts? 

running windows 7

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'tsc:w' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose stack Error: missing script: tsc:w
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
5 verbose cwd C:\Users\******\My Documents\Billing Hours Project
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "tsc:w"
8 error node v4.4.7
9 error npm  v2.15.8
10 error missing script: tsc:w
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by Foxandxss** [comment]
Have you check in the README if your node & npm versions match the needed ones?

**Comment by DavidShechtman** [comment]
Thank you for the idea! They were out of date(relative to the README), but I have updated them and I believe I am getting a similar issue. 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\dshechtman\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.5
3 info using node@v5.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-quickstart@1.0.0~prestart: angular2-quickstart@1.0.0
6 silly lifecycle angular2-quickstart@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-quickstart@1.0.0~start: angular2-quickstart@1.0.0
8 verbose lifecycle angular2-quickstart@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-quickstart@1.0.0~start: PATH: C:\Users\dshechtman\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\dshechtman\My Documents\Billing Hours Project\node_modules\.bin;C:\Program Files\nodejs;C:\cygwin64\usr\local\bin;C:\cygwin64\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\nodejs;C:\Users\dshechtman\AppData\Roaming\npm;C:\Users\dshechtman\AppData\Local\atom\bin
10 verbose lifecycle angular2-quickstart@1.0.0~start: CWD: C:\Users\dshechtman\My Documents\Billing Hours Project
11 silly lifecycle angular2-quickstart@1.0.0~start: Args: [ '/d /s /c', 'npm run lite' ]
12 silly lifecycle angular2-quickstart@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular2-quickstart@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-quickstart@1.0.0 start: `npm run lite`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\dshechtman\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:88:13)
14 verbose stack     at EventEmitter.emit (events.js:173:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\dshechtman\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:88:13)
14 verbose stack     at ChildProcess.emit (events.js:173:7)
14 verbose stack     at maybeClose (internal/child_process.js:819:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:212:5)
15 verbose pkgid angular2-quickstart@1.0.0
16 verbose cwd C:\Users\dshechtman\My Documents\Billing Hours Project
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dshechtman\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.2.0
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error angular2-quickstart@1.0.0 start: `npm run lite`
22 error Exit status 1
23 error Failed at the angular2-quickstart@1.0.0 start script 'npm run lite'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-quickstart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run lite
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-quickstart
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-quickstart
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
