### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by kornelc** [angular/quickstart#156]
Angular 2 Quick Start doesn't address CORS, which is a very frequent use case for REST. Could a cross site request example be included in the Quick Start/Tutorial docs?

**Comment by jiggy1com** [comment]
Weird! I was just running into this issue with my app last night. I'm using nodejs, so I ran npm install cors Check out npmjs, it will provide useful info if nodejs is your backend (even with nginx or apache proxy). I found an article explaining "preflight" ... And that's what Angular does, so you might look into that, too.

**Comment by MurDaD** [comment]
I'm working on developing quickstart into some king of game. And it's using PHP as API.
You can find CORS fix in this commit https://github.com/MurDaD/heroes-of-angular2/commit/1e5648753829714b349cee383b6fd570d7fe4a8a

**Comment by Foxandxss** [comment]
This is more of a backend thing and is outside the scope of this quickstart.
