### ISSUE TITLE
"GET /app.es6" Error (404): "Not found"

### ISSUE THREAD

**Issue by daniel-halldorsson** [angular/quickstart#16]
I think there are some missing instructions in the current quickstart tutorial up at https://angular.io/docs/js/latest/quickstart.html

when attempting to run from http-server i get the following error:
"GET /app.es6" Error (404): "Not found"

im guessing it is something to do with system.js not being included, i tried running npm install in the /quickstart dir and then including the link to its node module in index.html but i then get the following error:

Uncaught (in promise) RangeError: Error loading "app" at <unknown>
Maximum call stack size exceeded {stack: (...), message: "Error loading "app" at <unknown>↵Maximum call stack size exceeded"}

**Comment by wardbell** [comment]
Closed. Obsolete.
