### ISSUE TITLE
page not render

### ISSUE THREAD

**Issue by wangjingyi** [angular/quickstart#161]
The page is not rendered when I run the program. I attached a screenshot here after run the test.

node v6.3.1
npm v3.10.5

![capture](https://cloud.githubusercontent.com/assets/341953/17079997/bfd92522-50e6-11e6-8cdc-fc46839ae5a4.PNG)

**Comment by filipesilva** [comment]
It seems like you have a compilation issue, can you show me the full error output of the console?

**Comment by wangjingyi** [comment]
[npm-debug.log.txt](https://github.com/angular/quickstart/files/385013/npm-debug.log.txt)

**Comment by wangjingyi** [comment]
![capture](https://cloud.githubusercontent.com/assets/341953/17158893/0999365a-535f-11e6-97ac-66a5100dbe2c.PNG)

**Comment by wangjingyi** [comment]
When I did npm install, i was getting the warning(see attached).  Does the warning cause not page rendered (when I did npm start)?

![capture](https://cloud.githubusercontent.com/assets/341953/17159024/ec1734dc-535f-11e6-8718-3730c9d3af64.PNG)

**Comment by filipesilva** [comment]
Apologies for the delay getting back to you. I went through the log and couldn't find anything weird to be honest... Does `npm start` work and serve your files? 

The warning you show shouldn't cause any problems, they're common warnings about optional dependencies and typings.

Did you make any changes to the application? If you put up a repo, I will look at it and see if I get the same problem.

**Comment by wardbell** [comment]
Closing as your issue is old. Please re-open as a new issue if problem persists.
