### ISSUE TITLE
not running in bluemix and aws uploaded sample code and need to configure in html

### ISSUE THREAD

**Issue by maddela** [angular/quickstart#163]
Hello sir

I uploaded the quickstart in AWS and bluemix servers . Instance is not created. after uploading to server config issues are comming. I want to write angular 2 with php . How to configure with basic html .

**Comment by filipesilva** [comment]
The quickstart doesn't cover any particular server side language, nor a particular server setup. It is up to the user to adapt this setup to their technologies of choice. 

All I can say is that if it works locally but not remotely, it's probably due to misconfiguration.
