### ISSUE TITLE
can write angular 2 with html and javascript without node if there please tell how to do

### ISSUE THREAD

**Issue by maddela** [angular/quickstart#164]
Ok Is there steps to configure angular 2 with plain html. can write Directives components with javascript. can you tell how to do. In the quickstart you have given node application

**Comment by jiggy1com** [comment]
You mean running npm start ? 
That's the web server etc. watches for changes to your files and will reload your app in the browser. Great for development!

If you don't want to do that, just compile your .ts files to .js on your own, and load the index page with IIS, Apache, Nginx or whatever web server of your choice.

**Comment by filipesilva** [comment]
@jiggy1com comment is spot on.

Angular 2 is a javascript framework, so you will always need to run javascript to use it. Other than that it just uses plain html and typescript. 

It is true that the dev server we provide is a node application, but it does little more than just serve your files.
