### ISSUE TITLE
npm install err

### ISSUE THREAD

**Issue by milad1367** [angular/quickstart#165]
I am following "Angular 2" quickstart .When trying to do "npm  install" it is failing at "typings install" step.

PS C:\Users\Milad\angular2-quickstart> npm install
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> angular2-quickstart@1.0.0 postinstall C:\Users\Milad\angular2-quickstart
> typings install

typings WARN deprecated 7/20/2016: "registry:dt/node#6.0.0+20160621231320" is deprecated (updated, replaced or removed)
typings ERR! message Unable to read typings for "jasmine". You should check the entry paths in "jasmine.d.ts" are up to
date
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/c49913aa9
ea419ea46c1c684e488cf2a10303b1a/jasmine/jasmine.d.ts"
typings ERR! caused by connect ECONNREFUSED 10.10.34.36:443

typings ERR! cwd C:\Users\Milad\angular2-quickstart
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Milad\\angular2-quickstart\\node_modules\\typings
\\dist\\bin.js" "install"
typings ERR! node -v v6.3.1
typings ERR! typings -v 1.3.2

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angular2-quickstart@1.0.0 No description
npm WARN angular2-quickstart@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Milad\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\np
m-cli.js" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart@1.0.0 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-quickstart@1.0.0 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Milad\angular2-quickstart\npm-debug.log
PS C:\Users\Milad\angular2-quickstart>

please help me!

**Comment by VahidN** [comment]
10.10.34.36:443 means https://raw.githubusercontent.com is filtered/censored in your country. But there's a better way to manage it these days. The new recommendation according to TS is to use NPM to manage your Typings:
```
npm install --save-dev @types/core-js
```
It's the same as installing a normal npm package, but it has @types/ at the beginning. You can find the installed package in the node_modules\@types folder.
