### ISSUE TITLE
Error thrown in events.js running e2e test

### ISSUE THREAD

**Issue by alaingmail** [angular/quickstart#167]
I'm getting an error when running e2e test on my Windows 10 machine. 

I run the command line: npm run e2e

I get the following error:

C:\Temp\quickstart-master>npm run e2e

> angular2-quickstart@1.0.0 pree2e C:\Temp\quickstart-master
> npm run webdriver:update

> angular2-quickstart@1.0.0 webdriver:update C:\Temp\quickstart-master
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> angular2-quickstart@1.0.0 e2e C:\Temp\quickstart-master
> tsc && concurrently "http-server -s" "protractor protractor.config.js" --kill-others --success first

[0] events.js:160
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: listen EADDRINUSE 0.0.0.0:8080
[0]     at Object.exports._errnoException (util.js:1008:11)
[0]     at exports._exceptionWithHostPort (util.js:1031:20)
[0]     at Server._listen2 (net.js:1253:14)
[0]     at listen (net.js:1289:10)
[0]     at net.js:1399:9
[0]     at _combinedTickCallback (internal/process/next_tick.js:77:11)
[0]     at process._tickCallback (internal/process/next_tick.js:98:9)
[0]     at Module.runMain (module.js:577:11)
[0]     at run (bootstrap_node.js:352:7)
[0]     at startup (bootstrap_node.js:144:9)
[0] http-server -s exited with code 1
--> Sending SIGTERM to other processes..
[1] protractor protractor.config.js exited with code 1

**Comment by Foxandxss** [comment]
For some reason, your port 8080 is in use.

**Comment by usamakhalil86** [comment]
npm run e2e is failing 

with below error.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'e2e' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'pree2e', 'e2e', 'poste2e' ]
6 info pree2e angular2-quickstart@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info e2e angular2-quickstart@1.0.0
9 verbose unsafe-perm in lifecycle true
10 info angular2-quickstart@1.0.0 Failed to exec e2e script
11 verbose stack Error: angular2-quickstart@1.0.0 e2e: `tsc && concurrently "http-server -s" "protractor protractor.config.js" --kill-others --success first`
11 verbose stack Exit status 1
11 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
11 verbose stack     at EventEmitter.emit (events.js:110:17)
11 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
11 verbose stack     at ChildProcess.emit (events.js:110:17)
11 verbose stack     at maybeClose (child_process.js:1015:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
12 verbose pkgid angular2-quickstart@1.0.0
13 verbose cwd C:\Users\usama.khalil\Downloads\quickstart-master
14 error Windows_NT 6.1.7601
15 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "e2e"
16 error node v0.12.2
17 error npm  v2.7.4
18 error code ELIFECYCLE
19 error angular2-quickstart@1.0.0 e2e: `tsc && concurrently "http-server -s" "protractor protractor.config.js" --kill-others --success first`
19 error Exit status 1
20 error Failed at the angular2-quickstart@1.0.0 e2e script 'tsc && concurrently "http-server -s" "protractor protractor.config.js" --kill-others --success first'.
20 error This is most likely a problem with the angular2-quickstart package,
20 error not with npm itself.
20 error Tell the author that this fails on your system:
20 error     tsc && concurrently "http-server -s" "protractor protractor.config.js" --kill-others --success first
20 error You can get their info via:
20 error     npm owner ls angular2-quickstart
20 error There is likely additional logging output above.
21 verbose exit [ 1, true ]
