### ISSUE TITLE
change the server npm installing

### ISSUE THREAD

**Issue by milad1367** [angular/quickstart#168]
i not use npm proxy.
in my country block the server npm installing. I want to use another server to instaling npm.
How to do it?
please help me.
![untitled](https://cloud.githubusercontent.com/assets/15375991/17274509/b9a5a658-56f9-11e6-8b0f-92c0d47d3368.jpg)

**Comment by filipesilva** [comment]
Ok, seems the problem is in https://github.com/typings/typings. As part of our `npm install`, we also run `typings install`.

Here is the configuration instructions for it, showing how to add a proxy: https://github.com/typings/typings/blob/master/docs/faq.md#configuration

**Comment by milad1367** [comment]
tnx for answer.
im try with typings install.but i have same problems.:(((((((
