### ISSUE TITLE
npm failed on ubuntu 16.04

### ISSUE THREAD

**Issue by motkeg** [angular/quickstart#171]
After cloning the 'quickstart' and run `npm install` I get an error:

```
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
Killed          ...] - extract:underscore.string: **sill gunzTarPerm** modified mode [ 'ts/c

```

it seems to have problem with **gunzTarPerm**

_node -v_ : 6.3.1
_npm -v_ : 3.10.3

**Comment by motkeg** [comment]
Help somebody?

**Comment by filipesilva** [comment]
Might be a problem with your npm install or connection, as `gunzTarPerm` is part of how `npm` works.

I can't really say much more than that... your problem seems unrelated to the quickstart itself.
