### ISSUE TITLE
Hanging `,` in systemjs.config

### ISSUE THREAD

**Issue by Mutmatt** [angular/quickstart#172]
On line 33 after `'upgrade'` there is a hanging `,`

![image](https://cloud.githubusercontent.com/assets/872224/17330620/1c44764c-588d-11e6-9633-57afae921778.png)

**Comment by filipesilva** [comment]
It's mostly a matter of style. Some style-guides recommend to do that since it makes adding a new array element easier and also makes git diffs easier to read. I don't see a big reason to change it, though.
