### ISSUE TITLE
Update tough-cookie and minimatch due to security risks

### ISSUE THREAD

**Issue by llarsson** [angular/quickstart#173]
Upon running `npm install` on a brand new checkout, I get the following security-related warnings:

```
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

Perhaps those version numbers should be incremented, unless there is a specific reason to keep those libraries at the stated versions.

**Comment by Foxandxss** [comment]
We don't depend on those libraries directly, is a dependency of a dependency. I will check if any of those dependencies got an update.

**Comment by wardbell** [comment]
Closing as your issue is old. Please re-open as a new issue if problem persists.
