### ISSUE TITLE
Failed to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by crypto5** [angular/quickstart#174]
Hi,

I am new in JS development, and am currently trying to follow steps in quickstart, however when I type "npm install", I have following error:

npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> angular2-quickstart@1.0.0 postinstall /home/a/tmp/angular2-quickstart
> typings install

/usr/bin/env: ‘node’: No such file or directory

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angular2-quickstart@1.0.0 No description
npm WARN angular2-quickstart@1.0.0 No repository field.
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular2-quickstart@1.0.0 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular2-quickstart@1.0.0 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/a/tmp/angular2-quickstart/npm-debug.log

**Comment by crypto5** [comment]
Looks like it is problem with standard ubuntu nodejs distribution.
I uninstalled ubuntu nodejs, and installed nodejs using inctructions from https://github.com/nodesource/distributions#debinstall, and it solved the problem.

**Comment by lucassus** [comment]
@crypto5 you can also try install nodejs via https://github.com/creationix/nvm
