### ISSUE TITLE
please update code snippet ==> rm -rf .git  // non-Windows

### ISSUE THREAD

**Issue by elad2109** [angular/quickstart#176]
I have followed the tutorial
and mistakenly copy-pasted this line:

`rm -rf .git  // non-Windows`

this cmd is actually same as `rm -rf  / ` which deleted all my localUser files.

please change to `rm -rf .git # non-Windows`

**Comment by filipesilva** [comment]
Fair point. Fix in https://github.com/angular/quickstart/pull/177.
