### ISSUE TITLE
npm start ends with these error while `typings install`.

### ISSUE THREAD

**Issue by jmj4you** [angular/quickstart#178]
npm start ends with these error while `typings install`.

node v6.3.1
npm ERR! npm  v3.10.3

*************************

72511 verbose stack Error: angular2-quickstart@1.0.0 postinstall: `typings install`
72511 verbose stack Exit status 1
72511 verbose stack     at EventEmitter.<anonymous> (/home/jmj/.nvm/versions/node/v6.3.1/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
72511 verbose stack     at emitTwo (events.js:106:13)
72511 verbose stack     at EventEmitter.emit (events.js:191:7)
72511 verbose stack     at ChildProcess.<anonymous> (/home/jmj/.nvm/versions/node/v6.3.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
72511 verbose stack     at emitTwo (events.js:106:13)
72511 verbose stack     at ChildProcess.emit (events.js:191:7)
72511 verbose stack     at maybeClose (internal/child_process.js:852:16)
72511 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
72512 verbose pkgid angular2-quickstart@1.0.0
72513 verbose cwd /home/jmj/Angular2/quickstart
72514 error Linux 3.13.0-91-generic
72515 error argv "/home/jmj/.nvm/versions/node/v6.3.1/bin/node" "/home/jmj/.nvm/versions/node/v6.3.1/bin/npm" "install"
72516 error node v6.3.1
72517 error npm  v3.10.3
72518 error code ELIFECYCLE
72519 error angular2-quickstart@1.0.0 postinstall: `typings install`
72519 error Exit status 1
72520 error Failed at the angular2-quickstart@1.0.0 postinstall script 'typings install'.
72520 error Make sure you have the latest version of node.js and npm installed.
72520 error If you do, this is most likely a problem with the angular2-quickstart package,
72520 error not with npm itself.
72520 error Tell the author that this fails on your system:
72520 error     typings install
72520 error You can get information on how to open an issue for this project with:
72520 error     npm bugs angular2-quickstart
72520 error Or if that isn't available, you can get their info via:
72520 error     npm owner ls angular2-quickstart
72520 error There is likely additional logging output above.
72521 verbose exit [ 1, true ]

**Comment by Foxandxss** [comment]
That doesn't say anything useful, I believe the proper error is before that blurb.

**Comment by saadaouad** [comment]
@jmj4you can you change the file package.json with this : 
`{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "npm run lite",
    "lite": "lite-server"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.5",

    "core-js": "^2.4.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12",

    "angular2-in-memory-web-api": "0.0.15",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0"
  }
}`

**Comment by saadaouad** [comment]
@jmj4you can you change the file package.json with this : 
:point_down:

**Comment by saadaouad** [comment]
{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "npm run lite",
    "lite": "lite-server"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.5",

    "core-js": "^2.4.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12",

    "angular2-in-memory-web-api": "0.0.15",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0"
  }
}

**Comment by jmj4you** [comment]
@saadaouad Thank you very much, Now works fine,
