### ISSUE TITLE
strip_maps.sh fails for unknown reasons

### ISSUE THREAD

**Issue by matteosuppo** [angular/quickstart#18]
```bash 
$ sh strip_maps.sh 
sed: can't read : No such file or directory
```

But the file exists:

```bash
$ ls dist/es6-shim.js 
dist/es6-shim.js
```

**Comment by nalbion** [comment]
I experienced the same error.  The command seems to be doing what it needs to, so I instructed gulp_shell to ignore the error:

    // strip off the sourceMaps.
    gulp.task('build:strip_maps', shell.task(["sh strip_maps.sh"], {ignoreErrors:true}));

...that seemed to result in an empty `dist/es6-shim.js` file - not much use.

What did work, was to add `|| true` at the end of `strip_maps.sh`:

    sed -e '/^\/\/\# source/d' -i '' dist/es6-shim.js || true

**Comment by davideast** [comment]
We're going to be migrating off of this quickstart soon in lieu of a better solution.

Don't run any commands within this repo. The strip_maps file is not meant to ran in isolation either.

**Comment by wardbell** [comment]
Closed. Obsolete.
