### ISSUE TITLE
npm install - 400 bad request

### ISSUE THREAD

**Issue by Gennady77** [angular/quickstart#180]
It is not difficult to guess, when I do npm install I have error - 400 bad request.

**Comment by Enaldi** [comment]
404s for Angular. For example:

 [(http://registry.npmjs.org/angular/core/2.0.0-rc.5)]

**Comment by Foxandxss** [comment]
I need more information.

**Comment by wardbell** [comment]
Closing as your issue is old. Please re-open as a new issue if problem persists.
