### ISSUE TITLE
Behavior of the CommonChunkPlugin in the Webpack example

### ISSUE THREAD

**Issue by daffunn** [angular/quickstart#182]
As described [here](https://angular.io/docs/ts/latest/guide/webpack.html) I am importing all vendor libraries within my `vendor.ts`.

Unfortunately this does not work with all libraries. Although I added `import * as WebFont from 'webfontloader';` to `vendor.ts`, the library is written into `app.ts` as I also import it there. 

When I change `import * as WebFont from 'webfontloader';` to `let WebFont = require('webfontloader');` it does work. 

What's wrong? Why are all imports of angular working then?

**Comment by Foxandxss** [comment]
Hello, this is the wrong repository, this is just the quickstart (no webpack involved).

I would consider stackoverflow for that.
