### ISSUE TITLE
Cant Use StyleUrl

### ISSUE THREAD

**Issue by lyminster** [angular/quickstart#185]
cant use style url, no error to be found, but when using style it can be done

**Comment by filipesilva** [comment]
Can you provide some repro steps please?

**Comment by lyminster** [comment]
1  create folder login under app
2 create login.ts , login.html, login.css
3 in login.ts @component 
```
@Component({
    selector: 'login',
    templateUrl: '/app/login/login.html',
    //styleUrls: ['/app/login/login.css']
    styles: [`
    .page {
    margin-top:50px;
    margin-left:auto;
    margin-right:auto;
    width:500px;
    }
    `]
})
```
when i put the css in styles its work, but when i put it under login.css it doesnot work and not give an error too,
please correct me if im wrong Thanks

**Comment by filipesilva** [comment]
I tried to reproduce it in plunker, but it works for me: http://plnkr.co/edit/NYpd31tw1sTr6vFhKebg?p=preview

The only difference I see is that I used dot at the start of the url path `'./app/login/login.css'`.

**Comment by filipesilva** [comment]
Do you get an error in the browser console?

**Comment by lyminster** [comment]
no error, but the html works, now if i put dot in front it work, thanks

**Comment by filipesilva** [comment]
Glad it hear that helped!
