### ISSUE TITLE
npm test fails when zone.js is 0.6.14

### ISSUE THREAD

**Issue by psnider** [angular/quickstart#186]
I just did a fresh install of version 6ce71a08f6356b7a68325df25944de7610090207  
- Mac with OS El Capitan 10.11.6  
- node v5.12.0

When I run **npm test**, it fails and displays:
```
[1] Chrome 52.0.2743 (Mac OS X 10.11.6) ERROR
[1]   Uncaught Error: Missing: SyncTestZoneSpec
[1]   at /private/tmp/qwob/quickstart/node_modules/zone.js/dist/jasmine-patch.js:66
```

I'm able to get around this by downgrading zone.js back to 0.6.12.  I changed package.json to reference the exact version of zone.js:
```
    "zone.js": "0.6.12",
```
Also, to prevent these types of problems, please change the dependencies in package.json to be exact.

**Comment by filipesilva** [comment]
@Foxandxss I know you were having some issues with `zone` as well, can you weigh in?

**Comment by psnider** [comment]
I'm not familiar with zone.js yet, but found the cause by comparing an older working tutorial, and the latest version.  I compared the results of *npm list* in the two workspaces, then I narrowed the problem down to zone.js.

**Comment by Foxandxss** [comment]
Yes, we needed to merge #184. Now it is done, and it should work for everyone.
