### ISSUE TITLE
deploy script

### ISSUE THREAD

**Issue by Admdebian** [angular/quickstart#188]
Which is the best way to build a package to deploy on a web server?

**Comment by hanokhaloni** [comment]
+1 to this. There seems to be no "best-practice" to deploy angular 2 apps.

**Comment by bjorkblom** [comment]
+1

**Comment by jonathanHZ** [comment]
+1

**Comment by vrabota** [comment]
+1

**Comment by JhernandezZ** [comment]
+1

**Comment by MurDaD** [comment]
Angular CLI - the best and easiest way I think

**Comment by Admdebian** [comment]
I see Angular CLI creates a new app, a new karma conf and so on.

I'd like to use this starter kit.

**Comment by thompsonemerson** [comment]
+1

**Comment by bjornharvold** [comment]
+1 I looked at Angular CLI as well but I'd like to see this project come up with a solve. Right now, the development part of this project uses lite-server and hot reload is 3 times faster than the Angular CLI setup right now. I also don't like Angular CLI's way of having to build per environment. There is a great article: http://www.jvandemo.com/how-to-configure-your-angularjs-application-using-environment-variables/ about externalizing the environment file from the build. The deployment phase can be responsible for providing the app with the correct environment variables. "Build once - Deploy anywhere".

Cheers!

**Comment by wardbell** [comment]
That's a great question for angular.io. It is out-of-scope for quickstart. Closing
