### ISSUE TITLE
App fails to compile when using rootDir

### ISSUE THREAD

**Issue by haisaco** [angular/quickstart#189]
App fails to compile when using rootDir with @NgModel.
When I using rootDir, @NgModel not found constructor ex: not parameter "AppComponent(?)".

**Comment by wardbell** [comment]
Sorry but we do not have enough information and there are many confusing parts to these two sentences. What is `@NgModel`? Do you mean `@NgModule`? What is `rootDir`?

Closing as your issue is old. Please re-open as a new issue if problem persists.
