### ISSUE TITLE
Setup test coverage

### ISSUE THREAD

**Issue by lucassus** [angular/quickstart#194]
Ideally with html reporter like http://gotwarlost.github.io/istanbul/public/coverage/lcov-report/index.html
Is it currently possible to do that without crazy hacks?

**Comment by Cayan** [comment]
I took a while to figure it out and now I have a proper coverage report for my TS ng2 project. I'll try to open a PR with it.

**Comment by Foxandxss** [comment]
Before you spend the time in that, I'm going to ask if we want that in this repo

**Comment by wardbell** [comment]
Testing has evolved since this issue was opened. Closing as out of date. Please re-open as a new issue if problem persists.
