### ISSUE TITLE
Directive sample example

### ISSUE THREAD

**Issue by ivanhoinacki** [angular/quickstart#198]
I had trouble running the quickstart because of, can contribute to this situation.

**Comment by filipesilva** [comment]
Can you explain what situation you had difficulty with?

**Comment by ivanhoinacki** [comment]
@filipesilva I found the lack of an example with directive, I would like to share my idea, but it's my first contribution, I have some difficulties

**Comment by filipesilva** [comment]
This repository is not mean to have examples of directives, but rather to show the end result of the Quickstart chapter in https://angular.io/docs/ts/latest/quickstart.html. 

You can fin an example of creating an attribute directive in https://angular.io/docs/ts/latest/guide/attribute-directives.html.
