### ISSUE TITLE
[es6-shim.js] Register new Polymer elements - callbacks/prototype chain

### ISSUE THREAD

**Issue by KenavR** [angular/quickstart#2]
I'm sorry if this isn't the right place to put this issue, but I am not sure if the es6-shim.js file is custom-built for this project or if this could be an issue for angular2 in general.

In the "Zone.patchRegisterElement" function (around line 33335) it is assumed that the callback functions are a "own" property of the "prototype" object to get the descriptor.
```javascript
    Object.getOwnPropertyDescriptor(opts.prototype, callback);
```

But some polymer elements seem to have them higher up the chain. [Prism-js](http://addyosmani.github.io/prism-js/components/prism-js/) for example has the Polymer root one level higher. Is this an issue that should be addressed while registering the element or is there something wrong with this specific polymer element?

thanks

**Comment by davideast** [comment]
Thanks for letting us know about this issue.

This isn't a general Angular 2 file. The `es6-shim.js` is just a big glob of concatenated files that allow you run ES6 code in a current browser. It's just to get people up and running for the quickstart on the angular.io site.

All of this will change when TypeScript 1.5 releases with meta-data annotation support.
