### ISSUE TITLE
Directives running errors 

### ISSUE THREAD

**Issue by nicks78** [angular/quickstart#210]
The application still working but i need to comment out the directives to be able to "npm start" and then redo the directive. This error did not show on RC5

> error TS2345: Argument of type '{ selector: string; templateUrl: string; styleUrls: string[]; directives: (typeof RegisterCompone...' is not assignable to parameter of type 'ComponentMetadataType'.
> Object literal may only specify known properties, and 'directives' does not exist in type 'ComponentMetadataType'.

**Comment by jecacs** [comment]
I have a similar problem

**Comment by kevineo** [comment]
Same here

**Comment by Foxandxss** [comment]
RC6 doesn't have the `directives` property anymore.

**Comment by kevineo** [comment]
Ok. So how do we go around not having directives in our @Component? Because the app freezes at the loading screen.

**Comment by Foxandxss** [comment]
You need NgModules, check the doc.
