### ISSUE TITLE
similar issue as #203

### ISSUE THREAD

**Issue by DeepshikhaKalra** [angular/quickstart#211]
I am facing similar problem as reported in #203. I get error when i do npm start. On close debugging i found that "tsc -w" is failing. You can close this if you thing that #203 and this one is related..

I am on mac, with tsc version 1.8.10, typings 1.3.3 and node 6.5.0.

simply doing "tsc -w" gives me the following error:

quickstart $ tsc -w
fs.js:1431
throw error;
^

Error: watch /users/u/projects/experiements/rc6/quickstart ENOENT
at exports._errnoException (util.js:1026:11)
at FSWatcher.start (fs.js:1429:19)
at Object.fs.watch (fs.js:1456:11)
at addDirWatcher (/usr/local/lib/node_modules/typescript/lib/tsc.js:1036:39)
at Object.addFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:1051:21)
at Object.watchFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:1172:48)
at Object.executeCommandLine (/usr/local/lib/node_modules/typescript/lib/tsc.js:34546:44)
at Object. (/usr/local/lib/node_modules/typescript/lib/tsc.js:34877:4)
at Module._compile (module.js:556:32)
at Object.Module._extensions..js (module.js:565:10)

I have tried almost everything mentioned in this issue chain, but it's not working.

**Comment by ShaneRich5** [comment]
Following these instructions fix that for me:

[http://stackoverflow.com/questions/34335340/angular2-quickstart-npm-start-is-not-working-correctly](http://stackoverflow.com/questions/34335340/angular2-quickstart-npm-start-is-not-working-correctly)

They essentially installed some of the dependencies globally with:

`sudo npm install -g concurrently lite-server typescript`

**Comment by DeepshikhaKalra** [comment]
Shane, The instructions do not help!

> quickstart $ sudo npm install -g concurrently lite-server typescript
> Password:
> npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
> /usr/local/bin/concurrently -> /usr/local/lib/node_modules/concurrently/src/main.js
> /usr/local/bin/concurrent -> /usr/local/lib/node_modules/concurrently/src/main.js
> /usr/local/bin/lite-server -> /usr/local/lib/node_modules/lite-server/bin/lite-server
> /usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
> /usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
> /usr/local/lib
> ├── concurrently@2.2.0 
> ├─┬ lite-server@2.2.2 
> │ └─┬ browser-sync@2.15.0 
> │   ├─┬ chokidar@1.6.0
> │   │ ├── inherits@2.0.3 
> │   │ └─┬ is-binary-path@1.0.1
> │   │   └── binary-extensions@1.6.0 
> │   ├─┬ fs-extra@0.30.0
> │   │ └─┬ rimraf@2.5.4
> │   │   └─┬ glob@7.0.6
> │   │     └── once@1.4.0 
> │   └─┬ serve-index@1.8.0
> │     └─┬ http-errors@1.5.0
> │       └── inherits@2.0.1 
> └── typescript@1.8.10 
> 
> quickstart $ tsc -w
> fs.js:1431
>     throw error;
>     ^
> 
> Error: watch /users/kalra/projects/experiements/rc6/quickstart ENOENT
>     at exports._errnoException (util.js:1026:11)
>     at FSWatcher.start (fs.js:1429:19)
>     at Object.fs.watch (fs.js:1456:11)
>     at addDirWatcher (/usr/local/lib/node_modules/typescript/lib/tsc.js:1036:39)
>     at Object.addFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:1051:21)
>     at Object.watchFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:1172:48)
>     at Object.executeCommandLine (/usr/local/lib/node_modules/typescript/lib/tsc.js:34546:44)
>     at Object.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsc.js:34877:4)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)

**Comment by wardbell** [comment]
Old. Not about QuickStart. Closing
