### ISSUE TITLE
tsc: not found on npm start

### ISSUE THREAD

**Issue by egeogretmen** [angular/quickstart#215]
Although I have installed the dependencies with `npm install` and can see the package typescript when I do `npm list typescript`, I still get this error. Only when I `npm install -g typescript concurrently` I can manage to get `npm start` working. The angular2-quickstart guide does not state this so I suppose I should not have any problems without installing with the `-g` option. If `-g` is a must, then the guide should state this I guess.

```
vagrant@local:~/angular2-quickstart$ npm start

> angular2-quickstart@1.0.0 start /home/vagrant/angular2-quickstart
> tsc && concurrently "tsc -w" "lite-server" 

sh: 1: tsc: not found

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v6.5.0/bin/node" "/home/vagrant/.nvm/versions/node/v6.5.0/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular2-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular2-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
```

**Comment by egeogretmen** [comment]
I did do `npm install`. However I had to "globally" install tsc and concurrently for it to work

**Comment by wardbell** [comment]
You should not have to install it globally. Should work (and only work) with local install. Not having a linux box I am not able to help.

**Comment by olivierto** [comment]
+1 
I'm facing the same issue here by bulding app container from the provided dockerfile. 

`FROM node:latest

RUN mkdir -p /webapp /home/nodejs && \
    groupadd -r nodejs && \
    useradd -r -g nodejs -d /home/nodejs -s /sbin/nologin nodejs && \
    chown -R nodejs:nodejs /home/nodejs

WORKDIR /webapp
COPY package.json typings.json /webapp/
RUN npm install --unsafe-perm=true

COPY . /webapp
RUN chown -R nodejs:nodejs /webapp
USER nodejs
CMD npm start`

The weird thing here is: when i run "docker run" command code is compiling correctly. but when i'm using "docker-compose" command  it's giving me the tsc not found error.

**Comment by Dickurt** [comment]
@olivierto I had the same issue. Try adding this to your Dockerfile

```
RUN npm install -g tsc \
    && npm install -g concurrently \
    && npm install -g typescript \
```

For me, that only solved part of the issue. For some reason, npm install did not save the dependencies after installing them. So I had to manually run npm install in the docker container, i.e. `docker run angular npm install` and `docker run angular npm run typings install`.

This is only a workaround, of course. But at least it gets things going. I have yet to find a solution.

Hope that helps!

**Comment by Longfld** [comment]
Try my package, it is far more simply, and you can have ng2 cli later on for more functions.
 
https://github.com/Longfld/ng2QuickStartForBeginning

**Comment by olivierto** [comment]
@Dickurt thanks ! it works like charm thanks!

**Comment by Core2Duo** [comment]
@egeogretmen hey, I have the same issue and I have a solution for that. But (and it's more important) I have a reason of this issue.
I'm using vagrant with Debian 8 on my Win10 laptop and I have a shared folder with my project.
I had to use 'npm install' with '--no-bin-links' option because it's not possible to place a symlink in a shared folder. So, my node_modules/.bin/ directory is empty. And that's the reason of the problem.
Try 'npm bin' and see is your bin directory empty or not.
The solution is quite simple, you just have to change 'scripts' in packages.json to use local versions of the packages like that:
```javascript
"scripts": {
    "start": "node ./node_modules/concurrently/src/main.js \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "./node_modules/lite-server/bin/lite-server",
    "tsc": "./node_modules/typescript/bin/tsc",
    "tsc:w": "./node_modules/typescript/bin/tsc -w"
  }
```

**Comment by Longfld** [comment]
Make sure inside your package.json: "tsc": "tsc" is there
"scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    **"tsc": "tsc",**

**Comment by egeogretmen** [comment]
@Core2Duo hey there, although I have solved the issue my point is that I think it is misleading in the guide to assume that people should install tsc and concurrently globally or as you have suggested use the local versions from the node_modules. Nowhere in the guide says "you should use the local versions of tsc and concurrenly or install them globally". Instead it just says us to do `npm install` with this package.json as of this writing:
```javascript
{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "lite": "lite-server",
    "tsc": "tsc",
    "tsc:w": "tsc -w"
  },
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/angular/angular.io/blob/master/LICENSE"
    }
  ],
  "dependencies": {
    "@angular/common": "~2.1.1",
    "@angular/compiler": "~2.1.1",
    "@angular/core": "~2.1.1",
    "@angular/forms": "~2.1.1",
    "@angular/http": "~2.1.1",
    "@angular/platform-browser": "~2.1.1",
    "@angular/platform-browser-dynamic": "~2.1.1",
    "@angular/router": "~3.1.1",
    "@angular/upgrade": "~2.1.1",
    "angular-in-memory-web-api": "~0.1.13",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25"
  },
  "devDependencies": {
    "@types/core-js": "^0.9.34",
    "@types/node": "^6.0.45",
    "concurrently": "^3.0.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.3"
  }
}
```
This I believe should be fixed in the guide, for it may confuse some beginner developers out there.

**Comment by jfpwork** [comment]
The same error occur

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "PATH\\node.exe" "PATH\\\node_modules\\npm\\bin\\n pm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.

Find  a Trick

IF  ( js and map files are generated in app folder  )
THEN
  // do know why but in you CMD windows
  $ npm run lite  // localhost is running
  $ CTRL + C       // it is on Windows
  $ npm start      // is alive
  // somebody could explain why ?

Hope it could help

**Comment by wardbell** [comment]
Closing because there is no action here that we can or will take.

**Comment by jeansouzak** [comment]
I had the same problem with tsc and resolved on [updating my npm and node](https://tecadmin.net/upgrade-nodejs-via-npm/).
Then I ran the following commands in the quickstart folder:
`sudo npm install`
`npm start`

**Comment by rasor** [comment]
I had to copy typescript from devDependencies to
```
  "dependencies": {
    "typescript": "^2.4.0"
```
