### ISSUE TITLE
Fetch API cannot load about:blank. URL scheme "about" is not supported.

### ISSUE THREAD

**Issue by danielwertheim** [angular/quickstart#219]
Not sure if this belongs here instead: https://github.com/angular/zone.js

**Repro:**

1. clone
2. npm install
3. npm start

**Google Chrome:** Version 53.0.2785.113 m on Windows10

WORKS in Edge

![image](https://cloud.githubusercontent.com/assets/196044/18526419/d1d6d8b0-7ac0-11e6-8ea3-57ae685551cc.png)

```
zone.js:556 Fetch API cannot load about:blank. URL scheme "about" is not supported.
```

**Comment by filipesilva** [comment]
This seems related to `zone.js@0.6.22`, which was just release. Will you cross post your issue there.

**Comment by wardbell** [comment]
Closing because it doesn't belong here in QuickStart
