### ISSUE TITLE
Use node typings from the typings registry, not DT

### ISSUE THREAD

**Issue by felixfbecker** [angular/quickstart#220]
The typings from the registry are much more well-maintained. Instead of the huge monorepo they have their own repo, own issues, own PRs, own CI. You shouldn't advocate using the typings from DT.

https://github.com/types/env-node

**Comment by Foxandxss** [comment]
We will move to @types really soon.

**Comment by jacksoncharles** [comment]
I'm new to Angular2 and have started to get conflicts with the @types folder when running the typescript compiler. @types has been included as a dependency on packages such as angular2-select. Any advice on how to get around this problem? My whole project is knackered :-(

**Comment by filipesilva** [comment]
@jacksoncharles you should either use `typings`, `dt` OR `@types/`. Using more than one of these at the same time will (and should) give you duplication errors.

**Comment by jacksoncharles** [comment]
Thanks @filipesilva. I was hoping for a more idiot friendly answer aka: how do I swap to use @types? :-)

**Comment by filipesilva** [comment]
Assuming you're using `typings` this is what you should do:
- delete `typings` folder (where all the installed typings are)
- delete `typings.json`
- in `package.json` delete `"postinstall": "typings install",` and `"typings": "typings",`
- do `npm install @types/{core-js,jasmine,node,protractor} --save-dev`
- do `npm install typescript@latest --save-dev`
- configure your editor to use the local Typescript 2.0 (for VSCode follow https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions)

Those should be all steps. https://github.com/angular/quickstart/pull/157 should update the quickstart to `@types/` sometime in the next months.

**Comment by jacksoncharles** [comment]
thanks @filipesilva, greatly appreciated.

**Comment by wardbell** [comment]
We moved to `@types`.
