### ISSUE TITLE
typings directory not created, even after npm run typings --install 

### ISSUE THREAD

**Issue by mpstaton** [angular/quickstart#224]
The "typings" directory wasn't created.  Following instructions, I ran:
 $ npm run typings --install

> angular2-quickstart@1.0.0 typings /Users/mpstaton/code/angtype
> typings

Usage: typings <command>

Commands:
    bundle, i, in, info, init, install, la, list, ll, ls, open, prune, r,
    remove, rm, search, un, uninstall, view

typings <command> -h   Get help for <command>
typings <command> -V   Enable verbose logging

typings --version      Print the CLI version

typings@1.3.3 /Users/mpstaton/code/angtype/node_modules/typings

Here's the directory structure, excluding node_modules because there are too many files.  

.
├── CHANGELOG.md
├── Dockerfile
├── LICENSE
├── README.md
├── app
│   ├── app.component.js
│   ├── app.component.js.map
│   ├── app.component.spec.js
│   ├── app.component.spec.js.map
│   ├── app.component.spec.ts
│   ├── app.component.ts
│   ├── app.module.js
│   ├── app.module.js.map
│   ├── app.module.ts
│   ├── main.js
│   ├── main.js.map
│   └── main.ts
├── e2e
│   ├── app.e2e-spec.js
│   ├── app.e2e-spec.js.map
│   └── app.e2e-spec.ts
├── favicon.ico
├── index.html
├── karma-test-shim.js
├── karma.conf.js
├── npm-debug.log
├── package.json
├── protractor.config.js
├── styles.css
├── systemjs.config.js
├── tsconfig.json
├── tslint.json
├── typings.json
└── wallaby.js

**Comment by Foxandxss** [comment]
Check again the instruction and the README :P

**Comment by mpstaton** [comment]
Actually just futzed around with sudo and the spacing in the syntax, so it worked this time.  Sorry to bug.
