### ISSUE TITLE
Testing does not work

### ISSUE THREAD

**Issue by DenisVuyka** [angular/quickstart#225]
`npm test` script crashes, might be related to the missing `systemjs.config.extras.js` file.

**Comment by Foxandxss** [comment]
I need more info.

That file is optional and doesn't make any crash.

**Comment by DenisVuyka** [comment]
Main config uses mapping to path that does not exist without that 'extras.js':
```'@angular/core/testing': 'npm:@angular/core/bundles/core-testing.umd.js',```
Where does it take 'npm:' prefix in this case?

**Comment by Foxandxss** [comment]
What is the error.
