### ISSUE TITLE
typings install error happen when run npm install, how to fix this issue?

### ISSUE THREAD

**Issue by abbymrs** [angular/quickstart#227]
C:\Users\abby\Desktop\Angular2\newNg2>npm run typings -- install

> angular-quickstart@1.0.0 typings C:\Users\lwx344455\Desktop\Angular2\newNg2
> typings "install"

typings ERR! message https://api.typings.org/entries/dt/core-js/tags/0.0.0%2B201
60725163759 responded with 500, expected it to equal 200

typings ERR! cwd C:\Users\lwx344455\Desktop\Angular2\newNg2
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "D:\\tools\\nodejs\\node.exe" "C:\\Users\\lwx344455\\Deskto
p\\Angular2\\newNg2\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v6.6.0
typings ERR! typings -v 1.4.0
typings ERR! code EINVALIDSTATUS

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\tools\\nodejs\\node.exe" "D:\\tools\\nodejs\\node_modules\\np
m\\bin\\npm-cli.js" "run" "typings" "--" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 typings: `typings "install"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 typings script 'typings "install
"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart pa
ckage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings "install"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\lwx344455\Desktop\Angular2\newNg2\npm-debug.log

**Comment by kcferguson1** [comment]
how did you solve?

**Comment by abbymrs** [comment]
@kcferguson1 yes, by adding "registryURL": "http://api.typings.org/" to my .typingsrc file
