### ISSUE TITLE
[ts] Cannot find module './app/app.component'.

### ISSUE THREAD

**Issue by Capoutcha** [angular/quickstart#229]
in app.modules.ts i get the error in 
import { AppComponent} from './app/app.component';
[ts] Cannot find module './app/app.component'.

**Comment by Foxandxss** [comment]
It is in the same folder, not an app folder

**Comment by Capoutcha** [comment]
Yes both app.modules.ts and  app.component.ts are in the same app folder which is in the root
![2016-09-26_10-20-45](https://cloud.githubusercontent.com/assets/9768420/18829189/164df9f4-83d3-11e6-8d07-86bae4107277.png)
