### ISSUE TITLE
~_test-output/tests.html is not being produced?

### ISSUE THREAD

**Issue by Ncage1974** [angular/quickstart#232]
Just cloned the source today and tried to run the tests; "npm test" and i'm not getting the ~_test-output/tests.html. Initially i was using Ubuntu 16.04. I tried it in Windows 10 also and the same thing. I also tried to run the e2e tests and i do get a "protractor-results.txt" file

**Comment by wardbell** [comment]
Ah. Sorry. We had to drop support for the `HTML-Reporter` which doesn't seem to work any more. I was disappointed. 

I just now updated the README to remove mention of it.
