### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Devansh3790** [angular/quickstart#236]
I have started an angular2 project for learning [AoT()](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html). I have followed each steps as mentioning into the documentation. At the end when i run project through `npm run lite` it's showing me this error on browser console. 

![screenshot from 2016-10-02 00 33 51](https://cloud.githubusercontent.com/assets/12626121/19016467/334ae0da-8838-11e6-881b-ef7597dc3f8f.png)
![screenshot from 2016-10-02 00 34 46](https://cloud.githubusercontent.com/assets/12626121/19016468/334cd520-8838-11e6-98f5-4899bddd5455.png)

**Comment by wardbell** [comment]
I'm sorry but your issue isn't a QuickStart repo issue; it belongs on GH angular.io. That's why I'm closing.
