### ISSUE TITLE
npm start changes MacBook's hostname

### ISSUE THREAD

**Issue by timxzz** [angular/quickstart#237]
Hello,

I am using OS X EI Capitan v10.11.6
node -v: v6.3.1
npm -v: 3.10.3

Every time after I run `npm start`, my hostname in terminal will become `pc-128-210`,
and the full hostname will become `pc-128-210.customer.lon.castle.lan`. 

After I manually change the hostname by `sudo hostname -s [hostname]`, it will happen again if I run `npm start`. It's really annoying.

Not sure what causes the problem, maybe it's the problem of npm

Tim

**Comment by wardbell** [comment]
No one else has reported this (yet) and we don't have resources to pursue it. Maybe you can do some digging for us ... and the community.

**Comment by timxzz** [comment]
OK, I will have a deep look

**Comment by timxzz** [comment]
It turns out to be the problem related to DHCP of the wifi I used. Not caused by this project.
