### ISSUE TITLE
Doesn't detect my specs

### ISSUE THREAD

**Issue by divyanthj** [angular/quickstart#238]
I followed the angular testing quickstart guide, which led me to this repository. When I run npm test, it doesn't seem to recognize any of the specs inside my app/test/ folder

I get this error on the console

[1] Chrome 53.0.2785 (Windows 7 0.0.0): Executed 0 of 0 SUCCESS (0 secs / 0 secs
    Chrome 53.0.2785 (Windows 7 0.0.0): Executed 0 of 0 ERROR (0.015 secs / 0 se
cs)

**Comment by wardbell** [comment]
You'll have to give us a repro.

I just created `app/test/some.spec.ts` as
```
it('some test', () => {
 expect(true).toBe(true);
});
```
... and ran `npm test`. Worked fine.

BTW, we recommend putting specs next to the thing that they test. That means we generally don't need a separate `test` folder. When we do, it's usually for some deep integration test that crosscuts so many files that the spec doesn't seem to belong to any of them.

I'll leave this open for a short while to give you a chance to comment or provide more of a repro

**Comment by divyanthj** [comment]
Ok, so in the karma.conf.js, I rewrote the path variables to this

```
var appBase    = 'www/app/';       // transpiled app JS and map files
  var appSrcBase = 'src/app/';       // app source TS files
  var appAssets  = '/base/app/'; // component assets fetched by Angular's compiler

  var testBase    = 'www/app/';       // transpiled test JS and map files
  var testSrcBase = 'src/app/';       // test source TS files
```

Then I copied the `src/app/test/app.spec.ts` file to my `src/app/scripts` folder, which also contains `app.ts` file. Everything gets guilt into a `www/` folder. Is there anything else I need to reconfigure?

The contents of of my `app.spec.ts` is

```
/// <reference path="../../../typings/browser/index.d.ts" />

describe('1st tests', () => {
  it('true is true', () => expect(true).toBe(true));
});
```

I'm still getting the same error. What could I be missing?

**Comment by wardbell** [comment]
Your reply shows that you have taken you file structure in a direction that is completely different than the one proposed by the QuickStart.

That means it is out of scope for the quickstart.  I'm sorry but we don't have the time and resources to pursue this. Our narrow mission is to make the QS work _as written_.

Perhaps you'll find the help you need on StackOverflow.
