### ISSUE TITLE
es6-shim.js:4941 Uncaught SyntaxError: for-in loop variable declaration may not have an initializer

### ISSUE THREAD

**Issue by Justin-lu** [angular/quickstart#24]
When I run this quickstart, I get this error

```js
es6-shim.js:4941 Uncaught SyntaxError: for-in loop variable declaration may not have an initializer
```

```shell
node -v
=> v0.12.7

npm -v
=> 2.11.3
```

**Comment by sjaanus** [comment]
same problem for me. same versions.

**Comment by bazmatic** [comment]
Same error. Something must have changed recently?

**Comment by sethdarr** [comment]
Ditto.

➜  todoApp git:(master) ✗ node -v
v0.10.26
➜  todoApp git:(master) ✗ npm -v
1.4.3

**Comment by hemerfc** [comment]
Same error. Anyone found a solution for this error?

**Comment by sanqianpiao** [comment]
I've met the same problem. Replace with the newest version https://github.com/paulmillr/es6-shim/blob/master/es6-shim.js will be fine.

**Comment by wardbell** [comment]
Closed. Obsolete.
