### ISSUE TITLE
Extra forward slash when referencing UMD files

### ISSUE THREAD

**Issue by IgorMinar** [angular/quickstart#242]
reposting from: https://github.com/angular/angular/issues/9871

This is easily reproducible with the Angular 2 quickstart project. Just run npm start and check the network tab in Google Chrome.

Removing the forward slash before "bundles" in system.config.js seems to fix the issue:
```
packages['@angular/'+pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
packages['@angular/'+pkgName] = { main: 'bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
```

What is the expected behavior?

What is the motivation / use case for changing the behavior?

Simple deployment to Firebase.

Please tell us about your environment:

Angular version: 2.0.0-rc.4

Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
Chrome 51

Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
TypeScript, ES5

**Comment by filipesilva** [comment]
@IgorMinar that issue was present when this repo was in `2.0.0-rc.4`, but on `2.0.0-rc.6` we switched to a different `system.config.js` format: https://github.com/angular/quickstart/blob/master/systemjs.config.js#L17-L25

**Comment by IgorMinar** [comment]
thanks!
