### ISSUE TITLE
Quickstart won´t work

### ISSUE THREAD

**Issue by darklinki** [angular/quickstart#245]
zone.js:1274 GET http://localhost:3000/app/main.js 404 (Not Found)scheduleTask @ zone.js:1274ZoneDelegate.scheduleTask @ zone.js:216Zone.scheduleMacroTask @ zone.js:153(anonymous function) @ zone.js:1304send @ VM1636:3fetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781ZoneAwarePromise @ zone.js:478(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407ZoneDelegate.invoke @ zone.js:203Zone.run @ zone.js:96(anonymous function) @ zone.js:462ZoneDelegate.invokeTask @ zone.js:236Zone.runTask @ zone.js:136drainMicroTaskQueue @ zone.js:368
(index):16 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/app/main.js(…)

If followed the guide to run the quickstart for ts. Nothing works, tried like 100 things people on stackoverflow wrote. But found no solution. So I reverted to the original. There is now no modification just the basic code.

**Comment by filipesilva** [comment]
Your problem is zone.js related. Are you using `0.6.25`?

**Comment by darklinki** [comment]
"_args": [
    [
      "zone.js@^0.6.25",


This is what I found in the package.json from the node module. I hope this is what you meant.

**Comment by darklinki** [comment]
Tried it on a different pc, complettly clean instalation of node and followed the quickstart guide step by step. Still the same error. Cant believe it only affects me :question:

**Comment by filipesilva** [comment]
@darklinki can you put up your code online in github? That way I could clone it locally and test.

I can tell you with 100% certainty that the code currently on this repo works, and that the code that is being shown in the Quickstart chapter also works. We test them several times a day. 

But there might be some broken instructions somewhere in the prose that lead to your scenario, so if you can help me reproduce I can fix it.

**Comment by darklinki** [comment]
You´re right, I done it a third time. Somehow it worked now. Ty and sry.
