### ISSUE TITLE
version of angular-in-memory-web-api in package.json

### ISSUE THREAD

**Issue by Longfld** [angular/quickstart#247]
This does not work:
 "angular-in-memory-web-api": "~0.1.5",

I guess you mean:
 "angular-in-memory-web-api": "~0.0.15",??

Same issue in your github source code

**Comment by darklinki** [comment]
0.0.15 does not work

**Comment by Longfld** [comment]
~0.015 works for me, system couldn't find ~0.1.5

**Comment by filipesilva** [comment]
I just checked and it definitely exists. Maybe you're using a private registry or a proxy that does not yet have the latest versions?

```
$ npm info angular-in-memory-web-api versions

[ '0.1.0',
  '0.1.1',
  '0.1.2',
  '0.1.3',
  '0.1.4',
  '0.1.5',
  '0.1.6',
  '0.1.7' ]
```

**Comment by Longfld** [comment]
I agree it is not this project's issue, but this project is about quickstart for beginner, they won't find where is wrong and simply conclude angular2 is shit

`
C:\Projects\ng2\final\angular2-quickstart>npm install
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\nshi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "inst
all"
npm ERR! node v6.5.0
npm ERR! npm  v3.8.1

npm ERR! No compatible version found: angular2-in-memory-web-api@~0.1.5
npm ERR! Valid install targets:
npm ERR! 0.0.21, 0.0.20, 0.0.19, 0.0.18, 0.0.17, 0.0.16, 0.0.15, 0.0.14, 0.0.13, 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5,
0.0.4, 0.0.3, 0.0.2, 0.0.1
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\ng2\final\angular2-quickstart\npm-debug.log

C:\Projects\ng2\final\angular2-quickstart>npm info angular-in-memory-web-api versions

[ '0.1.0',
  '0.1.1',
  '0.1.2',
  '0.1.3',
  '0.1.4',
  '0.1.5',
  '0.1.6',
  '0.1.7' ]
`

**Comment by Foxandxss** [comment]
You are trying to install angular**2**-in-memory-web-api version 0.1.5+ and that **does not** exist. You need to get rid of that "2" on the name.

**Comment by filipesilva** [comment]
I think @Longfld is actually taking about a project called `angular2-quickstart` that uses `angular2-in-memory-web-api`.

@Longfld where is this project? In the quickstart repo, we use the right version https://github.com/angular/quickstart/blob/master/package.json#L40

**Comment by filipesilva** [comment]
Are you talking about this project? https://github.com/valor-software/angular2-quickstart

Angular does not maintain that. It's created by someone else, perhaps you should open an issue there for them to update their repo.
