### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by dir000** [angular/quickstart#248]
I followed the guide https://angular.io/docs/ts/latest/quickstart.html and got this error

```
npm install
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> angular-quickstart@1.0.0 postinstall C:\Users\Alex\WebstormProjects\angular-quickstart
> typings install


npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angular-quickstart@1.0.0 No description
npm WARN angular-quickstart@1.0.0 No repository field.
npm WARN angular-quickstart@1.0.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! file C:\Windows\system32\cmd.exe;C:\Users\Alex\AppData\Local\.meteor\
npm ERR! path C:\Windows\system32\cmd.exe;C:\Users\Alex\AppData\Local\.meteor\
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd.exe;C:\Users\Alex\AppData\Local\.meteor\
npm ERR! angular-quickstart@1.0.0 postinstall: `typings install`
npm ERR! spawn C:\Windows\system32\cmd.exe;C:\Users\Alex\AppData\Local\.meteor\ ENOENT
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angular-quickstart@1.0.0 No description
npm WARN angular-quickstart@1.0.0 No repository field.
npm WARN angular-quickstart@1.0.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! angular-quickstart@1.0.0 postinstall: `typings install`
npm ERR! Exit status -4058
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Alex\WebstormProjects\angular-quickstart\npm-debug.log
```

**Comment by mart-dominguez** [comment]
Hi I've solved ( in ubuntu 14 but I think is the same) by addding in the root project .typingsrc with 3 entries (i am behind a corporative proxy)

 proxy=http://xx.xx.xx.xx:8080  
 rejectUnauthorized=false
 registryURL=http://api.typings.org

**Comment by 0101coding** [comment]
I am having an issue similar to the above but with the error

> $ npm install
npm WARN package.json angular-quickstart@1.0.0 No description
npm WARN package.json angular-quickstart@1.0.0 No repository field.
npm WARN package.json angular-quickstart@1.0.0 No README data
npm WARN package.json angular-quickstart@1.0.0 No license field.
npm WARN optional dep failed, continuing fsevents@1.0.14
npm ERR! not a package C:\Users\user\AppData\Roaming\npm-cache\debug\2.2.0\package.tgz
npm ERR! not a package C:\Users\user\AppData\Roaming\npm-cache\debug\2.2.0\package.tgz
npm ERR! not a package C:\Users\user\AppData\Roaming\npm-cache\debug\2.2.0\package.tgz
npm ERR! not a package C:\Users\user\AppData\Roaming\npm-cache\debug\2.2.0\package.tgz
npm ERR! not a package C:\Users\user\AppData\Roaming\npm-cache\debug\2.2.0\package.tgz
npm ERR! not a package C:\Users\user\AppData\Roaming\npm-cache\glob\7.1.1\package.tgz
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm ERR! not a package C:\Users\user\AppData\Roaming\npm-cache\engine.io-client\1.7.0\package.tgz
npm ERR! not a package C:\Users\user\AppData\Roaming\npm-cache\glob\7.1.1\package.tgz
npm ERR! not a package C:\Users\user\AppData\Roaming\npm-cache\engine.io-parser\1.3.0\package.tgz
npm ERR! not a package C:\Users\user\AppData\Roaming\npm-cache\debug\2.2.0\package.tgz
npm ERR! not a package C:\Users\user\AppData\Roaming\npm-cache\async\2.1.1\package.tgz
npm ERR! not a package C:\Users\user\AppData\Roaming\npm-cache\debug\2.2.0\package.tgz
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! path D:\Dev Space\angular\ang2\demo\node_modules\typings\node_modules\typings-core\node_modules\debug\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'D:\Dev Space\angular\ang2\demo\node_modules\typings\node_modules\typings-core\node_modules\debug\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Please include the following file with any support request:
npm ERR!     D:\Dev Space\angular\ang2\demo\npm-debug.log

**Comment by filipesilva** [comment]
@dir000 your problem seems related to the `typings` tool, probably a proxy issue like @mart-dominguez mentioned.

@0101coding you seem to have a broken cache. Try doing the following:
```
npm cache clean
npm install
```
