### ISSUE TITLE
Uncaught ReferenceError: System is not defined

### ISSUE THREAD

**Issue by vriestimo** [angular/quickstart#25]
I'm getting above error when trying to view the demo (http://htmlxprs.github.io/angular2-todo/).
Have tried multiple browsers. Also the latest version of Chrome.

Does anybody know what might be the problem here? It seems to me that systemjs is simply not included or loaded correctly. JS execution fails at the following line in index.html:

System.paths = {
          'angular2/*':'/angular2/*.js',
          'rtts_assert/*': '/rtts_assert/*.js',
          'services/*' : '/services/*.js',
          'todoApp': 'TodoApp.es6'
      };

Kind regards,
Timo de Vries

**Comment by shez1983** [comment]
do gulp build:shim so that it builds a dist/es6-shim.js that the app requires.. without it I got the same error as you.. 

Also make sure that you have:

1. all the gulp dependencies installed (npm install)
2. then open the gulpfile.js and manually install the four dependencies listed i.e require(...)

in order to run gulp

**Comment by GunsAkimbo** [comment]
I got the same error if I hosted the app in IIS as an IIS application, which means the leading slashes points to the root of the server, not the application. To fix this, I removed the leading slashes:
System.paths = {
          'angular2/*':'angular2/*.js',
          'rtts_assert/*': 'rtts_assert/*.js',
          'services/*' : 'services/*.js',
          'todoApp': 'TodoApp.es6'
      };

**Comment by Hrshvrdhn** [comment]
I am getting the similar error while trying to run a simple code where I am displaying a variable in html being changed in a javascript file:
```javascript
var MainController = function($scope){
	$scope.message = "harsh";
};
```

and html as:
```javascript
<!DOCTYPE html>
<html ng-app>

  <head>
    <script data-require="angular.js@*" data-semver="2.0.0-alpha.45" src="https://code.angularjs.org/2.0.0-alpha.45/angular2.js"></script>
	<script src="script.js"></script>
  </head>

  <body ng-controller="MainController">
    <h1>{{message}}</h1>
  </body>

</html>
```
The error on chrome console is as:
```javascript
Uncaught ReferenceError: System is not defined(anonymous function) @ angular2.js:3098
```
which points to:

```javascript
System.register("angular2/src/core/facade/lang", [], true, function(require, exports, module) {
```

I don't understand the problem. Is it related to the angular2.js which is Angular lib file?

**Comment by pmcgeebcit** [comment]
I had this error with Chrome but was able to run it in FireFox in Windows and on a Mac. Since the Quickstart project is dealing with libraries that are in their infancy I am okay with that - it is possible that FireFox is more lax or the project may stop working in a future version of FireFox. The project still shows a decent reflection of Angular2 which has not officially been released yet.

**Comment by Queatz** [comment]
Can't seem to get around this for my Internet Explorer 11 users.

**Comment by maxhor** [comment]
I ran into the same problem. Adding

 `<script src="https://code.angularjs.org/tools/system.js"></script>`  solved it.

Still, in the html page, I already had the following reference:  

 `<script src="node_modules/systemjs/dist/system.js"></script>`

both references point to the same version of system.js, Both files start with 

```
 /*
 * SystemJS v0.19.6
 */
```

A big question for me is why `<script src="node_modules/systemjs/dist/system.js"></script>` does not work.

**Comment by wardbell** [comment]
Closed. Obsolete.

**Comment by Vexez** [comment]
the problem still exist until the quickstart guide is fixed to beta10
using 
`<script src="https://code.angularjs.org/tools/system.js"></script>`
instead of 
`<script src="node_modules/systemjs/dist/system.src.js"></script>`
fix it for now

**Comment by jamalsoueidan** [comment]
I had the same problem even though I dont know where SystemJS is coming from?

I specify module: commonjs and not systemjs:


	"compilerOptions": {
		"target": "ES5",
		"module": "commonjs",

**Comment by dachibro** [comment]
@jamalsoueidan +1

**Comment by simo14** [comment]
@wardbell @Vexez I am using beta 12 and systemjs 0.19.25 and still run into the same problem. I will use the temporal fix with code angular as for now. I do not think it is fixed in Angular Quickstart yet even though it uses betq

**Comment by jdforsythe** [comment]
I was having the same problem. If you change to `node_modules/systemjs/dist/system.js` instead of `system.src.js` it works. It appears that file is the same as the one on the Angular server.

**Comment by filipesilva** [comment]
@jdforsythe I just checked and the quickstart guide on www.angular.io seems to work. 

`node_modules/systemjs/dist/system.js` exists alongside `node_modules/systemjs/dist/system.src.js`.

**Comment by jdforsythe** [comment]
@filipesilva Yes, the two files exist in the node module. The problem is that using the `system.src.js` (which appears to be an un-minified version, but must have some kind of difference) causes the above mentioned errors in Chrome. I have not tested on any other browser. But the minified version `system.js` which is the same as the one on the Angular server does not throw the error.

**Comment by filipesilva** [comment]
@jdforsythe I can't seem to reproduce this error. The steps I took were these:

```
git clone https://github.com/angular/quickstart.git
cd quickstart
npm install
npm start
```

In chrome, this is all I see in the console:
![image](https://cloud.githubusercontent.com/assets/4172079/14888219/16a75b46-0d51-11e6-97b3-d250d7a18b9f.png)

**Comment by chinmay43** [comment]
@dachibro I am using ng2-bootstrap. I used npm to install ng2-bootstrap and typings install ~dt moment --save --global for moment. Any idea why ?

**Comment by Piusha** [comment]
Same issue I am experiencing. I just tried with installing node_modules again still same error appearing.
Uncaught ReferenceError: System is not defined 
I am using angular 2.1.*
