### ISSUE TITLE
Cant launch Angular2 Quickstart app 

### ISSUE THREAD

**Issue by kiiru501** [angular/quickstart#251]
Hi, 
I'm a newbie at angular2. I have tried to launch the Angular 2 Quickstart application but i still cant get it to work. 

Here is my code;

![capture](https://cloud.githubusercontent.com/assets/4168690/19373787/7aadde32-91cf-11e6-917a-cdeab95ce5b6.PNG)

I have seen various solutions here such as changing  **"start": "tsc && concurrently \"tsc -w\" \"lite-server\" "**  to  **"start": "concurrently \"tsc -w\" \"lite-server\" "**

but it doesn't work for me . help needed

**Comment by filipesilva** [comment]
Heya, that's an odd error. ENOENT means "Error No Entry", which usually is related to missing files/dirs.

Let's start by making sure your install is good. Can you try deleting `node_modules` and running `npm install` again?

**Comment by kiiru501** [comment]
I'm still getting the same error.
I have created another folder and followed the steps on the Angular Quickstart page.
When i run the **npm install** it keeps giving the error typings install failed. When i run **npm run typings install** ,it fails again. Although i found  **npm install typings -g** works.  **npm start**  still failes but i have been able to launch the **localhost:3000** through running the command **lite-server**.
please help

**Comment by filipesilva** [comment]
Can you show me the errors you are getting with `npm run typings`?

**Comment by kiiru501** [comment]
![capture2](https://cloud.githubusercontent.com/assets/4168690/19412298/b01a9360-931b-11e6-946d-2842a20efa0f.PNG)

**Comment by kiiru501** [comment]
![capture3](https://cloud.githubusercontent.com/assets/4168690/19412322/04d9c11e-931c-11e6-967c-5f5086433799.PNG)

**Comment by filipesilva** [comment]
I have idea why the command is failing on your system.. I find it weird that it says that the file and path is `D:\Windows\system32`, but can't say exactly what's broken. 

@Foxandxss, @wardbell any idea?

**Comment by kiiru501** [comment]
I Have two OS partitions on my PC. I am running win 7 on this one. The system path and user path both point to D:/windows/system32 . I dont think that should be a problem

**Comment by david9991** [comment]
I confirm same problem here on Ubuntu 16.04.

**Comment by kiiru501** [comment]
I have uninstalled everything node-related and reinstalled them back. but the error is still there .please assist

**Comment by filipesilva** [comment]
My best bet is that there's is SOMETHING that's stopping NPM from finding your local modules. 

Can you see if this command works successfully from your project dir?
```
node_modules\.bin\typings install
```

**Comment by jannakha** [comment]
set your shell env variables correctly
https://github.com/kimmobrunfeldt/spawn-default-shell

$SHELL
$COMSPEC

more comments here - https://github.com/kimmobrunfeldt/concurrently/issues/60

**Comment by kiiru501** [comment]
@filipesilva the command pops up  command shell which installs **typings** then disappears after two seconds. the error is still there once i run **npm start**

**Comment by filipesilva** [comment]
@kiiru501 can you show me the long when you ran `node_modules\.bin\typings install`?

**Comment by filipesilva** [comment]
@jannakha added PR to bump concurrently, maybe that helps.

**Comment by filipesilva** [comment]
@kiiru501 locally, try to do `npm install concurrently@3.1.0` and see if `npm start` works again.

**Comment by kiiru501** [comment]
it disappears after a second .cant freeze it sorry

**Comment by kiiru501** [comment]
same error still even after **npm install concurrently@3.1.0**. 
I keep getting this line every time  run a command
![capture5](https://cloud.githubusercontent.com/assets/4168690/19565844/fc85f2a2-96f0-11e6-8a07-787249c60139.PNG)

**Comment by filipesilva** [comment]
Hm... really weird that you both get that error AND get the version right afterwards. Also weird that in that error, there are double slashes `\\` in some of the directory paths.

I think you have a broken NPM/Node install somehow, maybe something wrong in the PATH? You can try asking in https://github.com/npm/npm as well.

**Comment by wardbell** [comment]
Sorry but this really doesn't relate to QuickStart. More of a stackoverflow thing. Closing.
