### ISSUE TITLE
TS web doc missing app.module

### ISSUE THREAD

**Issue by guillemsola** [angular/quickstart#256]
I was following the web tutorial https://angular.io/docs/ts/latest/quickstart.html but the app was not booting up.

Checked with this github source code and found that the

```
  declarations: [ AppComponent ],
  bootstrap: [ AppComponent ]
```

where missing in the NgModule section  for the app.module.ts.

Not sure if there is another github project for the documentation web source.

**Comment by filipesilva** [comment]
Heya, in step 3 there are actually instructions to edit your `app.module.ts` and add those bits: https://angular.io/docs/ts/latest/quickstart.html#!#root-component

![image](https://cloud.githubusercontent.com/assets/4172079/19618571/79756c42-9846-11e6-8b4d-20919a0fdf50.png)

**Comment by guillemsola** [comment]
So true.. 

Thank you for noticing!
