### ISSUE TITLE
“http://localhost:3000/traceur 404 (Not Found)” caused by angular-in-memory-web-api module (Chrome version 54.0.2840.71 (64-bit) on Mac OS X (10.11.6))

### ISSUE THREAD

**Issue by pniang** [angular/quickstart#259]
See https://github.com/angular/in-memory-web-api/blob/master/CHANGELOG.md#0113-2016-10-20 for solution.

**Comment by wardbell** [comment]
Yes. Missed it before. Corrected by commit 541bdc5f634e1142860c56cace247234edfaf74b
