### ISSUE TITLE
build:ng2 error

### ISSUE THREAD

**Issue by chabgood** [angular/quickstart#26]
I am on yosemite, I did gulp and I get this error:

ulp
[13:37:49] Using gulpfile ~/projects/me/angular2/quickstart/gulpfile.js
[13:37:49] Starting 'default'...
[13:37:49] Starting 'clean'...
[13:37:49] Finished 'clean' after 6.01 ms
[13:37:49] Starting 'build:ng2'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/Users/chabgood/projects/me/angular2/quickstart/node_modules/angular2/es6/prod/angular2.map'
    at Error (native)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/Users/chabgood/projects/me/angular2/quickstart/node_modules/rtts_assert/es6/es5build.map'
    at Error (native)
[13:37:53] 'build:ng2' errored after 4.35 s
[13:37:53] Error in plugin 'gulp-shell'
Message:
    Command failed: /bin/sh -c sh ng2build.sh
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/Users/chabgood/projects/me/angular2/quickstart/node_modules/angular2/es6/prod/angular2.map'
    at Error (native)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/Users/chabgood/projects/me/angular2/quickstart/node_modules/rtts_assert/es6/es5build.map'
    at Error (native)

Details:
    killed: false
    code: 1
    signal: null
    cmd: /bin/sh -c sh ng2build.sh
    stdout:
    stderr: events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/Users/chabgood/projects/me/angular2/quickstart/node_modules/angular2/es6/prod/angular2.map'
    at Error (native)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/Users/chabgood/projects/me/angular2/quickstart/node_modules/rtts_assert/es6/es5build.map'
    at Error (native)

[13:37:53] 'default' errored after 4.36 s
[13:37:53] Error in plugin 'run-sequence'
Message:
    An error occured in task 'build:ng2'.

**Comment by wardbell** [comment]
Closed. Obsolete.
