### ISSUE TITLE
Multiple "Duplicate identifier 'XXX'

### ISSUE THREAD

**Issue by AngularPadawan** [angular/quickstart#261]
After a fresh clone, npm install and npm start, I get multiple "Duplicate identifier" errors. Seems to be related to using @types type definitions in protractor.

F:\>git clone https://github.com/angular/quickstart.git
Cloning into 'quickstart'...
remote: Counting objects: 1146, done.
emote: Total 1146 (delta 0), reused 0 (delta 0), pack-reused 1146
Receiving objects: 100% (1146/1146), 1.06 MiB | 1.59 MiB/s, done.
Resolving deltas: 100% (637/637), done.
Checking connectivity... done.

F:\>npm --version
3.10.3

F:\>node --version
v6.3.1

F:\>npm install

...
F:\quickstart>npm start

> angular-quickstart@1.0.0 start F:\quickstart
> tsc && concurrently "tsc -w" "lite-server"

C:/projects/quickstart/node_modules/@types/q/index.d.ts(7,21): error TS2300: Duplicate identifier 'Q'.
C:/projects/quickstart/node_modules/@types/selenium-webdriver/index.d.ts(12,11): error TS2300: Duplicate identifier 'Driver'.
C:/projects/quickstart/node_modules/@types/selenium-webdriver/index.d.ts(46,11): error TS2300: Duplicate identifier 'Options'.
C:/projects/quickstart/node_modules/@types/selenium-webdriver/index.d.ts(310,11): error TS2300: Duplicate identifier 'ServiceBuilder'.
C:/projects/quickstart/node_modules/@types/selenium-webdriver/index.d.ts(422,11): error TS2300: Duplicate identifier 'Driver'.
C:/projects/quickstart/node_modules/@types/selenium-webdriver/index.d.ts(444,11): error TS2300: Duplicate identifier 'Options'.

**Comment by Foxandxss** [comment]
A good way of moving from padawan to jedi is to provide some description in the issue.

**Comment by AngularPadawan** [comment]
;) Sorry for the missing description, I got lost when switching windows... is there now.

**Comment by AngularPadawan** [comment]
Ok, just asking helped... obviously using the alias drive letter (c:\projects -> f:) confuses tsc. Doing the npm start in the "correct" folder just works. Sorry for the unnecessary post!
