### ISSUE TITLE
add aot configuration

### ISSUE THREAD

**Issue by jasonzhang2022** [angular/quickstart#262]
AOT as is documented here(https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) will be really helpful for a production skeleton.

**Comment by ibqn** [comment]
I have created one for myself, based on the AOT tutorial: [aot-quick-start](https://github.com/ibqn/ng2-quick-start)

**Comment by wardbell** [comment]
That's great that you've done that for yourself. We have decide not to add AoT to this QS at this time.
