### ISSUE TITLE
Issue with setting system.config.js in angular-cli project

### ISSUE THREAD

**Issue by Sri276286** [angular/quickstart#263]
Hi,

Could someone help me in using systemJs for an angular-cli project.

I have normally taken angular-cli project with ng new <proj-name> and trying to add system.config.js file in this.

My project structure looks like this 

![image](https://cloud.githubusercontent.com/assets/19607054/19714086/19b58ca8-9b69-11e6-8e4f-c6f0e5dd3e0e.png)

------------------------------------
my index,html 
-------------------------------------
<html>

<head>
    <title>Angular QuickStart</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="styles.css">
    
    
    <script src="node_modules/core-js/client/shim.min.js"></script>
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    
	<script src="https://code.angularjs.org/tools/system.js"></script>
    
    <script src="systemjs.config.js"></script>
    <script>
        System.import('app').catch(function(err) {
            console.error(err);
        });
    </script>
</head>

<body>
    <my-app>Loading...</my-app>
</body>

</html>

--------------------------------
angular-cli.json 
------------------------

{
  "project": {
    "version": "1.0.0-beta.17",
    "name": "pack-first-app"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": "assets",
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "prefixInterfaces": false
  }
}

-----------------------------------------
systemjs.config.js

-----------------------------------------

/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function(global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'src',
            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            // other libraries
            'rxjs': 'npm:rxjs'
            
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.ts',
                defaultExtension: 'ts'
            },
            rxjs: {
                defaultExtension: 'ts'
            }
        }
    });
})(this);

-----------------------------------------

I am seeing the following errors in the console 

![image](https://cloud.githubusercontent.com/assets/19607054/19714185/bf6ccfe4-9b69-11e6-8f76-0852960ff80a.png)

Please help me in doing a proper setup.

Any help appreciated.

thanks

**Comment by filipesilva** [comment]
@Sri276286 Angular-CLI does'tn use SystemJS as a loader anymore, so you don't need to do any related SystemJS configuration. In fact, there's no need to edit anything in `index.html` either, since it's managed by the build system as well.

I'm going to have to close this issue however, as your setup is not related to the quickstart per se. If you are having trouble with your CLI app I'll be happy to answer your issue in the CLI repo: https://github.com/angular/angular-cli

**Comment by Sri276286** [comment]
If I want to have control on build and bundling , how can I use systemjs with angular-cli project.

I heard with webpack, we cannot control on what we want to build or bundle. Please help me to proceed further.

**Comment by filipesilva** [comment]
@Sri276286 you cannot control the build step while using Angular-CLI at the moment, but in the future you will be able to via the addon system. Again, please open CLI related questions on the CLI tracker, I won't answer any more here because it's not related to the quickstart.

**Comment by Sumei1009** [comment]
@filipesilva May I ask where to set the paths and map as in System config if I want to use an external library?

**Comment by vasuneet** [comment]
I have the same question. If we need to add the reference of external library which we installed using npm install . How can we refer this in our project.

**Comment by gouravKhatter** [comment]
instead of using ember server in angular-cli i want to use Angular 4 cli project with Node server , how can i change inex.html??

**Comment by softboy99** [comment]
Hi,
i have the same problem with Angular 4 cli project with external library which we installed using npm install
