### ISSUE TITLE
Add classList polyfill in order to make the starter works on IE9

### ISSUE THREAD

**Issue by thomasmerieux** [angular/quickstart#269]
Hi guys,

I'm currently working on an app that must work on IE9 and I found out that your quickstart doesn't work on IE9 because it's missing the classList polyfill. 

For instance, when you're trying to use ngModel or the like, it throws an error on IE9 (see https://github.com/angular/angular/issues/12568).

I think it would be a great idea to add it so that the futur users doesn't get stuck because of that.

Thomas

**Comment by filipesilva** [comment]
Heya @thomasmerieux, we don't add all polyfills but we have a documentation page listing the necessary one for each browser: https://angular.io/docs/ts/latest/guide/browser-support.html
