### ISSUE TITLE
TypeError at karma-test-shim.js:30

### ISSUE THREAD

**Issue by fadc80** [angular/quickstart#274]
I am trying to figure out  how to run the quickstart tests with phantomjs. 

I thought these steps were enough:

**1. Install phantomjs and phantomjs launcher**

`$ npm install --save-dev phantomjs`
`$ npm install --save-dev karma-phantomjs-launcher`

**2. Change karma.conf.js**

// First change
require('karma-chrome-launcher') => require('karma-phantomjs-launcher')

// Second change
browsers: ['Chrome'] => browsers: ['PhantomJS']

**3. Install quickstart app**

`$ npm install`

**4. Run tests**

`$ npm run test-once`

The following error is reported:

> ...
> PhantomJS 2.1.1 (Linux 0.0.0) ERROR
>   TypeError: undefined is not a function (evaluating 'System.config')
>   at karma-test-shim.js:30
> ...

What am I missing or doing wrong?

Thanks.

**Comment by fadc80** [comment]
I have solved this issue appending system-polyfills.js to karma.conf.js:

```
files: [
  // System.js for module loading
  'node_modules/systemjs/dist/system.src.js',
  'node_modules/systemjs/dist/system-polyfills.js',
```

Why it is not needed for Chrome?

SO Refererence: [How to configure Angular 2 Quickstart to run phantomjs?](http://stackoverflow.com/questions/40470806/how-to-configure-angular2-quickstart-to-run-phantomjs)

**Comment by wardbell** [comment]
Thanks. This is is great information but it belongs as an update to the angular.io testing chapter, not here. The QuickStart repo does not support ... and will not support ... phantom.js out of the box.

Please re-post as a PR or at least an issue at [angular.io](https://github.com/angular/angular.io)
