### ISSUE TITLE
"systemjs.config.js" not loaded (HTTP-GET-ERROR 404)

### ISSUE THREAD

**Issue by nimo23** [angular/quickstart#275]
The actual version of angular-quickstart has this in index.html:

`<script src="systemjs.config.js"></script>`

Starting the server (npm start) and looking in dev tools shows that this file cannot be loaded (because of its filename):
![1](https://cloud.githubusercontent.com/assets/3045549/20118940/de528924-a606-11e6-91ee-a304188b33c4.png)

**However, it works, if I change the filename:** 

If I rename the file to "config.js" and reference it, 
then script can be loaded and angular quickstart works:

`<script src="config.js"></script>`

**The strange thing is that renaming the file to something like the following will result in the same problem (GET-Error 404):**

- "systemjs-config.js"
- "systemjs_config.js"
- "systemjsconfig.js"

Maybe because of the word "systemjs" or "*js.js" ?

So, I guess, renaming the file to "config.js" or something else, solves the problem.

**Comment by Foxandxss** [comment]
First time ever I see that. Are you running it with our provided local server?

**Comment by nimo23** [comment]
> Are you running it with our provided local server?

I am using **lite-server** 
coming from **angular-quickstarts "package.json"** 
and start the server with **npm start**:

```
{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "lite": "lite-server",
    "tsc": "tsc",
    "tsc:w": "tsc -w"
  },
..
```

**Comment by wardbell** [comment]
What you show does not look like the package.json from this repo. You can clearly see that there is a `systemjs.config.js` here and there is not a `config.js` here.

I'm attributing this issue to an error on your part and closing it. If you can demonstrate otherwise, I'm happy to reopen.

**Comment by nimo23** [comment]
>> What you show does not look like the package.json from this repo. You can clearly see that this repo has a What you show does not look like the package.json from this repo. You can clearly see that this repo has a systemjs.config.js and there is no config.js file. and there is no config.js file.

**I have to rename "systemjs.config.js" to "config.js" to make it work.** I mentioned the reason above. It does NOT work when I use the name "systemjs.config.js". I included the original quickstart before renaming to "config.js".

[angular-quickstart.zip](https://github.com/angular/quickstart/files/600615/angular-quickstart.zip)

**Comment by nimo23** [comment]
I tried it again to verify the case:

1. I am using "angular-quickstart.zip" as it is.
2. make "npm install"
3. make "npm start"

Server started:



![screenshot at nov 18 19-31-28](https://cloud.githubusercontent.com/assets/3045549/20441688/da3c0ace-adc5-11e6-8157-c761418c7ff8.png)

I opend Safari (it does not matter, google chrome or firefox shows the same error) and get the 404-Error for "systemjs.config.js":

![screenshot at nov 18 19-29-00](https://cloud.githubusercontent.com/assets/3045549/20441702/ebc4d80c-adc5-11e6-9801-8df3a6941d9e.png)

**Comment by nimo23** [comment]
I have cleared all my caches and tried again. The same error with 'systemjs.config.js', it's only working when renaming this file. Strange.

**Comment by wardbell** [comment]
There is something exotic in your environment. We cannot repro. I'm sorry but we have to keep this closed until there is a repro.
