### ISSUE TITLE
how do use the  command  npm start in background ?

### ISSUE THREAD

**Issue by percinor** [angular/quickstart#276]
i m npm install forever , i use command  forever start -c  "npm start"  /var/quickstart  in  ubuntu os  ,but couldn't work , how do i could run it in background.thanks

**Comment by Foxandxss** [comment]
Sorry I don't get the problem / idea.

**Comment by wardbell** [comment]
This QS repo does not support the [forever](https://www.npmjs.com/package/forever) npm package and it is not our intention to do so. Best to consult that documentation or stackoverflow.
