### ISSUE TITLE
Issue with quickstart

### ISSUE THREAD

**Issue by robbe-aberon** [angular/quickstart#278]
I had some problems with running the "quickstart tutorial". When I wanted to run the application it gave an error that main.js couldn't be found. When I changed the name to main.ts it could be found but gave another error: traceur couldn't be found. After some searching I fixed it by updating my 'tsconfig.json' and 'systemjs.config.js' with the ones that are given on github.

So maybe you can update the quickstart tutorial on the website with these files so it works out of the box. It's pretty frustrating when a tutorial doesn't run, so I hope I can help some people with their problems.

Kind regards and thanks for angular2

**Comment by wardbell** [comment]
QuickStart is being completely overhauled. This shouldn't be a problem again.
