### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by frankmuir** [angular/quickstart#282]
When I follow the instructions for this exactly and run NPM start, I get "Cannot GET /" in the browser.

In the console, one of the last lines will be "404 GET /index.html"

I have just downloaded this project, haven't changed any files.

**Comment by orieken** [comment]
I just cloned, npm install, and npm start and it worked just fine I'd try to pull latest and try again. is the console throwing any errors?

**Comment by wardbell** [comment]
Looks like this is not an issue for you.
