### ISSUE TITLE
Hypothetically, how would I deploy this?

### ISSUE THREAD

**Issue by gwooding** [angular/quickstart#286]
Hi,

I've spent months making a reasonably cool app that I'd like to share with the world, that began as this quickstart app.  It uses systemjs and starts up the lite-server when you run npm-start still.  

In fact, here's the code: https://github.com/gwooding/PayoffCalculator

What changes would one have to make to deploy the quickstart application using, say, Heroku?  I've had a lot of trouble using the Angular-CLI so have a strong bias against using it, but will use it if that's the only way.

**Comment by Foxandxss** [comment]
You would need to use https://github.com/systemjs/builder

**Comment by gwooding** [comment]
I'm a bit of a beginner at this.  If anyone knows of a step-by-step guide or would care to make one I think it would be very helpful for many Angular 2 beginners.

**Comment by wardbell** [comment]
It's a wonderful question but unfortunately this is the wrong place to ask it as we only address issues that concern the use of this QuickStart seed as described in the documentation. Please post your question to stackoverflow.
