### ISSUE TITLE
Unable to start the lite-server

### ISSUE THREAD

**Issue by vignesh-subash** [angular/quickstart#291]
when trying to start the lite-server, i am getting the following error. 
> tsc && concurrently "tsc -w" "lite-server" 

app/app.component.spec.ts(2,30): error TS2307: Cannot find module './app.component'.
app/app.module.ts(4,31): error TS2307: Cannot find module './app.component'.

i have cloned the latest project and after successfully installing the node_modules when i am trying to run npm start then getting the above error.

**Comment by filipesilva** [comment]
The error seems to indicate that you have deleted `./app.component.ts`.
