### ISSUE TITLE
Failed to load resource: the server responded with a status of 404(Not Found) error

### ISSUE THREAD

**Issue by vignesh-subash** [angular/quickstart#293]
i am getting 404 error and my browser not even looking into my app folder.  any solutions?
![screen shot 2016-11-22 at 3 04 06 pm](https://cloud.githubusercontent.com/assets/13498070/20518370/fb6eca72-b0c4-11e6-80a9-0dc3796e6127.png)

**Comment by filipesilva** [comment]
Do you have any import for `angular2/core`? It should be `@angular/core` instead.

**Comment by vignesh-subash** [comment]
thank you @filipesilva 👍
