### ISSUE TITLE
Please add working code coverage

### ISSUE THREAD

**Issue by gituser7878-Ultralinq** [angular/quickstart#295]
Currently there is no clarity on how to generate code coverage for the latest versions of Angular 2, with karma-coverage, and systemjs as the module loader.

**Comment by rohans84** [comment]
I have submitted a PR for this - https://github.com/angular/quickstart/pull/290

**Comment by gituser7878-Ultralinq** [comment]
Hi @rohans84, it is awesome but still I have issues making it work with our particular code base. As when karma-coverage is used as a preprocessor, the tests never complete. Upon ending the tests prematurely, there is a coverage report that references the component source file that was being tested but it is minimal coverage as the tests were never completed.

**Comment by wardbell** [comment]
Code coverage is a great idea but is not consistent with the relative simplicity we seek for this QuickStart seed. Thanks but we'll have to decline your suggestion.
