### ISSUE TITLE
mistake in the system.config.js?

### ISSUE THREAD

**Issue by konstantin-chernov** [angular/quickstart#296]
Not sure if it apllies here, but my attempt to run [example from angular 2 quickstart](https://angular.io/docs/ts/latest/quickstart.html) failed. I noticed that `system.config.js` has `main: './main.js',` line, while it should be `main: 'app.main.js'`

**Comment by filipesilva** [comment]
There is no `app.main.js` file, perhaps you misread the instructions in https://angular.io/docs/ts/latest/quickstart.html#!#main to create a `app/main.ts` file?
