### ISSUE TITLE
What's the purpose of systemjs.config.extras.js?

### ISSUE THREAD

**Issue by junjunruan** [angular/quickstart#297]
I forked the quick start example, and there is an empty file called systemjs.config.extras.js. In what situation will we need it? Can anyone give me an example?

**Comment by wardbell** [comment]
Its a way of extending the SystemJS configuration with other mappings if your tests require them (e.g., "barrels"). You could modify `systemjs.config.js` directly but we'd rather you didn't. So it looks for this extra file in case you have extra configuration.

You can ignore it until you need it. Even deleting it won't hurt ... you'll just get console messages about it.
