### ISSUE TITLE
This didn't work in either ie11 or ff 36.0.1 on windows 7

### ISSUE THREAD

**Issue by kevinpas** [angular/quickstart#3]
I think I did everything as outlined.

I put a few alerts here and there and they "alerted".

Example: I put an alert in es6-shim.js to prove that it was getting loaded.

**Comment by davideast** [comment]
Can you provide your code or some screenshots?

**Comment by kevinpas** [comment]
This might work:
1)  I have a repo:  https://github.com/kevinpas/Exec2)  clone the
addAngular2 branch: https://github.com/kevinpas/Exec/tree/addAngular2
, I don't know github well enough to know if "anyone" can clone a
branch, get back with me if not3)  in the root, using iojs: iojs
iojsAngular2.js4)  in a browser http://localhost:19002/
if you don't want to use 19002 then edit the json in iojsAngular2.js ,
see "port"      :   19002
node would probably work too if you change these lines:

	var HttpImp     = require( './Imp/HttpImp/iojsHttpServer.js'    );
var FileImp = require( './Imp/FileImp/iojsFile.js' ); to
	var HttpImp     = require( './Imp/HttpImp/nodeHttpServer.js'    );
var FileImp = require( './Imp/FileImp/nodeFile.js' ); 

On ‎3‎/‎19‎/‎2015 at 11:47 AM, "David East"  wrote:Can you
provide your code or some screenshots?

---

**Comment by kevinpas** [comment]
1)  I have a repo:  https://github.com/kevinpas/Exec
2)  clone the addAngular2 branch:
https://github.com/kevinpas/Exec/tree/addAngular2 
, I don't know github well enough to know if "anyone" can clone a
branch, get back with me if not
3)  in the root, using iojs: iojs iojsAngular2.js
4)  in a browser http://localhost:19002/  if you don't want to use
19002 then edit the json in iojsAngular2.js , see "port"      :  
19002 
node would probably work too if you change these lines:

 var HttpImp     = require( './Imp/HttpImp/iojsHttpServer.js'    );
var FileImp = require( './Imp/FileImp/iojsFile.js' ); 
to
var HttpImp     = require( './Imp/HttpImp/nodeHttpServer.js'    );
var FileImp = require( './Imp/FileImp/nodeFile.js' ); 

On ‎3‎/‎19‎/‎2015 at 11:47 AM, "David East"  wrote:Can you
provide your code or some screenshots?
On ‎3‎/‎19‎/‎2015 at 1:35 PM, kevinpas@hushmail.com
wrote:This might work:
1)  I have a repo:  https://github.com/kevinpas/Exec2)  clone the
addAngular2 branch: https://github.com/kevinpas/Exec/tree/addAngular2
, I don't know github well enough to know if "anyone" can clone a
branch, get back with me if not3)  in the root, using iojs: iojs
iojsAngular2.js4)  in a browser http://localhost:19002/
if you don't want to use 19002 then edit the json in iojsAngular2.js ,
see "port"      :   19002
node would probably work too if you change these lines:

 var HttpImp     = require( './Imp/HttpImp/iojsHttpServer.js'    );
var FileImp = require( './Imp/FileImp/iojsFile.js' ); to
 var HttpImp     = require( './Imp/HttpImp/nodeHttpServer.js'    );
var FileImp = require( './Imp/FileImp/nodeFile.js' ); 

On ‎3‎/‎19‎/‎2015 at 11:47 AM, "David East"  wrote:Can you
provide your code or some screenshots?

---

**Comment by kevinpas** [comment]
Look in this folder:  Live/Sites/angular2_quickstart

On ‎3‎/‎19‎/‎2015 at 1:40 PM, kevinpas@hushmail.com wrote:1)
 I have a repo:  https://github.com/kevinpas/Exec
2)  clone the addAngular2 branch:
https://github.com/kevinpas/Exec/tree/addAngular2 
, I don't know github well enough to know if "anyone" can clone a
branch, get back with me if not
3)  in the root, using iojs: iojs iojsAngular2.js
4)  in a browser http://localhost:19002/  if you don't want to use
19002 then edit the json in iojsAngular2.js , see "port"      :  
19002 
node would probably work too if you change these lines:

 var HttpImp     = require( './Imp/HttpImp/iojsHttpServer.js'    );
var FileImp = require( './Imp/FileImp/iojsFile.js' ); 
to
var HttpImp     = require( './Imp/HttpImp/nodeHttpServer.js'    );
var FileImp = require( './Imp/FileImp/nodeFile.js' ); 

On ‎3‎/‎19‎/‎2015 at 11:47 AM, "David East"  wrote:Can you
provide your code or some screenshots?
On ‎3‎/‎19‎/‎2015 at 1:35 PM, kevinpas@hushmail.com
wrote:This might work:
1)  I have a repo:  https://github.com/kevinpas/Exec2)  clone the
addAngular2 branch: https://github.com/kevinpas/Exec/tree/addAngular2
, I don't know github well enough to know if "anyone" can clone a
branch, get back with me if not3)  in the root, using iojs: iojs
iojsAngular2.js4)  in a browser http://localhost:19002/
if you don't want to use 19002 then edit the json in iojsAngular2.js ,
see "port"      :   19002
node would probably work too if you change these lines:

 var HttpImp     = require( './Imp/HttpImp/iojsHttpServer.js'    );
var FileImp = require( './Imp/FileImp/iojsFile.js' ); to
 var HttpImp     = require( './Imp/HttpImp/nodeHttpServer.js'    );
var FileImp = require( './Imp/FileImp/nodeFile.js' ); 

On ‎3‎/‎19‎/‎2015 at 11:47 AM, "David East"  wrote:Can you
provide your code or some screenshots?

---

**Comment by kevinpas** [comment]
The example above won't work because my server isn't processing mime type 'es6', but that is a side issue.

Instead of using my server I npm installed the server that was suggested in the "learn in 5 min", on https://angular.io/ 

Both my server and the one suggested cause FF to dump the following into the console:

"TypeError: el.createShadowRoot is not a function

.execute/BrowserDomAdapter</<.createShadowRoot@http://localhost:8080/quickstart/angular2/src/dom/browser_adapter.js:169:20
.execute/NativeShadowDomStrategy</<.attachTemplate@http://localhost:8080/quickstart/angular2/src/core/compiler/shadow_dom_strategy.js:221:38
.execute/ProtoView</<._instantiate@http://localhost:8080/quickstart/angular2/src/core/compiler/view.js:391:17
.execute/ProtoView</<.instantiate@http://localhost:8080/quickstart/angular2/src/core/compiler/view.js:311:45
_injectorBindings/</<@http://localhost:8080/quickstart/angular2/src/core/application.js:67:20
run@http://localhost:8080/quickstart/dist/es6-shim.js:29889:16
zoneBoundFn@http://localhost:8080/quickstart/dist/es6-shim.js:29866:14
" lang.js:64:6

**Comment by kevinpas** [comment]
ie 11 catches an exception in "run" and reports: "Object doesn't support property or method 'apply'  "

run: function run (fn, applyTo, applyWith) {
    applyWith = applyWith || [];

    var oldZone = window.zone,
        result;

    window.zone = this;

    try {
      this.beforeTask();
      result = fn.apply(applyTo, applyWith);
    } catch (e) {
      if (zone.onError) {
        zone.onError(e);
      } else {
        throw e;
      }
    } finally {
      this.afterTask();
      window.zone = oldZone;
    }
    return result;
  },

**Comment by davideast** [comment]
This repo was just update to a newer version of Angular 2. Can you try again, but with node rather than io?

**Comment by kevinpas** [comment]
FireFox is working but not IE 11.

I am not following this too closely.  Let me know anytime you want me to try it again.

**Comment by kevinpas** [comment]
I'm removing the branch from my repository that uses angular2 / quickstart
