### ISSUE TITLE
i got some error when run npm start

### ISSUE THREAD

**Issue by CAH-FlyChen** [angular/quickstart#304]
node_modules/.2.53.35@@types/selenium-webdriver/index.d.ts(12,11): error TS2300: Duplicate identifier 'Driver'
and much more ...

**Comment by zach5078** [comment]
Same here. 
Tried a lot of methods, still couldn't fix it .

**Comment by wardbell** [comment]
You have to tell us more than this. Something about your environment (e.g, OS) and how you got here. Start clean, try again, keep track of all versions. If you're still stuck, tell us how.

I have to close this issue for lack of actionable information. Come back and ask again once you've got the data. Sorry.
