### ISSUE TITLE
Might not be an issue, but I wonder

### ISSUE THREAD

**Issue by patrickracicot** [angular/quickstart#305]
Previously, when the quickstart found on angular.io was stand-alone, we would have the `package.json` file usually updated in sync with the releases of version.  Currently, in the `package.json` of this quickstart, the versions are still pointing on `~2.2.0`, but on the latest npm version is `2.2.3`.

What is the strategy that is used for the update of this repository?

**Comment by Foxandxss** [comment]
the ~ means that it will install that version or any patch version. So it means that it will install any 2.2.x version, including 2.2.3

**Comment by patrickracicot** [comment]
@Foxandxss That's what I also though, but when I `npm install` and then look into the umd.js files, the specified version in the header of the file is 2.2.0 (`@license Angular v2.2.0`).  Also, when I lookup the actual `package.json` file inside the `node_modules` I see `"version": "2.2.0"`.  

Is this intended? (sorry, I'm kind of new with npm)

**Comment by Foxandxss** [comment]
That shouldn't happen. Clear your node_modules and try again.
