### ISSUE TITLE
Failed to load app.component.css

### ISSUE THREAD

**Issue by patelnav** [angular/quickstart#309]
I was following along the angular tutorial, [at one point](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html) app.component.css is created and set using styleUrls. This works for all components except app.component.ts.

Setting styleUrls to "app/app.component.css" works, but this is inconsistent with the other components.

I've created a branch to illustrate the issue: https://github.com/patelnav/quickstart/tree/style-urls

Other Info:
npm -v: 3.10.9
node -v: v7.2.1
OS: macOS Sierra 10.12.1 (16B2555)

**Comment by slamidtfyn** [comment]
Since the property is called styleUrl it's probably not possible to do this without using the full path. You could use the style property instead and set the styles inline if you only setup a small number of styles 

`styles: ['  h1 {    color: green      }  ']`

**Comment by patelnav** [comment]
@slamidtfyn: the branch I provided was for illustrative purposes, not the actual CSS I'm trying to implement. 

Ah! So adding the moduleId seems to fix this problem. See the two commits on https://github.com/patelnav/quickstart/tree/this-works

This is addressed [here](https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html). 

But it seems the Tour of Heroes tutorial doesn't correctly identify this

**Comment by bjlbernal** [comment]
Thanks, @patelnav. You had the exact same problem I had. Team needs to update Tour of Heroes tutorial at the end of this section [here](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html#!#style-the-navigation-links) where they have the student move the CSS into it's own file. I suggest changing the last code block example form just ```javascriptstyleUrls: ['app.component.css'],``` and mention that ```moduleId: module.id,``` also needs to be added.

**Comment by wardbell** [comment]
Please raise your concerns with Tour of Heroes on the angular.io repo.
