### ISSUE TITLE
The package es6-shim@0.35.0 does not satisfy its siblings' peerDependencies requirements

### ISSUE THREAD

**Issue by cezarykluczynski** [angular/quickstart#31]
I'ts impossible to install after cd290d9558a4e4932a5c3f0521650eb2df2f9354. Without it, npm install works fine. Error message is:

npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package es6-shim@0.35.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.9 wants es6-shim@^0.33.3

**Comment by raaspazasu** [comment]
You need to upgrade npm to the latest version.
`sudo npm install -g npm`

**Comment by wardbell** [comment]
Is annoying but is not actually blocking. Resolved as of beta.11
