### ISSUE TITLE
Failed to startup

### ISSUE THREAD

**Issue by anxing131** [angular/quickstart#310]
I'm  following tutorial to download by git, run `npm start` command has errors : 
![image](https://cloud.githubusercontent.com/assets/23404814/21004314/a7ac3c00-bd6a-11e6-89bf-d5694869d8c4.png)

Other Info:
npm -v: 3.8.9
node -v: v6.2.0
OS: Win7_64
IDE: webstorm(2016.02)

**Comment by wardbell** [comment]
Cannot repro. Perhaps something bad happened during your `npm install` such as a network failure during download. Please delete the `node_modules` folder and try `npm install` again. Or start the whole process over.

Closing. If this recurs, open a new issue, reference this one ... and maybe someone can walk through it.

**Comment by bp-dev** [comment]
I also had a lot of "error TS2300: Duplicate identifier" and "error TS2403: Subsequent variable declarations must have the same type" errors on a fresh git clone, all went away when I manually deleted the typings folder.
I'm guessing a transition from typings to node_modules/@types
