### ISSUE TITLE
Does not start on Safari 8.0 / OSX 10.10 - Strict mode does not allow function declarations in a lexically nested statement

### ISSUE THREAD

**Issue by juavol** [angular/quickstart#311]
Downloaded the source and did npm install and npm start (on my development machine, which is Windows). Works fine with Chrome under Windows and Chrome from a Mac running OSX 10.10. 

However, on Safari 8.0 on a Mac, the browser is "stuck" in the loading screen showing "Loading AppComponent content here". The dev console shows the following error:

>  "**(SystemJS) Strict mode does not allow function declarations in a lexically nested statement**.
> 	eval@[native code]
> 	invoke@http://devmachine:3000/node_modules/zone.js/dist/zone.js:229:31
> 	run@http://devmachine:3000/node_modules/zone.js/dist/zone.js:113:49
> 	http://devmachine:3000/node_modules/zone.js/dist/zone.js:509:60
> 	invokeTask@http://devmachine:3000/node_modules/zone.js/dist/zone.js:262:40
> 	runTask@http://devmachine:3000/node_modules/zone.js/dist/zone.js:151:57
> 	drainMicroTaskQueue@http://devmachine:3000/node_modules/zone.js/dist/zone.js:405:42
> 	g@http://devmachine:3000/node_modules/core-js/client/shim.min.js:8:19058
> 	http://devmachine:3000/node_modules/core-js/client/shim.min.js:8:19180
> 	k@http://devmachine:3000/node_modules/core-js/client/shim.min.js:8:14294
> 	Evaluating http://devmachine:3000/node_modules/@angular/compiler/bundles/compiler.umd.js
> 	Error loading http://devmachine:3000/node_modules/@angular/compiler/bundles/compiler.umd.js as "@angular/compiler" from http://devmachine:3000/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js"

**Comment by juavol** [comment]
Just checked with OSX 10.12 and Safari 10 and it does work ok. It is however also stuck on Safari/iPhone and Chrome/iPhone - although I currently have issues investigating what the error is there.

Note: this is always the same Windows machine as the server, just different OSX/IOS clients.

**Comment by folgorante** [comment]
On my system:
```
$ uname -a
Linux ton 4.7.0-1-amd64 #1 SMP Debian 4.7.5-1 (2016-09-26) x86_64 GNU/Linux
$ node -v
v6.9.1
$ npm -v
3.10.9
$ firefox -v
Mozilla Firefox 45.4.0

@angular/common@~2.3.0
typescript@~2.0.10
zone.js@^0.7.2

```

The code doesn't work in the browser, it gives the following error:

```
Error: (SystemJS) in strict mode code, functions may be declared only at top level or immediately within another function
	ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:229:17
	Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:113:24
	scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:509:52
	ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:262:21
	Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:151:28
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:405:25
	ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:336:25
	
	Evaluating http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js
	Error loading http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js as "@angular/compiler" from http://localhost:3000/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js
Stack trace:
(SystemJS) in strict mode code, functions may be declared only at top level or immediately within another function
	ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:229:17
	Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:113:24
	scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:509:52
	ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:262:21
	Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:151:28
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:405:25
	ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:336:25
	
	Evaluating http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js
	Error loading http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js as "@angular/compiler" from http://localhost:3000/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js localhost:3000:18:49
```

With older versions of node_modules copied from an older installation
```
@angular/common@~2.1.2
typescript@^2.0.3
zone.js@^0.6.26
```
it works.

**Comment by sylv01** [comment]
Same error confirmed on CentOS 7 with firefox.

uname -a
Linux abc123 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

node -v 
v7.2.1

npm -v
4.0.3

Mozilla Firefox 45.4.0

Error: (SystemJS) in strict mode code, functions may be declared only at top level or immediately within another function
	ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:229:17
	Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:113:24
	scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:509:52
	ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:262:21
	Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:151:28
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:405:25
	ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:336:25
	
	Evaluating http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js
	Error loading http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js as "@angular/compiler" from http://localhost:3000/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js
Stack trace:
(SystemJS) in strict mode code, functions may be declared only at top level or immediately within another function
	ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:229:17
	Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:113:24
	scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:509:52
	ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:262:21
	Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:151:28
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:405:25
	ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:336:25
	
	Evaluating http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js
	Error loading http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js as "@angular/compiler" from http://localhost:3000/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js localhost:3000:19:49

**Comment by filipesilva** [comment]
Heya all, this seems to be a problem with Angular 2.3.0 and you can find more information in these issues:

- https://github.com/angular/angular/issues/13301
- https://github.com/angular/angular/issues/13311 (sends you to the first one)

A fix seems to already be in master and I suppose it will be out in the next release.
