### ISSUE TITLE
Clarity for package.json

### ISSUE THREAD

**Issue by patelnav** [angular/quickstart#313]
There's a ton of packages being included here. Can we cluster and comment on the dependancies, and what they're used for (essential, spec-testing, e2e-testing, etc . 

This file is really hard to make sense of

**Comment by wardbell** [comment]
Sorry about that but the quickstart is a seed to get you started. We do not intend to explain the configuration files here because that is a distraction from learning Angular. 

Moreover, officially, comments are NOT allowed in JSON files.
Complain to the inventor, [Douglas Crockford](https://news.ycombinator.com/item?id=3912149) :-)

**Comment by patelnav** [comment]
Sure! No comments in JSON 👍🏾 
But perhaps the dependencies and tools should be explained somewhere. I found having all these files and dependencies in the "Getting Started"/"quickstart" was a distraction from learning Angular! 

There are optional choices being made in the repository for which CI/testing/e2e tools are used on top of  what Angular needs to just work. These optional dependencies should be explicitly called out.

If you guys want to take an official stance on use X tool for Y, perhaps a separate repository that's not the "learning Angular" repo would be the best place

**Comment by wardbell** [comment]
I agree that we should explain the contents and we intend to do so in the angular.io docs (under setup anatomy). I don't agree that we have to do so in this repo.

Our official stance is that these packages work together ... not that you should or have to use them.

You could reasonably question why we are encouraging testing in our QS seed. We've decided to do so. Sorry that you find it distracting. Hope you can overlook the distractions and enjoy Angular.
