### ISSUE TITLE
npm not working got many error

### ISSUE THREAD

**Issue by Akhand2505** [angular/quickstart#317]
Hey guys, spent yesterday doing some angular2 stuff

Then this morn I went to do an npm start and get the attached error messages?

Any ideas? I have made sure I have the latest npm and node as you can see in the debug file, and I have made sure that concurrently, lite-server and typescript are all globally installed.

Still nothing seems to work - not sure how it could go from working fine yesterday to not working without making any changes that I can foresee would stop npm start??

**Comment by filipesilva** [comment]
Heya, it looks like you accidentally changed part of your npm script in `package.json`.

Make sure it looks like this:
```
"start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
```

**Comment by filipesilva** [comment]
Oh and there's no need to have any package globally installed. Whatever is on `package.json` scripts always has the local node_modules added to path!
