### ISSUE TITLE
404 error while refreshing : "http://localhost:3000/detail/12" 

### ISSUE THREAD

**Issue by ddavidad** [angular/quickstart#319]
I get am error 404 while trying to go to an address with parameters...if you can please explain to me what i did wrong if at all.
for some reason the all the links wore broken, after adding "/" before the path fixed them, but the "main" could not load properly.
I don't have a better way of explaining the issue then the title+the images below.
 thank you in advance.

![image](https://cloud.githubusercontent.com/assets/8751297/21176614/389d989c-c1f0-11e6-8997-00da66af4dd2.png)

![image](https://cloud.githubusercontent.com/assets/8751297/21176798/fb4eba4c-c1f0-11e6-81a2-af495b166213.png)

**Comment by wardbell** [comment]
Sorry but this doesn't look like an issue with the QuickStart itself and those are the only issues we can handle. Please present your case to a forum such as StackOverflow.

**Comment by ddavidad** [comment]
thank you @wardbell
