### ISSUE TITLE
Trying the quickstart, but getting an error.

### ISSUE THREAD

**Issue by jbarber2016** [angular/quickstart#324]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 no such package available : @angular/common
npm ERR! 404
npm ERR! 404  '@angular/common' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404 It was specified as a dependency of 'angular-quickstart'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Downloads\quickstart\npm-debug.log

**Comment by Foxandxss** [comment]
Install a newer npm

**Comment by jbarber2016** [comment]
This is the absolute latest.  Goto nodejs.org and 6.9.2 is the latest you can get for windows unless you want to try the experimental stuff.  I actually figured it out by doing the following.  

npm set registry http://registry.npmjs.org

**Comment by Foxandxss** [comment]
Newer npm, not node

**Comment by jbarber2016** [comment]
Ok, agreed, but npm is bundled with nodejs.  3.5.2 is the latest AFAIK.  But either way, I am all good with the registry.

**Comment by Foxandxss** [comment]
Latest is 4, but with a 3.10.x it is happy

**Comment by shanecarmody** [comment]
@jbarber2016 had the same issue, your solution to set the registry first worked for me 👍

**Comment by cyuno** [comment]
Setting the registry and having the latest npm and node still doesn't work or me. I am on windows 10:

npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
...
npmERR! Failed to parse package.json data
npmERR! package.json must be actual JSON not just JavaScript
npmERR!
npmERR! This is not a bug in npm.

I am using node v6.9.2, npm v3.10.10

**Comment by jbarber2016** [comment]
I would guess something is wrong with your package.json, maybe the encoding isn't correct but hard to know without seeing it.

**Comment by cyuno** [comment]
I cloned the repository. Here is the file:
package.json:


{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "e2e": "tsc && concurrently \"http-server -s\" \"protractor protractor.config.js\" --kill-others --success first",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "lite-server",
    "pree2e": "webdriver-manager update",
    "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
    "test-once": "tsc && karma start karma.conf.js --single-run",
    "tsc": "tsc",
    "tsc:w": "tsc -w"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.0",

    "angular-in-memory-web-api": "~0.2.2",
    "systemjs": "0.19.40",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.1",
    "zone.js": "^0.7.4"
  },
  "devDependencies": {
    "concurrently": "^3.1.0",
    "lite-server": "^2.2.2",
    "typescript": "~2.0.10",

    "canonical-path": "0.0.2",
    "http-server": "^0.9.0",
    "tslint": "^3.15.1",
    "lodash": "^4.16.4",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~4.0.14",
    "rimraf": "^2.5.4",

    "@types/node": "^6.0.46",
    "@types/jasmine": "^2.5.36"
  },
  "repository": {}
}

**Comment by henioStraszny** [comment]
I have similar problem, attaching npm log.
[npm-debug.log.txt](https://github.com/angular/quickstart/files/681303/npm-debug.log.txt)

**Comment by henioStraszny** [comment]
Apparently problem was related to zone.js: https://github.com/angular/zone.js/issues/554 

I've fixed it by updating package.json dependencies to newest one and doing npm install.
