### ISSUE TITLE
Build fails: error MSB6006: "tsc.exe" exited with code 1.

### ISSUE THREAD

**Issue by AmirHMousavi** [angular/quickstart#335]
following the guide step by step, but on build time I get tsc.exe exit code 1.
here is the normal log of visual studio 2015 update 3
```
1>------ Build started: Project: AngularApplication1, Configuration: Debug Any CPU ------
1>Build started 12/23/2016 10:27:39 AM.
1>PreComputeCompileTypeScriptWithTSConfig:
1>  C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "D:\WorkSpace\visual studio 2015\Projects\AngularApplication1\AngularApplication1\tsconfig.json" 
1>CompileTypeScriptWithTSConfig:
1>  C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "D:\WorkSpace\visual studio 2015\Projects\AngularApplication1\AngularApplication1\tsconfig.json" 
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(214,5): error MSB6006: "tsc.exe" exited with code 1.
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:00.57
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by ibqn** [comment]
The typescript version 1.8 used above might be simply too old, please try with 2.0.10

I am personally not aware of the VS integration, but the way I run it on windows is:

- install [git bash](https://git-for-windows.github.io/)
- install [nodejs](https://nodejs.org/en/download/)
- open git bash window and clone the repo (git clone https://github.com/angular/quickstart.git)
- run 'cd quickstart' followed by 'npm install' and 'npm start'

**Comment by AmirHMousavi** [comment]
the fact is when we move $(PATH) entry above the $(DevEnvDir) entries, why it does not use tcs from node modules?

**Comment by filipesilva** [comment]
Typescript 2.0.x is needed for the quickstart to properly compile. 

I don't use Visual Studio myself so I can't help you with the config, but there must be a setting somewhere that allows you to use the local TS version instead of the global one that VS has.

Visual Studio Code and Webstorm have such options, so I assume VS does as well.
