### ISSUE TITLE
zone.js: Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by roroco** [angular/quickstart#338]
here is my [stackoverflow question](http://stackoverflow.com/questions/41318672/zone-js-uncaught-rangeerror-maximum-call-stack-size-exceeded), I only try [this demo](https://github.com/angular/quickstart) with `npm i; npm start`, I don't change any code.

here is my env:

```
roroco@roroco ~/Downloads/ng2-quickstart $ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah
roroco@roroco ~/Downloads/ng2-quickstart $ google-chrome -version
Google Chrome 55.0.2883.87
```

**Comment by roroco** [comment]
This issue is fixed in https://github.com/angular/angular/issues/13667

**Comment by filipesilva** [comment]
Heya @roroco, glad you got it sorted. That extension must be doing something weird :/
