### ISSUE TITLE
Uncaught TypeError: Cannot read property 'zone' of undefined

### ISSUE THREAD

**Issue by jokira247** [angular/quickstart#34]
A fresh install shows this error in Google Chrome Console.

Uncaught TypeError: Cannot read property 'zone' of undefined  @ angular2-polyfills.js:258

**Comment by cgmartin** [comment]
Also seeing the same browser console error from commit 0fb8db4de578b41300dfde84f7fbb06a3f563b11

If I downgrade to previous cd290d9558a4e4932a5c3f0521650eb2df2f9354 (angular 2 beta-9) it works.

Related thread: https://github.com/angular/angular/issues/7652

**Comment by wardbell** [comment]
Known, reported bug. Annoying but not actually blocking. Expect to clear up by beta.12

**Comment by wardbell** [comment]
Should be clear now in beta.12
