### ISSUE TITLE
What happened to 'typings' file and dir?

### ISSUE THREAD

**Issue by dylanh724** [angular/quickstart#340]
I'm trying to follow a Udemy tutorial and it's not there -- am I following an old tutorial or am I missing something?

**Comment by filipesilva** [comment]
Heya, we took those out a while ago when we switched to using`@types/*` in https://github.com/angular/quickstart/pull/157.

You can also read more about `@types` in these pages:
- https://angular.io/docs/ts/latest/guide/typescript-configuration.html#!#typings
- http://www.typescriptlang.org/docs/handbook/declaration-files/consumption.html
