### ISSUE TITLE
quick start only show "Loading AppComponent content here ..."

### ISSUE THREAD

**Issue by HelloWorldCAT** [angular/quickstart#348]
### environment:
```
system: ubuntu 12.04
node: v6.9.3
npm: 3.10.10
```
### when I follow step:
```
git clone https://github.com/angular/quickstart.git quickstart
cd quickstart
npm install
npm start
```
### firefox showing:
 "Loading AppComponent content here ..."
not
"Hello Angular".

### in the firefox console, errors below:
```
http://localhost:3000/node_modules/core-js/client/shim.min.js is being assigned a //# sourceMappingURL, but already has one
Error: (SystemJS) invalid range in character class
	RegExp@http://localhost:3000/node_modules/core-js/client/shim.min.js:8:6158
	Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:242:1
	Zone$1</Zone</Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:113:17
	scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:520:78
	Zone$1</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:275:1
	Zone$1</Zone</Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:151:21
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:418:25
	ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:349:25
	
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js
Stack trace:
(SystemJS) invalid range in character class
	RegExp@http://localhost:3000/node_modules/core-js/client/shim.min.js:8:6158
	Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:242:1
	Zone$1</Zone</Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:113:17
	scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:520:78
	Zone$1</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:275:1
	Zone$1</Zone</Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:151:21
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:418:25
	ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:349:25
	
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js localhost:3000:19
```

**Comment by amassarwi** [comment]
what is the output of your `npm install` command ?

**Comment by irakli2692** [comment]
doesn't work on old firefox browser

**Comment by hirenalken** [comment]
updating browser has solved this issue for me

**Comment by vishalbayskar** [comment]
For me, it was a result of a silly typo in a template.
instead of label I was using lable.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)

**Comment by klausenbusk** [comment]
> Starting from 1 November 2017, all the Angular documentation, at angular.io, is based on the Angular CLI.

https://angular.io/docs refer to a non-working quick start example: https://angular.io/generated/live-examples/quickstart/eplnkr.html , just a heads-up..

**Comment by Foxandxss** [comment]
It works for me. Still, that link will die soon. It actually refers to the old quickstart which I need to delete as soon as I finish some other required steps.

**Comment by klausenbusk** [comment]
> It works for me.

Weird, with a few days old Firefox Nightly it isn't working, but as you said it will be gone "soon", so who cares :)

**Comment by elirehema** [comment]
I resolve it by using http://localhost:3000/ instead of http://localhost
