### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by DhiaEddineSaidi** [angular/quickstart#349]
log file : Chromium 53.0.2785 (Ubuntu 0.0.0): Executed 0 of 0 SUCCESS (0 secs / 0 secs)

ium 53.0.2785 (Ubuntu 0.0.0): Executed 0 of 0 ERROR (0.015 secs / 0 secs)

npm ERR! Linux 4.4.0-51-generic

npm ERR! argv "/home/travis/.nvm/versions/node/v5.12.0/bin/node" "/home/travis/.nvm/versions/node/v5.12.0/bin/npm" "run" "test-once"

npm ERR! node v5.12.0

npm ERR! npm  v3.8.6

npm ERR! code ELIFECYCLE

npm ERR! angular-quickstart@1.0.0 test-once: `tsc && karma start karma.conf.js --single-run`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the angular-quickstart@1.0.0 test-once script 'tsc && karma start karma.conf.js --single-run'.

npm ERR! Make sure you have the latest version of node.js and npm installed.

npm ERR! If you do, this is most likely a problem with the angular-quickstart package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     tsc && karma start karma.conf.js --single-run

npm ERR! You can get information on how to open an issue for this project with:

npm ERR! Or if that isn't available, you can get their info via:

npm ERR!     npm owner ls angular-quickstart

npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

npm ERR!     /home/travis/build/DhiaEddineSaidi/QuickstartAngular/npm-debug.log

**Comment by faisalsaghir7** [comment]
hey bro 
i found the solution
go packge.json and replace this code of lines 

"scripts": {
    "start": "concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },

**Comment by jasperchow** [comment]
@faisalsaghir7  "start": "concurrently "npm run tsc:w" "npm run lite" ",

npm ERR! Unexpected token 'p' at 6:30
npm ERR!     "start": "concurrently "npm run tsc:w" "npm run lite" ",
npm ERR!                              ^

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
