### ISSUE TITLE
Workflow Automation Question

### ISSUE THREAD

**Issue by grayskwrl149** [angular/quickstart#350]
This is the 2nd Angular project I've looked at. The first was an example app in a book. It used gulp for workflow automation. I don't see anything in your package.json for that. But I'm new to such things, so am I just missing it? What does this use for workflow automation?

Thanks,
Jerry

PS: Is this the correct way to submit questions?

**Comment by wardbell** [comment]
It's a fine question. The answer is ... the Angular docs deliberately minimize the role of external tools and, because we can accomplish what we need to accomplish without gulp, we do.  But you should feel free to use it.
