### ISSUE TITLE
Quick start deployment

### ISSUE THREAD

**Issue by alisherabd** [angular/quickstart#354]
I have build the app and everything works perfect regarding the developmental environment. But how can I manage to make a production environment. I have looked into editing scripts into `package.json` but no success. Would be great if you can include scripts like `npm run build` and npm run build_prod.

Thanks

**Comment by wardbell** [comment]
We are working on guidance for deploying to production.We have nothing to add to QS in that regard at this time. Closing for now. When we do ... will add it.

**Comment by alisherabd** [comment]
Thank you
