### ISSUE TITLE
Response with status: 0  for URL: null

### ISSUE THREAD

**Issue by tungphamdev** [angular/quickstart#356]
I don't know why I can't get json from my nodejs server (express). I test so many browser and just with Internet Explorer and Microsoft Edge operate normally. Chorme, Firefox alway 'Response with status: 0  for URL: null'.

this my code:
import {Component, OnInit} from '@angular/core';
import {Injectable}    from '@angular/core';
import {Http, Response} from '@angular/http';
import {Observable} from 'rxjs';
@Injectable()
@Component({
  selector: 'my-app',
  template: `<h1>Hello {{name}}</h1>`,
})
export class AppComponent implements OnInit {

  name: any;

  constructor(private _http: Http) {
  }

  ngOnInit(): void {
    try {
      this.getAllData();
    } catch (e) {
      alert(e);
    }
  }

  getData(): Observable<any> {
    return this._http.get('http://localhost:7000/')
      .map((r: Response) => r.json());
  }

  getAllData() {
    this.getData().subscribe(
      data => this.name = data.data,
      err => alert(err));
  }

**Comment by wardbell** [comment]
I'm sorry but this is not a QuickStart issue. Would be better on StackOverflow. Closing

**Comment by devbratraghuvanshi** [comment]
I think best way is check if request is of type "OPTIONS" return 200 from middle ware. It worked for me.

express.use('*',(req,res,next) =>{
      if (req.method == "OPTIONS") {
        res.status(200);
        res.send();
      }else{
        next();
      }
    });
