### ISSUE TITLE
e2e tests failing - pass in browser but return error message & code from shell

### ISSUE THREAD

**Issue by goblinfactory** [angular/quickstart#360]
I believe I have the latest version of node `v7.4.0` and npm `4.0.5`, and did a git clone of the quickstart few minutes ago (23h45m  19 Jan 2017), ran 

```
> npm install
> npm run pre2e2
> npm run e2e
```
After the above, the tests appeared to run ok (and pass) in the browser, however the shell returned the following error; (I have attached the npm logfile from that run `npm-debug.log.zip`)

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "e2e"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 e2e: `tsc && concurrently "http-server -s" "protractor protractor.config.js" --kill-others --success first`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 e2e script 'tsc && concurrently "http-server -s" "protractor protractor.config.js" --kill-others --success first'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "http-server -s" "protractor protractor.config.js" --kill-others --success first
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alanhemmings/src/git-alan-public/study-ang2-play-by-play/npm-debug.log

```

[npm-debug.log.zip](https://github.com/angular/quickstart/files/718060/npm-debug.log.zip)

**Comment by goblinfactory** [comment]
Update : 10h37 20 Jan : doing another fresh git clone and running the commands below I am now no longer able to reproduce the error. I had observed the error for a few days on various other fresh checkouts, and for the life of me I can't see what's changed on my system if anything.  Closing this issue as I'm satisfied its most likely a really odd local machine issue. (from my noobie perspective)

**Comment by goblinfactory** [comment]
**I think I've worked out the sequence of how I ended up with the symptoms described** 

- I was initially running the `npm run test` (unit test) and this was working ok. 
- I was following along  a play-by-play with @jonpapa and I believe I had done a few of steps before actually running e2e for the first time. 
- That test runs, and there's no visible error in the Chrome window that appears, however, if the title of the `Hello Angular` changes to something that the end to end spec does not expect the test fails, but the chrome window does not show anything similar to the error you see in a failed unit test
 - also, the output in the console window is quite long, and the text showing `1 failed spec(s)` had already scrolled off the window, and the only visible text is the `npm ERR! texts` with a very specific messaging encouraging the submission of an `angular-quickstart` bug report.
- I'm a noobie angular (and javascript) developer, and come from an ops-ish background, `fake, msbuild` etc, where I'm used to making sure the build outputs are as simple as possible, and can read like a story. 

**lesson learnt?**

- test on multiple machines?
- test with with colleague first, before submitting bug report
- protractor/jasmine (?) output should not show `npm ERR!` output from a test run, that should (imho) indicate an unexpected script error. If I see that then something in the build process is broken. It should be easy for a non programmer to read the build output and the error message should be self documenting. (so, imho, this can be improved.)
- the test failing, was actually valid, and was not a script error. The test executed successfully and returned a valid error result of (1). Although this does appear to lead to a discussion around how noisy should an 'npm' error be, and under what circumstances can we override the npm default error messages. (I don't know, again, me...noob, so just noting this here, because I think it's relevant.) For example, if there is a way to return (1) to 'npm' as well as the appropriate error message to display, one for (verbose) and other for (standard) then that would be a great take-away for me, and a win.

**Comment by filipesilva** [comment]
Heya, I'm glad you got it sorted, and thanks for taking the time to write up your experience! 

I agree with you that npm errors are quite noisy. They also aren't very helpful by themselves to post back to repo maintainers. Those long error logs happen *specifically* because stuff is being ran as a [npm script](https://docs.npmjs.com/misc/scripts). Basically it tacks on its own error message in addition to whatever the real command put out.

I haven't looked much into it but it would be nice to be able to remove that extra error text. I don't think there is a reasonable way to do it for new users though, that's the kind of thing that needs system configuration usually.

**Comment by filipesilva** [comment]
Here's an NPM issue on the topic: https://github.com/npm/npm/issues/6124

Seems you can do `npm run e2e --silent` (or `-s`).

**Comment by goblinfactory** [comment]
Ah great, thanks for the feedback. Does this mean you'll update the quickstart?  (Sorry too new to npm and javascript to dive in and submit a pull request myself.) Plus signing the contracts to `become a contributor` seems overboard for a 1 liner fix? ;-D

**Comment by filipesilva** [comment]
That's the thing though, it can't be fixed on `package.json` itself. At least when I tried adding it inside the script it didn't work. So users would always have to do it. Which also kinda sucks.
