### ISSUE TITLE
app/app.module.ts(4,29): error TS2307: Cannot find module './hero-service'.

### ISSUE THREAD

**Issue by debbiev** [angular/quickstart#365]
I get this error whenever I add this line to app.component.ts:

  import { HeroService } from './hero-service';

If I stop npm, and restart it (ctrl-c, npm start), I get the following:

debbiev@DebsSonyLaptop:~/Projects/Firebase/heros$ npm start

> angular-quickstart@1.0.0 start /home/debbiev/Projects/Firebase/heros
> tsc && concurrently "tsc -w" "lite-server" 

app/app.component.ts(3,29): error TS2307: Cannot find module './hero-service'.
app/app.module.ts(4,29): error TS2307: Cannot find module './hero-service'.

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/debbiev/Projects/Firebase/heros/npm-debug.log

---------------------------------------------------------
If I remove the import statement, everything works fine.
Here is a directory listing:

Projects/Firebase/heros$ ls
angular-quickstart@1.0.0
app
CHANGELOG.md
e2e
favicon.ico
index.html
karma.conf.js
karma-test-shim.js
LICENSE
node_modules
non-essential-files.txt
package.json
protractor.config.js
README.md
styles.css
systemjs.config.extras.js
systemjs.config.js
tsc
tsconfig.json
tslint.json
debbiev@DebsSonyLaptop:~/Projects/Firebase/heros$ ls app
app.component.js
app.component.js.map
app.component.spec.js
app.component.spec.js.map
app.component.spec.ts
app.component.ts
app.module.js
app.module.js.map
app.module.ts
hero-detail.component.js
hero-detail.component.js.map
hero-detail.component.ts
hero.js
hero.js.map
hero.service.js
hero.service.js.map
hero.service.ts
hero.ts
main.js
main.js.map
main.ts
mock-heroes.js
mock-heroes.js.map
mock-heroes.ts

----------------------------------

Make sure you have the latest version of node.js and npm installed:

debbiev@DebsSonyLaptop:~/Projects/Firebase/heros$ npm -v
3.5.2
debbiev@DebsSonyLaptop:~/Projects/Firebase/heros$ node -v
v4.2.6

--------------------------------------------

**Comment by Foxandxss** [comment]
It is hero.service not hero-service

**Comment by debbiev** [comment]
That worked!  Thank you!

**Comment by SupradaChethan** [comment]
That worked for me, Thanks!

**Comment by chromial** [comment]
same error message, different module
------------------------------------
src/app/mock-heroes.ts(1,22): error TS2307: Cannot find module './hero'.
This is what the tutorial says to use
--------------------------------------------------
import { Hero } from './hero';

**Comment by mwanduka** [comment]
ERROR in src/app/app.module.ts(10,36): error TS2307: Cannot find module './search/search-box/search-box.component'.
src/app/app.module.ts(11,33): error TS2307: Cannot find module './search/search/search.component'.
src/app/profile/profile.component.ts(33,16): error TS2339: Property 'getDetails' does not exist on type 'ProfileComponent'.
src/app/profile/profile.component.ts(46,18): error TS2339: Property 'getDetails' does not exist on type 'ProfileComponent'.
src/app/routing/routing.module.ts(8,33): error TS2307: Cannot find module '../search/search/search.component'.

**Comment by selvam326** [comment]
ERROR in src/app/app.module.ts(8,32): error TS2307: Cannot find module './layout/admin/admin.component'.
src/app/app.module.ts(9,34): error TS2307: Cannot find module 'ng-click-outside'.
src/app/app.module.ts(12,36): error TS2307: Cannot find module './layout/admin/breadcrumbs/breadcrumbs.component'.
src/app/app.module.ts(13,30): error TS2307: Cannot find module './layout/admin/title/title.component'.
src/app/app.routing.ts(2,30): error TS2307: Cannot find module './layout/admin/admin.component'.
