### ISSUE TITLE
Issue with npm start

### ISSUE THREAD

**Issue by dineshsinghchauhan** [angular/quickstart#367]
I am using angular2 quick start with Ubuntu 16.14 LTS
when I run `npm start` itnot work, display following error in terminal 
```
> angular-quickstart@1.0.0 start /media/dinesh/Dinesh/prac/angular2/quickstart
> tsc && concurrently "tsc -w" "lite-server" 

app/app.component.ts(13,29): error TS1005: ';' expected.

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/dinesh/Dinesh/prac/angular2/quickstart/npm-debug.log
```

Here is attched 'npm-debug.log'
[npm-debug.txt](https://github.com/angular/quickstart/files/734974/npm-debug.txt)

**Comment by Foxandxss** [comment]
Did you read the error? It is quite clear.

**Comment by dineshsinghchauhan** [comment]
@Foxandxss  I am new to angular I didn't understand what to do to to resolve this
can you help please

**Comment by Foxandxss** [comment]
`app/app.component.ts(13,29): error TS1005: ';' expected.`

**Comment by gleamingali** [comment]
I have the same issue with npm start.....can you help me plz
node v6.9.5
npm 3.10.10

> angular-quickstart@1.0.0 start C:\Projects\myapp
> tsc && concurrently "tsc -w" "lite-server" 

 Error occured when executing command: tsc -w
 Error: Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAG env variable.
     at detectExecuteFlag (C:\Projects\myapp\node_modules\spawn-default-shell\src\get-shell.js:29:9)
     at getShell (C:\Projects\myapp\node_modules\spawn-default-shell\src\get-shell.js:37:18)
     at Object.spawn (C:\Projects\myapp\node_modules\spawn-default-shell\src\index.js:5:24)
     at C:\Projects\myapp\node_modules\concurrently\src\main.js:192:34
     at arrayMap (C:\Projects\myapp\node_modules\lodash\lodash.js:660:23)
     at Function.map (C:\Projects\myapp\node_modules\lodash\lodash.js:9571:14)
     at run (C:\Projects\myapp\node_modules\concurrently\src\main.js:181:22)
     at main (C:\Projects\myapp\node_modules\concurrently\src\main.js:61:5)
     at Object.<anonymous> (C:\Projects\myapp\node_modules\concurrently\src\main.js:421:1)
     at Module._compile (module.js:570:32)
     at Object.Module._extensions..js (module.js:579:10)
     at Module.load (module.js:487:32)
     at tryModuleLoad (module.js:446:12)
     at Function.Module._load (module.js:438:3)
     at Module.runMain (module.js:604:10)
     at run (bootstrap_node.js:394:7)

**Comment by SamJWeissman** [comment]
@dineshsinghchauhan 

Hey man -- I wasn't having the exact same error but something extremely similar. I bumped the version of typescript and npm start working fine now.

IE: Went into package.json changed typescript from ~2.0.10 to ^2.0.10 

Hope this helps you too.

**Comment by Foxandxss** [comment]
Both problems are unrelated.

Stay in TS 2.0.10, 2.1 is not compatible with AOT.

**Comment by SamJWeissman** [comment]
@Foxandxss 

I haven't touched anything within the quickstart project yet, but was getting a similar npm error:

error TS1005: '=' expected.

I'm on a fresh clone and running latest versions of node and npm. The first thing that worked for me was bumping versions of typescript. 

Either something is wrong with the code in this project, or some package ( not necessarily typescript I guess? ) is out of date.

Any suggestions?

Thanks,
--Sam

**Comment by Foxandxss** [comment]
Yes, I just answered that issue.

You need to lock the @types/jasmine into a previous version. Latest one is broken for us.

**Comment by SamJWeissman** [comment]
@Foxandxss 

Awesome, it's working. Thanks!

I hadn't seen you answer that. Was this discussed in a separate issue ( and if so would you mind pointing me to it )?

**Comment by Foxandxss** [comment]
https://github.com/angular/quickstart/issues/380

**Comment by SamJWeissman** [comment]
Awesome, thanks again @Foxandxss !

**Comment by muyuqiu001** [comment]
@Foxandxss hello,I am facing the same error,
```
> npm run build


> angular-quickstart@1.0.0 build D:\js\angular2\quickstart
> tsc -p src/

node_modules/@types/jasmine/index.d.ts(39,52): error TS1005: '=' expected.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\node-v6.9.5-win-x64\\node.exe" "D:\\Program Files\\node-v
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
```

which version of jasmine should be locked? and the node/npm version affect the issue?

And i download the latest code from git~

thanks~

**Comment by KhizerRehan** [comment]
Can any one Help on this Error ??

 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1022:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:359:16)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:394:7)
     at startup (bootstrap_node.js:149:9)
     at bootstrap_node.js:509:3
 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1022:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:359:16)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:394:7)
     at startup (bootstrap_node.js:149:9)
     at bootstrap_node.js:509:3
[1] npm run serve exited with code -4058

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\khizer Rehan\\AppData\\Roaming\\npm\\node_modules\\
bin\\npm-cli.js" "start"
npm ERR! node v6.9.5
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "npm run serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'concurrently "npm run build:watch" "npm run serve"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run build:watch" "npm run serve"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\khizer Rehan\AppData\Roaming\npm-cache\_logs\2017-02-18T21_42_15_956Z-debug.log

F:\NodeApps\Angular2\DesignCourse\angular-quickstart\quickstart>

**Comment by Sheetalshinde71** [comment]
hello, I m facing some error 
![capture](https://cloud.githubusercontent.com/assets/25894767/23121227/986a692e-f785-11e6-877a-4eb0d9737438.PNG)

**Comment by Yourwebgirl** [comment]
I am by no means an expert. I'm learning Angular2 for the first time. And I am new to Node.  I've seen this error screen twice on this project, so far. Both times there was something wrong in my code, not with Node. For instance misspelling a keyword or function name. Also using the wrong quotation marks. In some places, the quotation is not a normal single quote. It's the italicized quote located on the key before the 1 key on a standard keyboard. Hope this helps a bit.

**Comment by Sheetalshinde71** [comment]
@Yourwebgirl  thanks for the help ,let me check my code first

**Comment by KhizerRehan** [comment]
@Sheetalshinde71 if you couldn't find the error! than try this because i was facing the same issue although i made no changes in angular-quick start.i simply cloned the project from github and after installing packages(npm install) i hit npm start but a bunch of error's were deisplayed.

 Try this!
Step 1: npm install -g angular-cli

Step 2:Go to Directory

Step 3:ng serve

**Comment by Sheetalshinde71** [comment]
@KhizerRehan  thanks ,I will try

**Comment by Foxandxss** [comment]
This issue is getting out of hand. The original issue was hopefully fix.

**Comment by Sheetalshinde71** [comment]
Now I got this issue

![image](https://cloud.githubusercontent.com/assets/25894767/23356558/54760f72-fd00-11e6-88df-d542e0c2ea81.png)

**Comment by Neron-Liu** [comment]
Guys, I also went into this issue today.

And I have fixed it by steps:
1. change "rxjs" from "5.0.1" to "5.0.2"
2. npm install -g typescript
3. npm -g install concurrently
4. npm -g install lite-server

my versions are:
node - v6.10.0
npm - 3.10.10
tsc - Version 2.2.1

hope it helps. :)

**Comment by Sheetalshinde71** [comment]
thanks @Neron-Liu for your solution . I have already solved this issue

**Comment by jivan25** [comment]
![error](https://user-images.githubusercontent.com/25750411/31072396-94d19ae8-a71c-11e7-8b16-16ee61b7a5ef.png)
please help me I'm facing this error

**Comment by Foxandxss** [comment]
There is no task called "lite"

**Comment by jivan25** [comment]
It's automatically generated..

**Comment by Foxandxss** [comment]
uhm?

**Comment by jivan25** [comment]
Now I got this issue
![error](https://user-images.githubusercontent.com/25750411/31072657-9d2c5330-a71d-11e7-88bd-8198f2339bde.png)

**Comment by Foxandxss** [comment]
it is trying to create a new instance of your terminal or something and doesn't find it. I have no idea :/

**Comment by bhagatshubham1994** [comment]
PS D:\Angular2Projs\practise\myapp> npm start

> angular-quickstart@1.0.0 prestart D:\Angular2Projs\practise\
myapp
> npm run build

                                                                          al logging output above.
> angular-quickstart@1.0.0 build D:\Angular2Projs\practise\mya
pp
> tsc -p src/                                                             10-23T12_23_37_456Z-debug.log

src/app/components/user.component.ts(95,14): error TS7006: Par
ameter 'hobby' implicitly has an 'any' type.
src/app/components/user.component.ts(101,17): error TS7006: Pa
rameter 'i' implicitly has an 'any' type.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is lik
ely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shubham_bhagat\AppData\Roaming\npm-cache\_logs\2017-10-23T12_45_15_598Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shubham_bhagat\AppData\Roaming\npm-cache\_logs\2017-10-23T12_45_15_668Z-debug.log
PS D:\Angular2Projs\practise\myapp>

**Comment by bhagatshubham1994** [comment]
I have just restarted Visual Studio code and it's showing this error. This codes were working fine earlier but now it's showing these errors, please help.

**Comment by SarvagyaS** [comment]
I was having the same error. I realised that the problem was with npm install,
I went into the quickstart folder and executed npm install again, it worked !

**Comment by XerO00** [comment]
I have checked all syntax and they are correct still Im getting below error

~/myAngularApp $ npm start

> angular-firstapp@1.0.0 start /home/prasanna/myAngularApp
> tsc && concurrently"tsc-w""lite-server"

typescript/lib/lib.d.ts(1305,19): error TS1005: ',' expected.
typescript/lib/lib.d.ts(1305,33): error TS1005: ',' expected.
typescript/lib/lib.d.ts(1318,19): error TS1005: ',' expected.
typescript/lib/lib.d.ts(1318,33): error TS1005: ',' expected.
typescript/lib/lib.d.ts(1325,19): error TS1005: ',' expected.
typescript/lib/lib.d.ts(1344,19): error TS1005: ';' expected.
typescript/lib/lib.d.ts(1344,20): error TS1109: Expression expected.
typescript/lib/lib.d.ts(1344,21): error TS1109: Expression expected.
typescript/lib/lib.d.ts(1345,1): error TS1128: Declaration or statement expected.
typescript/lib/lib.d.ts(1371,24): error TS1005: ';' expected.
typescript/lib/lib.d.ts(1376,24): error TS1005: ';' expected.
typescript/lib/lib.d.ts(1381,25): error TS1005: ';' expected.
typescript/lib/lib.d.ts(1386,56): error TS1005: ';' expected.
typescript/lib/lib.d.ts(1386,90): error TS1005: ';' expected.
typescript/lib/lib.d.ts(1391,62): error TS1005: ';' expected.
typescript/lib/lib.d.ts(1391,75): error TS1109: Expression expected.
typescript/lib/lib.d.ts(1391,89): error TS1005: ';' expected.
typescript/lib/lib.d.ts(1391,91): error TS1128: Declaration or statement expected.
typescript/lib/lib.d.ts(1391,100): error TS1005: ';' expected.
typescript/lib/lib.d.ts(4364,29): error TS1005: ',' expected.
typescript/lib/lib.d.ts(7256,25): error TS1005: ',' expected.
typescript/lib/lib.d.ts(13636,37): error TS1005: ',' expected.
typescript/lib/lib.d.ts(13639,40): error TS1005: ',' expected.
typescript/lib/lib.d.ts(13839,37): error TS1005: ',' expected.
typescript/lib/lib.d.ts(13842,40): error TS1005: ',' expected.
typescript/lib/lib.d.ts(20419,27): error TS1005: ',' expected.
typescript/lib/lib.d.ts(20427,24): error TS1005: ',' expected.
typescript/lib/lib.d.ts(20453,12): error TS1005: ',' expected.
typescript/lib/lib.d.ts(20454,12): error TS1005: ',' expected.
typescript/lib/lib.d.ts(20455,12): error TS1005: ',' expected.
typescript/lib/lib.d.ts(20463,21): error TS1005: ',' expected.
typescript/lib/lib.d.ts(20495,12): error TS1005: ',' expected.
typescript/lib/lib.dom.d.ts(227,29): error TS1005: ',' expected.
typescript/lib/lib.dom.d.ts(3119,25): error TS1005: ',' expected.
typescript/lib/lib.dom.d.ts(9499,37): error TS1005: ',' expected.
typescript/lib/lib.dom.d.ts(9502,40): error TS1005: ',' expected.
typescript/lib/lib.dom.d.ts(9702,37): error TS1005: ',' expected.
typescript/lib/lib.dom.d.ts(9705,40): error TS1005: ',' expected.
typescript/lib/lib.es2016.full.d.ts(230,29): error TS1005: ',' expected.
typescript/lib/lib.es2016.full.d.ts(3122,25): error TS1005: ',' expected.
typescript/lib/lib.es2016.full.d.ts(9502,37): error TS1005: ',' expected.
typescript/lib/lib.es2016.full.d.ts(9505,40): error TS1005: ',' expected.
typescript/lib/lib.es2016.full.d.ts(9705,37): error TS1005: ',' expected.
typescript/lib/lib.es2016.full.d.ts(9708,40): error TS1005: ',' expected.
typescript/lib/lib.es2016.full.d.ts(16285,27): error TS1005: ',' expected.
typescript/lib/lib.es2016.full.d.ts(16293,24): error TS1005: ',' expected.
typescript/lib/lib.es2016.full.d.ts(16319,12): error TS1005: ',' expected.
typescript/lib/lib.es2016.full.d.ts(16320,12): error TS1005: ',' expected.
typescript/lib/lib.es2016.full.d.ts(16321,12): error TS1005: ',' expected.
typescript/lib/lib.es2016.full.d.ts(16329,21): error TS1005: ',' expected.
typescript/lib/lib.es2016.full.d.ts(16361,12): error TS1005: ',' expected.
typescript/lib/lib.es2017.full.d.ts(235,29): error TS1005: ',' expected.
typescript/lib/lib.es2017.full.d.ts(3127,25): error TS1005: ',' expected.
typescript/lib/lib.es2017.full.d.ts(9507,37): error TS1005: ',' expected.
typescript/lib/lib.es2017.full.d.ts(9510,40): error TS1005: ',' expected.
typescript/lib/lib.es2017.full.d.ts(9710,37): error TS1005: ',' expected.
typescript/lib/lib.es2017.full.d.ts(9713,40): error TS1005: ',' expected.
typescript/lib/lib.es2017.full.d.ts(16290,27): error TS1005: ',' expected.
typescript/lib/lib.es2017.full.d.ts(16298,24): error TS1005: ',' expected.
typescript/lib/lib.es2017.full.d.ts(16324,12): error TS1005: ',' expected.
typescript/lib/lib.es2017.full.d.ts(16325,12): error TS1005: ',' expected.
typescript/lib/lib.es2017.full.d.ts(16326,12): error TS1005: ',' expected.
typescript/lib/lib.es2017.full.d.ts(16334,21): error TS1005: ',' expected.
typescript/lib/lib.es2017.full.d.ts(16366,12): error TS1005: ',' expected.
typescript/lib/lib.es2018.full.d.ts(231,29): error TS1005: ',' expected.
typescript/lib/lib.es2018.full.d.ts(3123,25): error TS1005: ',' expected.
typescript/lib/lib.es2018.full.d.ts(9503,37): error TS1005: ',' expected.
typescript/lib/lib.es2018.full.d.ts(9506,40): error TS1005: ',' expected.
typescript/lib/lib.es2018.full.d.ts(9706,37): error TS1005: ',' expected.
typescript/lib/lib.es2018.full.d.ts(9709,40): error TS1005: ',' expected.
typescript/lib/lib.es2018.full.d.ts(16286,27): error TS1005: ',' expected.
typescript/lib/lib.es2018.full.d.ts(16294,24): error TS1005: ',' expected.
typescript/lib/lib.es2018.full.d.ts(16320,12): error TS1005: ',' expected.
typescript/lib/lib.es2018.full.d.ts(16321,12): error TS1005: ',' expected.
typescript/lib/lib.es2018.full.d.ts(16322,12): error TS1005: ',' expected.
typescript/lib/lib.es2018.full.d.ts(16330,21): error TS1005: ',' expected.
typescript/lib/lib.es2018.full.d.ts(16362,12): error TS1005: ',' expected.
typescript/lib/lib.es5.d.ts(1305,19): error TS1005: ',' expected.
typescript/lib/lib.es5.d.ts(1305,33): error TS1005: ',' expected.
typescript/lib/lib.es5.d.ts(1318,19): error TS1005: ',' expected.
typescript/lib/lib.es5.d.ts(1318,33): error TS1005: ',' expected.
typescript/lib/lib.es5.d.ts(1325,19): error TS1005: ',' expected.
typescript/lib/lib.es5.d.ts(1344,19): error TS1005: ';' expected.
typescript/lib/lib.es5.d.ts(1344,20): error TS1109: Expression expected.
typescript/lib/lib.es5.d.ts(1344,21): error TS1109: Expression expected.
typescript/lib/lib.es5.d.ts(1345,1): error TS1128: Declaration or statement expected.
typescript/lib/lib.es5.d.ts(1371,24): error TS1005: ';' expected.
typescript/lib/lib.es5.d.ts(1376,24): error TS1005: ';' expected.
typescript/lib/lib.es5.d.ts(1381,25): error TS1005: ';' expected.
typescript/lib/lib.es5.d.ts(1386,56): error TS1005: ';' expected.
typescript/lib/lib.es5.d.ts(1386,90): error TS1005: ';' expected.
typescript/lib/lib.es5.d.ts(1391,62): error TS1005: ';' expected.
typescript/lib/lib.es5.d.ts(1391,75): error TS1109: Expression expected.
typescript/lib/lib.es5.d.ts(1391,89): error TS1005: ';' expected.
typescript/lib/lib.es5.d.ts(1391,91): error TS1128: Declaration or statement expected.
typescript/lib/lib.es5.d.ts(1391,100): error TS1005: ';' expected.
typescript/lib/lib.es6.d.ts(1305,19): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(1305,33): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(1318,19): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(1318,33): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(1325,19): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(1344,19): error TS1005: ';' expected.
typescript/lib/lib.es6.d.ts(1344,20): error TS1109: Expression expected.
typescript/lib/lib.es6.d.ts(1344,21): error TS1109: Expression expected.
typescript/lib/lib.es6.d.ts(1345,1): error TS1128: Declaration or statement expected.
typescript/lib/lib.es6.d.ts(1371,24): error TS1005: ';' expected.
typescript/lib/lib.es6.d.ts(1376,24): error TS1005: ';' expected.
typescript/lib/lib.es6.d.ts(1381,25): error TS1005: ';' expected.
typescript/lib/lib.es6.d.ts(1386,56): error TS1005: ';' expected.
typescript/lib/lib.es6.d.ts(1386,90): error TS1005: ';' expected.
typescript/lib/lib.es6.d.ts(1391,62): error TS1005: ';' expected.
typescript/lib/lib.es6.d.ts(1391,75): error TS1109: Expression expected.
typescript/lib/lib.es6.d.ts(1391,89): error TS1005: ';' expected.
typescript/lib/lib.es6.d.ts(1391,91): error TS1128: Declaration or statement expected.
typescript/lib/lib.es6.d.ts(1391,100): error TS1005: ';' expected.
typescript/lib/lib.es6.d.ts(6075,29): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(8967,25): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(15347,37): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(15350,40): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(15550,37): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(15553,40): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(22130,27): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(22138,24): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(22164,12): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(22165,12): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(22166,12): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(22174,21): error TS1005: ',' expected.
typescript/lib/lib.es6.d.ts(22206,12): error TS1005: ',' expected.
typescript/lib/lib.esnext.array.d.ts(33,21): error TS1005: ',' expected.
typescript/lib/lib.esnext.array.d.ts(147,21): error TS1005: ',' expected.
typescript/lib/lib.esnext.full.d.ts(232,29): error TS1005: ',' expected.
typescript/lib/lib.esnext.full.d.ts(3124,25): error TS1005: ',' expected.
typescript/lib/lib.esnext.full.d.ts(9504,37): error TS1005: ',' expected.
typescript/lib/lib.esnext.full.d.ts(9507,40): error TS1005: ',' expected.
typescript/lib/lib.esnext.full.d.ts(9707,37): error TS1005: ',' expected.
typescript/lib/lib.esnext.full.d.ts(9710,40): error TS1005: ',' expected.
typescript/lib/lib.esnext.full.d.ts(16287,27): error TS1005: ',' expected.
typescript/lib/lib.esnext.full.d.ts(16295,24): error TS1005: ',' expected.
typescript/lib/lib.esnext.full.d.ts(16321,12): error TS1005: ',' expected.
typescript/lib/lib.esnext.full.d.ts(16322,12): error TS1005: ',' expected.
typescript/lib/lib.esnext.full.d.ts(16323,12): error TS1005: ',' expected.
typescript/lib/lib.esnext.full.d.ts(16331,21): error TS1005: ',' expected.
typescript/lib/lib.esnext.full.d.ts(16363,12): error TS1005: ',' expected.
typescript/lib/lib.scripthost.d.ts(227,27): error TS1005: ',' expected.
typescript/lib/lib.scripthost.d.ts(235,24): error TS1005: ',' expected.
typescript/lib/lib.scripthost.d.ts(261,12): error TS1005: ',' expected.
typescript/lib/lib.scripthost.d.ts(262,12): error TS1005: ',' expected.
typescript/lib/lib.scripthost.d.ts(263,12): error TS1005: ',' expected.
typescript/lib/lib.scripthost.d.ts(271,21): error TS1005: ',' expected.
typescript/lib/lib.scripthost.d.ts(303,12): error TS1005: ',' expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-firstapp@1.0.0 start: `tsc && concurrently"tsc-w""lite-server"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-firstapp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/prasanna/.npm/_logs/2018-03-11T11_00_04_341Z-debug.log
