### ISSUE TITLE
Double Compiling and Page Reloading with Each Code Change

### ISSUE THREAD

**Issue by grayskwrl149** [angular/quickstart#371]
So, I'm sitting here working on my Typescript Angular 2 project with your totally awesome quickstart, which is super helpful for someone new to Angular 2 and Typescript. I totally love it!

There's one minor peculiarity I see when `npm start` is running. It seems like every time I make a file change and save it, I get a recompile and a page reload, then another recompile and page reload.

**Comment by grayskwrl149** [comment]
EDIT: It seems to happen with changes to Typescript files, but not with changes to CSS files.

**Comment by vigamage** [comment]
I am also facing this

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
