### ISSUE TITLE
angular 2.4.0 and typings.json

### ISSUE THREAD

**Issue by faisalloe** [angular/quickstart#372]
i have been using angular v. 2.0.0 now i want to upgrade it to 2.4.0 sorry if i have being lazy to ask question here.

i have not found typings.json in this repo, v.2.4.0 does not require typings any more ?

**Comment by Foxandxss** [comment]
It is not that. Typescript 2.0 released a new way of typings. They are not npm packages (that you can see with the `@types/` on their names).

That is the official way since a couple of months back.
