### ISSUE TITLE
(SystemJS) XHR error (404 Not Found) in angularJS2

### ISSUE THREAD

**Issue by LijinDurairaj** [angular/quickstart#375]
I have put all the functions which i am using in a new folder and i am trying to access it by importing all the functions in the component in which i am using. I am able to import the functions, and i am able to even implement that function in the component, but when i run the app, i am getting an 404 file not found error.
dont know what went wrong

`import { pincodePattern, matchingPasswords, qualificationValidation, emailValidator } from '../functions/functions.validation'`

When i run it i get an error like this
`Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/functions/functions.validation`

**Comment by yuwangjuan** [comment]
me too

**Comment by mlukjanska** [comment]
Looks like the same issue as this one: https://github.com/angular/quickstart/issues/406

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
