### ISSUE TITLE
when i run npm test, a problem has occurred, Uncaught ReferenceError: jasmine is not defined

### ISSUE THREAD

**Issue by rogueRabbit** [angular/quickstart#378]
I want to do unit testing, I downloaded the latest angular2-quickstart code, then npm install all dependency packet, then npm test, a problem has occurred
![image](https://cloud.githubusercontent.com/assets/14859823/22725764/5bb54672-ee0a-11e6-8577-e6a734569ab3.png)
@wardbell please help me thanks

**Comment by rogueRabbit** [comment]
It's my own problem, already solved, thank you anyway

**Comment by justforuse** [comment]
@rogueRabbit ,Hi, I also face this problem, what's the solution? thanks.
