### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by casertillo** [angular/quickstart#380]
Hello, I download the app and did what it says on the tutorial. However, is not starting.  Attached you can find the debug log.  At console, the error says:

node_modules/@types/jasmine/index.d.ts(39,52): error TS1005: '=' expected.

[npm-debug.txt](https://github.com/angular/quickstart/files/768088/npm-debug.txt)

**Comment by Foxandxss** [comment]
Yeah, that jasmine types has a breaking change and we cannot support that yet. You need to lock it to the previous version for now. I have a PR standing to fix that.

**Comment by casertillo** [comment]
good to know. thanks!
