### ISSUE TITLE
Routing for Angular 2 Quickstart

### ISSUE THREAD

**Issue by DynamicRemo** [angular/quickstart#385]
Hi, i just downloaded [angular quickstart app][1] and followed the ReadMe. I have it up and running and can see AppComponent is rendered. 

Now i have created my custom module "CounterModule" containing my component "CounterComponent" as well as its related "CounterRoutingModule" but as soon as i links my module/component to AppRoutingModule (app-routing.module.ts), even the AppComponent stops rendering and starts to show Loading Text from my index.html. Please help me resolve this routing issue.

Here's my app-routing.module.ts

    import { NgModule } from '@angular/core';
	import { HttpModule } from '@angular/http';
	import { RouterModule, Routes } from '@angular/router';
	import { CounterComponent } from './mongodb/counter.component';

	const routes: Routes = [
	  { path: '', redirectTo: 'counter', pathMatch: 'full' },
	  { path: 'counter', component: CounterComponent },
	];

	@NgModule({
	  imports: [ RouterModule.forRoot(routes) ],
	  exports: [ RouterModule ]
	})

	export class AppRoutingModule {}

  [1]: https://github.com/angular/quickstart

**Comment by oscarfuquen** [comment]
Could you post the console log errors.

**Comment by DynamicRemo** [comment]
Thanks @oscarfuquen for your response but i resolved the issue on my own. That was my fault and was experiencing syntax error.

**Comment by ghost** [comment]
Hey, m facing same issue. Also attaching console log error. Kindly check.
![console](https://user-images.githubusercontent.com/16730858/34068193-49056c62-e25d-11e7-8d97-d851b5e2ceff.PNG)
