### ISSUE TITLE
npm start fails - tsc - angular2 quickstart

### ISSUE THREAD

**Issue by kmeda** [angular/quickstart#387]
I have the following error on running npm start from angular quick start.

All my quickstart clones ran okay _until I installed typescript globally_.
I can continue working by having two separate sessions below
     - $(npm bin)/tsc -p src/ -w
     - npm run serve

I am not sure what is causing this apart from the recent change which is installing typescript globally. 
[2017-02-22T16_49_40_111Z-debug.txt](https://github.com/angular/quickstart/files/794283/2017-02-22T16_49_40_111Z-debug.txt)
[2017-02-22T16_49_40_111Z-debug.txt](https://github.com/angular/quickstart/files/794285/2017-02-22T16_49_40_111Z-debug.txt)

But I can only run it using the above method.

00-angular2-website$ npm start

> angular-quickstart@1.0.0 prestart /Users/karthik/Desktop/Desktop/mean_stack/angular-2_projects/00-angular2-website
> npm run build

> angular-quickstart@1.0.0 build /Users/karthik/Desktop/Desktop/mean_stack/angular-2_projects/00-angular2-website
> $(npm bin)/tsc -p src/

src/app/app.component.spec.ts(7,1): error TS2304: Cannot find name 'describe'.
src/app/app.component.spec.ts(12,3): error TS2304: Cannot find name 'beforeEach'.
src/app/app.component.spec.ts(19,3): error TS2304: Cannot find name 'beforeEach'.
src/app/app.component.spec.ts(25,3): error TS2304: Cannot find name 'it'.
src/app/app.component.spec.ts(25,39): error TS2304: Cannot find name 'expect'.
src/app/app.component.spec.ts(27,3): error TS2304: Cannot find name 'it'.
src/app/app.component.spec.ts(30,5): error TS2304: Cannot find name 'expect'.

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/Users/karthik/.npm-packages/bin/npm" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 build: `$(npm bin)/tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script '$(npm bin)/tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     $(npm bin)/tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/karthik/.npm/_logs/2017-02-22T16_49_40_111Z-debug.log

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/Users/karthik/.npm-packages/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/karthik/.npm/_logs/2017-02-22T16_49_40_160Z-debug.log

**Comment by mahlijah** [comment]
hi kmeda, how did you resolve this issue?

**Comment by kmeda** [comment]
Hi mahlijah, I don't remember at the moment. I must've messed up something.
I tried this clone now and it runs fine.

**Comment by mahlijah** [comment]
thanks for the response kmeda.
