### ISSUE TITLE
Cannot find name 'module'

### ISSUE THREAD

**Issue by llhotka** [angular/quickstart#398]
In Atom editor, I tried to add the line
```
moduleId: module.id,
```
to a `@Component` decorator but the editor reports an error
```
Cannot find name 'module'
```
If I ignore it, everything seems to be fine and the example works, but it is annoying. Is there any way how to get rid of this problem? I realise it needn't be in the quickstart project.

**Comment by nikhilknoldus** [comment]
what is the error you are getting while running your app? Try restart your editor it may work or remove node-modules and re-install all modules.

**Comment by llhotka** [comment]
No error, the application runs just fine. I found a workaround in placing ``commonjs.d.ts`` file under ``src`` with this content:
```
declare var module: NodeModule;
```
so maybe this could be added to the repo.

**Comment by nikhilknoldus** [comment]
Thats nice, if you got the workaround, you can close this issue.
