### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by sushilpatil123** [angular/quickstart#399]
I am getting following error while running npm start command, Please can you help me with this issue?

npm start

> angular-quickstart@1.0.0 prestart C:\Users\kp\Documents\GitHub\my-proj
> npm run build

> angular-quickstart@1.0.0 build C:\Users\kp\Documents\GitHub\my-proj
> tsc -p src/

> angular-quickstart@1.0.0 start C:\Users\kp\Documents\GitHub\my-proj
> concurrently "npm run build:watch" "npm run serve"

 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1029:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:607:11)
     at run (bootstrap_node.js:425:7)
     at startup (bootstrap_node.js:146:9)
     at bootstrap_node.js:540:3
 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1029:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:607:11)
     at run (bootstrap_node.js:425:7)
     at startup (bootstrap_node.js:146:9)
     at bootstrap_node.js:540:3
[1] npm run serve exited with code -4058

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kp\\AppData\\Roaming\\npm\\node_modu
les\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.7.1
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "npm run serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'concurrently "npm run build:watch" "np
m run serve"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run build:watch" "npm run serve"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kp\AppData\Roaming\npm-cache\_logs\2017-03-03T04_51_26_531Z-debug.log

C:\Users\kp\Documents\GitHub\my-proj>npm run build:w
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kp\\AppData\\Roaming\\npm\\node_modu
les\\npm\\bin\\npm-cli.js" "run" "build:w"
npm ERR! node v7.7.1
npm ERR! npm  v4.3.0

npm ERR! missing script: build:w
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kp\AppData\Roaming\npm-cache\_logs\2017-03-03T04_52_28_442Z-debug.log

**Comment by nikhilknoldus** [comment]
Hi, try finding the package.json file in your root/home directory and remove that, than try running your project it may work.

**Comment by Magizhchi** [comment]
I am getting a similar issue, has this been resolved yet

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
