### ISSUE TITLE
Get Node Modules not working in VS2015 using package.json

### ISSUE THREAD

**Issue by venkatg-07it** [angular/quickstart#400]
Working Angular 2 in Visual Studio 2015, using NPM Configuration File, I used the restore package for Package.json. But, it doesn't get any thing. 

Visual 2015 is support for this or not, Any one help me on this area

**Comment by nikhilknoldus** [comment]
can you show me your package.json pointing to the error line, i use VS 1.8.1 and everything works expected.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)

**Comment by nikhilmundhra** [comment]
Error on restoring packages from package.json in quickstart-master downloaded from https://github.com/angular/quickstart. I am using it to run angular 2 in Visual Studio 2015. I have followed https://angular.io/guide/visual-studio-2015 for installation of quickstart files in visual studio 2015.

Error on restoring packages from package.json :-

npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated uws@9.14.0: stop using this version
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\supports-color-91851346\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\has-ansi-3495030d\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\strip-ansi-fbce9964\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\supports-color-91851346\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\has-ansi-3495030d\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\strip-ansi-fbce9964\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\supports-color-91851346\license'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\has-ansi-3495030d\license'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\strip-ansi-fbce9964\license'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\supports-color-91851346\readme.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\has-ansi-3495030d\readme.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\strip-ansi-fbce9964\readme.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\ua-parser-js-568c885b\src\ua-parser.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\readable-stream-dab5ec6f\lib\_stream_duplex.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\tmp-79cf1820\lib\tmp.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\tough-cookie-4dbedf2b\lib\cookie.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\readable-stream-dab5ec6f\lib\_stream_passthrough.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\readable-stream-dab5ec6f\lib\_stream_readable.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\@angular\http-cc877983\src\http_module.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\@angular\platform-browser-c62ac93c\@angular\platform-browser\animations.es5.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\nikhil.mundhra\Documents\Visual Studio 2015\Projects\InvMgmtApp\InvMgmtApp\node_modules\.staging\when-81a1c626\unfold\list.js'
npm ERR! code E403
npm ERR! 403 Forbidden: selenium-webdriver@2.53.3
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nikhil.mundhra\AppData\Roaming\npm-cache\_logs\2018-06-18T12_53_33_022Z-debug.log

====npm command completed with exit code 1====


What should I do?
