### ISSUE TITLE
Tests don't run

### ISSUE THREAD

**Issue by roblouie** [angular/quickstart#402]
I did only three things to get this issue:

1. Clone this repo
2. Run `npm install` from the project root
3. Ran `npm run test:once` from the project root

That results in a 404 error from systemjs, evidently because the proxy setting in the karma config just doesn't work?
```
Error: XHR error loading http://localhost:9877/base/src/node_modules/@angular/core/bundles/core-testing.umd.js
        Error loading http://localhost:9877/base/src/node_modules/@angular/core/bundles/core-testing.umd.js', originalStack: 'Error: (SystemJS) XHR error loading http://localhost:9877/base/src/node_modules/@angular/core/bundles/core-testing.umd.js
        Error: XHR error loading http://localhost:9877/base/src/node_modules/@angular/core/bundles/core-testing.umd.js
        Error loading http://localhost:9877/base/src/node_modules/@angular/core/bundles/core-testing.umd.js', zoneAwareStack: 'Error: (SystemJS) XHR error loading http://localhost:9877/base/src/node_modules/@angular/core/bundles/core-testing.umd.js
```

Not really much of a "quick start" when you can't run the tests...

**Comment by roblouie** [comment]
Just found an ugly workaround, but at least it works I guess, I hard coded the proxy to the server url:

```
proxies: {
  // required for modules fetched by SystemJS
  '/base/src/node_modules/': 'http://localhost:9877/base/node_modules'
},
```

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
