### ISSUE TITLE
GET 404 (Not Found) error - Routing doesn't work

### ISSUE THREAD

**Issue by mcichecki** [angular/quickstart#406]
So I've made an app which was working great but then I've figured out that menubar on top with two links would be ok so I've followed this tutorial: https://angular.io/docs/ts/latest/guide/router.html but something is wrong. I can't get it working and there is this error:
GET http://localhost:3000/about/about.component 404 (Not Found)
GET http://localhost:3000/home/home.component 404 (Not Found)

VSCode does not show any problems.

main file structure:

src
├───about
│   ├───about.component.html
│   ├───about.component.ts (and other .js and .js.map files)
├───app
│   ├───app.component.ts
│   ├───app.module.ts (and other .js and .js.map files...)
├───home
│   ├───home.component.html
│   ├───home.component.ts (other less relevant files)

in index.html I've added <base href="/">

app.module.ts:
```
import { RouterModule, Routes } from '@angular/router'
...
import { AppComponent }  from './app.component';
import { AboutComponent } from './../about/about.component';
import { HomeComponent } from './../home/home.component';

const appRoutes: Routes = [
  {
    path: '/home/home', //I've also tried home/home, home and so on
    component: HomeComponent,
  },
  {
    path: '/about/about',
    component: AboutComponent,
  },
]

@NgModule({
    imports: [
    BrowserModule,
    CommonModule,
    FormsModule,
    HttpModule,
    ReactiveFormsModule,
    RouterModule.forRoot(appRoutes),
    ....],
      declarations: [ AppComponent, AboutComponent, HomeComponent ],
    ....
```

app.component.ts:
```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
    <nav>
      <a routerLink="/home" routerLinkActive="active">Home</a>
      <a routerLink="/about" routerLinkActive="active">About</a>
    </nav>
    <router-outlet></router-outlet>
  `
})

export class AppComponent {

}
```

about.component.ts:
```
import { Component } from '@angular/core'

@Component({
  selector: 'about',
  moduleId: module.id,
  template: `
  <p>ABOUT</p>
  `,
})

export class AboutComponent {
  
}
```

home.component.ts:
```
// imports

@Component({
  selector: 'home',
  moduleId: module.id,
  templateUrl: 'home.component.html',
  styleUrls: ['home.css'],
  providers: [HomeService],
})
export class HomeComponent {
// ...
}
```

The problem is probably connected to the routerLink but I've tried couple of different options and it didn't work.

**Comment by nikhilknoldus** [comment]
Hi @mcichecki do it like this :
app.routes.ts

`import { ModuleWithProviders } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { AppComponent } from './app.component';
import { AboutComponent } from './about/about.component';
import { ServicesComponent } from './services/services.component';
import { Notfound404Component } from './notfound404/notfound404.component';

export const router: Routes = [
{path: '', redirectTo: 'app', pathMatch: 'full'},
{path: 'about', component: AboutComponent },
{path: 'services', component: ServicesComponent},
{path: '**', component: Notfound404Component  }
];


export const routes: ModuleWithProviders = RouterModule.forRoot(router)`

app.module.ts

`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { routes } from './app.routes';
import { AppComponent } from './app.component';
import { AboutComponent } from './about/about.component';
import { ServicesComponent } from './services/services.component';
import { Notfound404Component } from './notfound404/notfound404.component';

@NgModule({
  declarations: [
    AppComponent,
    AboutComponent,
    ServicesComponent,
    Notfound404Component
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    routes
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
`

app.component.html

> <style>
li{
  margin:15px;
}
</style>
<pre>
 ul style="display: inline-flex;
    background-color: darkorange;">
  li 
    <a routerLink="app">Home</a>
  /li 
 

AND SO ON ...
<router-outlet></router-outlet>

and it will work fine.

**Comment by mlukjanska** [comment]
I found this explanation quite helpful about the topic: [Component-relative paths in Angular](https://blog.thoughtram.io/angular/2016/06/08/component-relative-paths-in-angular-2.html)

**Comment by Sanal05** [comment]
I think it will be better if you post this question at StackOverflow. Because this seems a coding issue.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
