### ISSUE TITLE
The seed gives error in Internet Explorer

### ISSUE THREAD

**Issue by soyiatgit** [angular/quickstart#411]
I just tried cloning the seed and installed all npm dependencies. Upon doing npm start, the application launches at port 3000. The application works fine on Chrome, however on IE the "Hello Angular" text doesn't appear. Rather the page just shows "Loading AppComponent content here...".

I get the following error in IE console:

(Error: (SystemJS) Invalid character
	SyntaxError: Invalid character
	   at ZoneDelegate.prototype.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:332:13)
	   at Zone.prototype.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:126:17)
	   at Anonymous function (http://localhost:3000/node_modules/zone.js/dist/zone.js:713:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:365:13)
	   at Zone.prototype.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:166:21)
	Evaluating http://localhost:3000/systemjs-angular-loader.js
	Error loading http://localhost:3000/systemjs-angular-loader.js
	Error loading http://localhost:3000/app/app.module.js as "./app/app.module" from http://localhost:3000/main.js)

As IE is my target browser, I have to develop app only on IE. Can someone suggest if I have been doing something wrong here. I have seen few threads which shows the issue in earlier beta versions and say that its resolved now. But I just cloned the seed and still face the issue.

**Comment by Foxandxss** [comment]
Thanks, I can reproduce it. As soon as I clear my queue I will take a peek.

The error is not related to anything Angular, it is more of a systemjs loader I put that doesn't seem to like IE.

**Comment by soyiatgit** [comment]
Thanks for the acknowledgement. Looking forward to the resolution.

Meanwhile, will try to update you in case I come across any findings.

Thanks
Saurabh

**Comment by mattm86** [comment]
This plunkr has a systemjs-angular-loader.js file that loads both ie and chrome.

https://angular.io/resources/live-examples/reactive-forms/ts/final.eplnkr.html

**Comment by davidnordstedt** [comment]
I've been struggling with this exact same thing for the past week or so.  I suspect it has something to do with the fact IE 11 doesn't support ES6 template literals, but I haven't gotten it to work yet.  Things seem to start going bad in systemjs-angular-loader.js.

**Comment by davidnordstedt** [comment]
I went to jump in a fix this in my app yesterday and I see someone already put a fix in for it I just didn't notice it before. 
[https://github.com/angular/quickstart/commit/456b849692ade45c4f58fc80c65ee23c99dc9190](url)

**Comment by koolkravi** [comment]
I am facing similar issue with Angular 4 Quick start. It is not working in i.e. 10 browser. i am developing an application for target browser i.e.

Ref: https://angular.io/docs/ts/latest/guide/setup.html
sample code: https://angular.io/resources/zips/quickstart/quickstart.zip

can some one help to fix this issue?
error trace from ie console as below.
Error: (SystemJS) Expected ';'
	SyntaxError: Expected ';'
	   at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:363:13)
	   at run (http://localhost:3000/node_modules/zone.js/dist/zone.js:125:17)
	   at Anonymous function (http://localhost:3000/node_modules/zone.js/dist/zone.js:760:17)
	   at invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:396:13)
	   at runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:165:21)
	Evaluating http://localhost:3000/systemjs-angular-loader.js
	Error loading http://localhost:3000/systemjs-angular-loader.js
	Error loading http://localhost:3000/js/app/app.module.js as "./app/app.module" from http://localhost:3000/js/main.js

**Comment by soyiatgit** [comment]
Did you try generating the project from the angular- cli instead.

**Comment by koolkravi** [comment]
Using angular cli also throw different error.
Below steps I have done to create a sample project
step1: npm install -g @angular/cli@latest
step2:   
ng new my-project
cd new-project
ng serve
step 3: open http://localhost:4200/
------------------------

Below error comes in I.E. 10 console.
----------------
SCRIPT5007: Unable to get property 'apply' of undefined or null reference 
vendor.ea154689718a347004ac.bundle.js, line 8 character 769
------------

**Comment by koolkravi** [comment]
[...](https://github.com/angular/quickstart/issues/411#issuecomment-299542838)
working fine in i.e. 10 browser with angular cli after after i adjusted polyfills.ts

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
