### ISSUE TITLE
http/bundles/http.umd.js/testing - Error: (SystemJS) XHR error (404 Not Found)

### ISSUE THREAD

**Issue by mlukjanska** [angular/quickstart#415]
If trying to use the MockBackend, MockConnection from '@angular/http/testing'; without any modifications to the default systemjs.config.js configuration, it will give Console errors in a browser and might prevent starting the app:
![2017-03-26 20_34_20-new notification](https://cloud.githubusercontent.com/assets/4057482/24334583/887b4e08-1264-11e7-8073-26ae3f3da982.png)

This can be resolved by adding the following line into systemjs.config.js to angular bundles:
```
// angular bundles
'@angular/http/testing': 'npm:@angular/http/bundles/http-testing.umd.js',
```

**Comment by rimbakasimba** [comment]
works great. unfortunately the various tutorials miss out this configuration step :)

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
