### ISSUE TITLE
traceur 404 not found

### ISSUE THREAD

**Issue by mortezadalil** [angular/quickstart#417]
Quick start angular 4 project run with npm start but when I moved files into asp.net mvc 5 project this error appeared : 

GET http://localhost:47917/traceur 404 (Not Found)
scheduleTask @ zone.js:1990
ZoneDelegate.scheduleTask @ zone.js:384
Zone.scheduleTask @ zone.js:209
Zone.scheduleMacroTask @ zone.js:232
(anonymous) @ zone.js:2014
.....
![image](https://cloud.githubusercontent.com/assets/15077932/24396755/8ef52834-13b9-11e7-8a71-2ed379995366.png)

**Comment by mortezadalil** [comment]
Oh! changing "es2015" to "commonjs" inside tsconfig.json solved my problem.
I hope your problem same as my problem because I don't know why traceur error related to many different problems! 
See [here](http://stackoverflow.com/questions/37022526/angular-2-404-traceur-not-found)

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)

**Comment by lcundiff** [comment]
@Foxandxss Angular setup tutorial is still referencing this page: https://angular.io/guide/upgrade-setup

When I finished this tutorial, I also came across this error. Is there a way to inform Angular that their documents are not updated? It will help people avoid falling into a time sink in setting up this repository.

**Comment by Foxandxss** [comment]
@lcundiff That is absolutely right. That is weird. Let me ping the team. Thanks
