### ISSUE TITLE
error TS2307: Cannot find module './observable/IfObservable'.

### ISSUE THREAD

**Issue by DocGreenRob** [angular/quickstart#419]
So, trying to install Angular 2 and went through the following:

`npm install -g angular-cli`

In GitBash

`git clone https://github.com/angular/quickstart angular-2-proj`

`cd angular-2-proj`

`npm install`

`npm start`

Got this error:

angular-quickstart@1.0.0 prestart C:\_Sandbox\_git\angular-2-proj
npm run build
angular-quickstart@1.0.0 build C:\_Sandbox\_git\angular-2-proj
tsc -p src/
'tsc' is not recognized as an internal or external command,
operable program or batch file.npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8                                                                                                                                                                                               6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 build: tsc -p src/
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! This is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.npm ERR! Please include the following file with any support request:
npm ERR!     C:\_Sandbox\_git\angular-2-proj\npm-debug.lognpm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8                                                                                                                                                                                               6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 prestart: npm run build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! This is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.npm ERR! Please include the following file with any support request:
npm ERR!     C:\_Sandbox\_git\angular-2-proj\npm-debug.log

Then I, according to this post http://stackoverflow.com/questions/12685995/cant-find-typescript-compiler-command-tsc-is-not-valid tried:

`npm install -g typescript`

then

`npm start`

and get

npm start
angular-quickstart@1.0.0 prestart C:\_Sandbox\_git\angular-2-proj
npm run build
angular-quickstart@1.0.0 build C:\_Sandbox\_git\angular-2-proj
tsc -p src/
node_modules/rxjs/Observable.d.ts(5,30): error TS2307: Cannot find module './observable/IfObservable'.
node_modules/rxjs/Observable.d.ts(6,33): error TS2307: Cannot find module './observable/ErrorObservable'.npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 build: tsc -p src/
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! This is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.npm ERR! Please include the following file with any support request:
npm ERR!     C:\_Sandbox\_git\angular-2-proj\npm-debug.lognpm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 prestart: npm run build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! This is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.npm ERR! Please include the following file with any support request:
npm ERR!     C:\_Sandbox\_git\angular-2-proj\npm-debug.log

Lastly I did:

`npm install -g rxjs`

`npm start`

same error!

**Comment by maxguzeng** [comment]
I have the same problem. 

ERROR in /home/dev/frontend/src/app/shared/form/login/login.form.component.ts (10,31): Cannot find module 'rxjs/Observable/TimerObservable'.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
