### ISSUE TITLE
Local package.json exists, but node_modules missing

### ISSUE THREAD

**Issue by Muzaffar08** [angular/quickstart#420]
> angular-quickstart@1.0.0 prestart C:\Users\muzaffar\Desktop\Mob App Test\Angul                                                                                                                arJS
> npm run build

> angular-quickstart@1.0.0 build C:\Users\muzaffar\Desktop\Mob App Test\AngularJ                                                                                                                S
> tsc -p src/

error TS5023: Unknown option 'p'
Use the '--help' flag to see options.
error TS5007: Cannot resolve referenced file: 'src/'.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart pa                                                                                                                ckage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in                                                                                                                stall?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\muzaffar\AppData\Roaming\npm-cache\_logs\2017-03-31T12_07_                                                                                                                22_542Z-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart pa                                                                                                                ckage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in                                                                                                                stall?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\muzaffar\AppData\Roaming\npm-cache\_logs\2017-03-31T12_07_                                                                                                                22_565Z-debug.log

**Comment by MichaelDeBoey** [comment]
You first need to run `npm install` before you can build the package :-)

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)

**Comment by HJLLL** [comment]
Hello Foxandxss, I just started to learn, I want to ask you about the difference between the warehouse and vode. I met you the first time I came here. I hope you can take me to study.

**Comment by ismardoi2001** [comment]
nice

**Comment by vikram-java** [comment]
first ' npm install'
then 'npm start '

**Comment by Aryan-Oswal** [comment]
- ,\

**Comment by kyeltech** [comment]
npm install is not working @vikram-java

**Comment by vikram-java** [comment]
firstly install node.js then run npm install and npm start

**Comment by VU-THI-LINH123** [comment]
### _fjfkjdskfjs****_
