### ISSUE TITLE
Delete non-essential files not wotking on windows 10

### ISSUE THREAD

**Issue by ak274** [angular/quickstart#421]
When I'm trying to run commands for windows following error occurred .

`bash: syntax error near unexpected token %i`

**Comment by ak274** [comment]
Just realized, I was trying to run those commands on Bash. Ran them on command prompt and works fine.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
