### ISSUE TITLE
xhr error

### ISSUE THREAD

**Issue by RostyslavSh** [angular/quickstart#424]
I`ve cloned project and configured base path in index.html. No custom code. 
This error keeps appearing.
![issue](https://cloud.githubusercontent.com/assets/18091196/24599195/b56c157a-1857-11e7-8756-a75da68abb32.png)

**Comment by AnyaLemon** [comment]
I'm getting the same error. Were you ever able to solve this?

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
