### ISSUE TITLE
(SystemJS) Block-scoped declarations

### ISSUE THREAD

**Issue by pra7eek** [angular/quickstart#425]
Hi,

I'm getting following error while running the quickstart project in google chrome:

> Error: (SystemJS) Block-scoped declarations (let, const, function, class) not yet supported outside strict mode(…)

This error is occurring due to the following line
`System.import('main.js').catch(function(err){ console.error(err); });`

I'm running ubuntu 14.04. The weird part is that the project is running pretty well in mozilla but not in chrome. Please help.

**Comment by seasoncc** [comment]
i also have the exact problem happened on lower chrome version just like 44 or 45, but fine on the recent Chrome version. PS, angular 4 used. Please help.
![screen](https://cloud.githubusercontent.com/assets/3510004/25789568/10429ad0-33e4-11e7-8634-0cf7890cbc68.JPG)

**Comment by hinok** [comment]
Add `'use strict';` at the beginning of [systemjs-angular-loader.js](https://github.com/angular/quickstart/blob/87ad8f5769c52a623b8e7df679b3960f2aa50e63/src/systemjs-angular-loader.js#L1)

So this file should look like:

```
'use strict'; // This line is missing and fixes problem

var templateUrlRegex = /templateUrl\s*:(\s*['"`](.*?)['"`]\s*)/gm;
var stylesRegex = /styleUrls *:(\s*\[[^\]]*?\])/g;
var stringRegex = /(['`"])((?:[^\\]\\\1|.)*?)\1/g;

// rest of the code
```

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
