### ISSUE TITLE
how can i change the port

### ISSUE THREAD

**Issue by laurencefass** [angular/quickstart#429]
im new to npm... i want to change the port but cant find where to do it. if ive already npm installed, do i need to reinstall to change the port, or can i use npm magic to change the port? thanks.

**Comment by landonp1203** [comment]
Quick Google Search came up with this:
http://stackoverflow.com/a/35441172/4272115

Hope it helps!

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
