### ISSUE TITLE
Error: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by barretodavid** [angular/quickstart#43]
After doing a clean install of this repo and adding the Router to the app with:

```javascript
import {bootstrap}    from 'angular2/platform/browser';
import {AppComponent} from './app.component';
import {ROUTER_PROVIDERS} from 'angular2/router';

bootstrap(AppComponent, [ROUTER_PROVIDERS]);
```

I'm getting the following error in the browser console (Chrome 49 - OS X 10 El Capitan):

```
Error: SyntaxError: Unexpected token <(…)   angular2-polyfills.js:322
ZoneDelegate.invoke @ angular2-polyfills.js:322
Zone.run @ angular2-polyfills.js:218
(anonymous function) @ angular2-polyfills.js:567
ZoneDelegate.invokeTask @ angular2-polyfills.js:355
Zone.runTask @ angular2-polyfills.js:254
drainMicroTaskQueue @ angular2-polyfills.js:473
ZoneTask.invoke @ angular2-polyfills.js:425
```

**Comment by Foxandxss** [comment]
The current version of this repository is sadly broken. We are waiting to beta .12 to fix this issues.

So let's wait for that update and see if that fixes your issue or not.

**Comment by Foxandxss** [comment]
Could you update the repo and try now please?

**Comment by barretodavid** [comment]
I downloaded again this app and followed the same procedure to add the router and I'm getting a similar error message:

```
Error: SyntaxError: Unexpected token <(…)   angular2-polyfills.js:332
ZoneDelegate.invoke @ angular2-polyfills.js:332
```

**Comment by Foxandxss** [comment]
You need to include the router after you include angular:

```
<script src="node_modules/angular2/bundles/angular2.dev.js"></script>
<script src="node_modules/angular2/bundles/router.dev.js"></script>
```

**Comment by wardbell** [comment]
Just tried with beta.13 and it works fine.
As @Foxandxss observes, you must add the **independent router library** to your `index.html`.

Please note that this is not a support site. Closing because there is no issue.
