### ISSUE TITLE
"OS/X" instructions are valid for all unix-like operating systems

### ISSUE THREAD

**Issue by Keziolio** [angular/quickstart#430]
So in the readme and angular docs you should rename "OS/X (bash)" and put only "bash" or "posix", "unix-like", etc.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
