### ISSUE TITLE
Hero search component URL bug in tutorial

### ISSUE THREAD

**Issue by chautsunman** [angular/quickstart#432]
In the final version of `HeroSearchComponent`, `moduleId` is not set for the component, so there is an error in the relative paths of `templaterUrl` and `styleUrls`.

Either `moduleId` should be set to `module.id`, or it should use the absolute paths `app/hero-service.component.html` and `app/hero-service.component.css`.

[Tutorial](https://angular.io/docs/ts/latest/tutorial/toh-pt6.html)

**Comment by Foxandxss** [comment]
No. We removed the moduleId needs with a plugin which sits on the quickstart.

We will explain it better this next week so no one gets confused anymore.
