### ISSUE TITLE
Getting compile time issue, Cannot find name 'describe'

### ISSUE THREAD

**Issue by chayanmaji** [angular/quickstart#434]
I setup a new angular2 project as mentioned in the https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html. I followed every steps mentioned in the link. But I am getting below errors.

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2304	Cannot find name 'describe'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\e2e\app.e2e-spec.ts	3	Active
Error		"tsc.exe" exited with code 1.	AngularTwo			
Error	TS2304	Cannot find name 'beforeEach'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\e2e\app.e2e-spec.ts	7	Active
Error	TS2304	Cannot find name 'it'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\e2e\app.e2e-spec.ts	11	Active
Error	TS2304	Cannot find name 'expect'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\e2e\app.e2e-spec.ts	12	Active
Error	TS2339	Property 'getText' does not exist on type 'ElementFinder'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\e2e\app.e2e-spec.ts	12	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\browser.d.ts	1	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\browser.d.ts	1	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\browser.d.ts	2	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\browser.d.ts	2	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\debugger.d.ts	1	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\debugger.d.ts	1	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\debugger.d.ts	2	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\debugger.d.ts	2	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\element.d.ts	1	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\element.d.ts	1	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\element.d.ts	2	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\element.d.ts	2	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\index.d.ts	6	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\index.d.ts	6	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\locators.d.ts	1	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\locators.d.ts	1	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\locators.d.ts	2	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\locators.d.ts	2	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\plugins.d.ts	1	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\plugins.d.ts	1	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\plugins.d.ts	2	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\plugins.d.ts	2	Active
Error	TS2307	Cannot find module 'q'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\plugins.d.ts	3	Active
Error	TS2307	Cannot find module 'q'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\plugins.d.ts	3	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\plugins.d.ts	4	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\plugins.d.ts	4	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\ptor.d.ts	1	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\ptor.d.ts	1	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\ptor.d.ts	2	Active
Error	TS2307	Cannot find module 'selenium-webdriver'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\ptor.d.ts	2	Active
Error	TS2307	Cannot find module 'selenium-webdriver/chrome'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\ptor.d.ts	3	Active
Error	TS2307	Cannot find module 'selenium-webdriver/chrome'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\ptor.d.ts	3	Active
Error	TS2307	Cannot find module 'selenium-webdriver/firefox'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\ptor.d.ts	4	Active
Error	TS2307	Cannot find module 'selenium-webdriver/firefox'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\ptor.d.ts	4	Active
Error	TS2307	Cannot find module 'selenium-webdriver/http'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\ptor.d.ts	5	Active
Error	TS2307	Cannot find module 'selenium-webdriver/http'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\ptor.d.ts	5	Active
Error	TS2307	Cannot find module 'selenium-webdriver/remote'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\ptor.d.ts	6	Active
Error	TS2307	Cannot find module 'selenium-webdriver/remote'.	TypeScript Virtual Projects	D:\Chayan\AngularTwo\AngularTwo\node_modules\protractor\built\ptor.d.ts	6	Active

**Comment by DarthNyan** [comment]
I have the same problem

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
