### ISSUE TITLE
Safari in iPad mini (iOS 9.3.1) throws exception when loading app

### ISSUE THREAD

**Issue by calvino66** [angular/quickstart#437]
My iphone/iPad are fine with the angular app which are running iOS10.
But my iPad mini was not working with the same angular app. The error thrown from loading main.js:
Error: (SystemJS) Unexpected identifier 'resolvedUrl' eval@[native code] invoke@...

After an hour of investigation, i found that the error can be bypassed if i changed "let" to "var" in  the file "systemjs-angular-loader.js" line 22:
  let resolvedUrl = url;

Have a quick search in https://kangax.github.io/compat-table/es6/#let_basic_support_(strict_mode)
It is found that not all browsers support the use of "let", including iOS 9.

as it is not a big issue changing let to var in this js file. i suggest make this change.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
