### ISSUE TITLE
Reload Twice when start up at the first time.

### ISSUE THREAD

**Issue by SouengKimmeng** [angular/quickstart#438]
I always noted that when I run npm start it will start the project then in the first time it reload twice. Do anyone have any idea or that problem? thanks.

**Comment by brandonkoch6** [comment]
I experience this same issue.  It does seem very odd.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
