### ISSUE TITLE
System.register-Issue setting up the quickstart

### ISSUE THREAD

**Issue by SilverJan** [angular/quickstart#44]
Hi there,

not sure if this is the right place to ask but I am facing this issue while setting up the quickstart tutorial of Angular 2. 

I am using gulp for tsc, bundling and hosting (gulp-)webserver.

My tsc-gulp-task in the gulpfile.js looks like that:

    var gulpTypescript = require('gulp-typescript');
    var tscConfig = require('./tsconfig.json');

    gulp.task('tsc', function () {
        return gulp.src('src/**/*.ts')
            .pipe(gulpTypescript(tscConfig.compilerOptions))
            .pipe(gulp.dest('/gen'));
    });

This task generates two .js-Files which I am concatenating with gulp-bundle-assets to the final main.js. This file is located in build/lib/

My final bundled main.js looks like that (shortened):

    System.register(['angular2/core'], function(exports_1, context_1) {
        var __moduleName = context_1 && context_1.id;
        ..
    }};
    System.register(['angular2/platform/browser', './app.component'], function(exports_1, context_1) {
        var __moduleName = context_1 && context_1.id;    
        ..
    }};

The chrome console gives me the following error:

> Error: Multiple anonymous System.register calls in module https://localhost:8000/lib/main.js. If loading a bundle, ensure all the System.register calls are named.

So actually I don't know what is wrong with the main.js. Maybe someone else does?

**Comment by Foxandxss** [comment]
This project is a mirror for what you can build on angular.io. A simpler and easier way to get started on the tutorials.

That being said, this is not the best channel to get this kind of support.

Thank you :)

**Comment by wardbell** [comment]
Sorry. I'm closing because what you're trying to do is out of scope for this repo. Not saying it's wrong. Just can't handle it here. Thanks.
