### ISSUE TITLE
Typescript output directory

### ISSUE THREAD

**Issue by aleixsuau** [angular/quickstart#446]
Hi!
It would be nice to change the output directory of the tsconfig.json (outDir) to a different folder, right now it gets messy really fast.
In my case I have changed:

1. tsconfig.json >> "outDir": "dist"
2. systemjs.config.js >> map: {
      // our app is within the app folder
      'app': 'dist',
      ... }
3. index.html >> System.import('dist/main.js').catch(function(err){ console.error(err); });

And it seems to work fine.  More info and alternatives: http://stackoverflow.com/questions/34684527/separate-angular2-typescript-files-and-javascript-files-into-different-folders/40694657#40694657

Thanks!

**Comment by brandonkoch6** [comment]
When I do this and use a templateUrl in the app component such as:

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

It does not seem to work.  It gets a 404 when it tries to get /dist/app/app.component.html

How did you modify it to see your template HTML and CSS files?

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
