### ISSUE TITLE
i am getting error

### ISSUE THREAD

**Issue by paramdotnet** [angular/quickstart#447]
PS D:\My Learnings\Angular\master> npm start

> angular-quickstart@1.0.0 prestart D:\My Learnings\Angular\master
> npm run build

> angular-quickstart@1.0.0 build D:\My Learnings\Angular\master
> tsc -p src/

src/app/app.component.spec.ts(3,50): error TS2307: Cannot find module '@angular/core/testing'.
src/app/app.component.spec.ts(4,30): error TS2307: Cannot find module '@angular/platform-browser'.
src/app/app.component.spec.ts(5,30): error TS2307: Cannot find module '@angular/core'.
src/app/app.component.spec.ts(7,1): error TS2304: Cannot find name 'describe'.
src/app/app.component.spec.ts(12,3): error TS2304: Cannot find name 'beforeEach'.
src/app/app.component.spec.ts(19,3): error TS2304: Cannot find name 'beforeEach'.
src/app/app.component.spec.ts(25,3): error TS2304: Cannot find name 'it'.
src/app/app.component.spec.ts(25,39): error TS2304: Cannot find name 'expect'.
src/app/app.component.spec.ts(27,3): error TS2304: Cannot find name 'it'.
src/app/app.component.spec.ts(30,5): error TS2304: Cannot find name 'expect'.
src/app/app.component.ts(1,27): error TS2307: Cannot find module '@angular/core'.
src/app/app.module.ts(1,31): error TS2307: Cannot find module '@angular/core'.
src/app/app.module.ts(2,31): error TS2307: Cannot find module '@angular/platform-browser'.
src/main.ts(1,40): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\saura\AppData\Roaming\npm-cache\_logs\2017-05-05T00_14_12_515Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\saura\AppData\Roaming\npm-cache\_logs\2017-05-05T00_14_12_650Z-debug.log
PS D:\My Learnings\Angular\master>

**Comment by RuslanBehun** [comment]
the same stuff, something happens with this stuff

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
