### ISSUE TITLE
Getting error when start

### ISSUE THREAD

**Issue by juggleru** [angular/quickstart#450]
Mac OS X 10.11.6
node v6.10.3
npm 3.10.10

```
$ npm start

> angular-quickstart@1.0.0 prestart /Users/juggle/webwork/my-proj
> npm run build


> angular-quickstart@1.0.0 build /Users/juggle/webwork/my-proj
> tsc -p src/

../../node_modules/@types/lodash/index.d.ts(12847,29): error TS2304: Cannot find name 'object'.
../../node_modules/@types/lodash/index.d.ts(19587,15): error TS2428: All declarations of 'WeakMap' must have identical type parameters.
../../node_modules/@types/lodash/index.d.ts(19587,33): error TS2304: Cannot find name 'object'.

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/juggle/webwork/my-proj/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/juggle/webwork/my-proj/npm-debug.log
```

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-quickstart@1.0.0~prestart: angular-quickstart@1.0.0
6 verbose lifecycle angular-quickstart@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle angular-quickstart@1.0.0~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/juggle/webwork/my-proj/node_modules/.bin:/Users/juggle/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/juggle/Library/Android/sdk:/opt/X11/bin:/usr/local/go/bin:/Users/juggle/Library/Android/sdk/tools:/usr/local/Cellar/yarn/0.16.1/bin
8 verbose lifecycle angular-quickstart@1.0.0~prestart: CWD: /Users/juggle/webwork/my-proj
9 silly lifecycle angular-quickstart@1.0.0~prestart: Args: [ '-c', 'npm run build' ]
10 silly lifecycle angular-quickstart@1.0.0~prestart: Returned: code: 1  signal: null
11 info lifecycle angular-quickstart@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: angular-quickstart@1.0.0 prestart: `npm run build`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:886:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid angular-quickstart@1.0.0
14 verbose cwd /Users/juggle/webwork/my-proj
15 error Darwin 15.6.0
16 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 error node v6.10.3
18 error npm  v3.10.10
19 error code ELIFECYCLE
20 error angular-quickstart@1.0.0 prestart: `npm run build`
20 error Exit status 1
21 error Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the angular-quickstart package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run build
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs angular-quickstart
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls angular-quickstart
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

```

**Comment by aspergillusOryzae** [comment]
I am getting the same/similar error with an updated version of npm. It appears that tsc is deprecated? I updated my npm with `npm install npm@latest -g`

MacOSX: 10.11.6
node: 6.10.3
npm: 4.5.0

```
$ node -v
v6.10.3
$ npm -v
4.5.0
$ npm install
$ npm start

> angular-quickstart@1.0.0 prestart ~/Samples/quickstart/quickstart
> npm run build

> angular-quickstart@1.0.0 build ~/Samples/quickstart/quickstart
> tsc -p src/

sh: tsc: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2017-05-05T19_12_28_021Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2017-05-05T19_12_28_040Z-debug.log
```

Debug log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.5.0
3 info using node@v6.10.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-quickstart@1.0.0~prestart: angular-quickstart@1.0.0
6 verbose lifecycle angular-quickstart@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle angular-quickstart@1.0.0~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/me/Samples/quickstart/quickstart/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle angular-quickstart@1.0.0~prestart: CWD: /Users/me/Samples/quickstart/quickstart
9 silly lifecycle angular-quickstart@1.0.0~prestart: Args: [ '-c', 'npm run build' ]
10 silly lifecycle angular-quickstart@1.0.0~prestart: Returned: code: 1  signal: null
11 info lifecycle angular-quickstart@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: angular-quickstart@1.0.0 prestart: `npm run build`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:886:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid angular-quickstart@1.0.0
14 verbose cwd /Users/me/Samples/quickstart/quickstart
15 verbose Darwin 15.6.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v6.10.3
18 verbose npm  v4.5.0
19 error code ELIFECYCLE
20 error errno 1
21 error angular-quickstart@1.0.0 prestart: `npm run build`
21 error Exit status 1
22 error Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
22 error Make sure you have the latest version of node.js and npm installed.
22 error If you do, this is most likely a problem with the angular-quickstart package,
22 error not with npm itself.
22 error Tell the author that this fails on your system:
22 error     npm run build
22 error You can get information on how to open an issue for this project with:
22 error     npm bugs angular-quickstart
22 error Or if that isn't available, you can get their info via:
22 error     npm owner ls angular-quickstart
22 error There is likely additional logging output above.
23 verbose exit [ 1, true ]
```

**Comment by aspergillusOryzae** [comment]
I ran this which got me past the tsc error, and onto the next...
`npm install typescript -g`

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)

**Comment by sabarisan96** [comment]
hi Im new to angular while starting npm im getting below error any one give me the solution

../node_modules/@types/mongodb/index.d.ts(420,24): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(421,24): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(422,24): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(431,30): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(432,30): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(433,30): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(468,30): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(469,30): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(470,30): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(623,37): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(635,17): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(636,17): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(637,17): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(693,12): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(695,12): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(697,15): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(698,15): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(699,15): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(1151,59): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(1403,23): error TS1005: ',' expected.
../node_modules/@types/mongodb/index.d.ts(1512,34): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(104,43): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(104,46): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(104,48): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(105,16): error TS1005: ')' expected.
node_modules/@types/angular/index.d.ts(106,21): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(106,70): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(107,21): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(108,9): error TS1128: Declaration or statement expected.
node_modules/@types/angular/index.d.ts(108,10): error TS1128: Declaration or statement expected.
node_modules/@types/angular/index.d.ts(118,23): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(118,33): error TS1005: ']' expected.
node_modules/@types/angular/index.d.ts(118,41): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(118,42): error TS1136: Property assignment expected.
node_modules/@types/angular/index.d.ts(118,45): error TS1005: ':' expected.
node_modules/@types/angular/index.d.ts(118,58): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(118,121): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(118,131): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(118,137): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(118,147): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(118,156): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(128,20): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(128,35): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(128,77): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(128,87): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(128,93): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(130,22): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(130,31): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(131,25): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(131,29): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(132,26): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(132,44): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(132,54): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(133,22): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(133,28): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(133,36): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(133,39): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(134,21): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(134,27): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(134,35): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(134,38): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(135,24): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(135,30): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(136,24): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(136,30): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(137,25): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(137,31): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(137,39): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(137,42): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(138,23): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(138,29): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(138,37): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(138,40): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(139,23): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(139,29): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(139,37): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(139,40): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(140,26): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(140,32): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(140,40): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(140,43): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(141,23): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(141,29): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(141,37): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(141,40): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(142,26): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(142,32): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(143,22): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(143,31): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(153,18): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(153,31): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(153,39): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(165,17): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(166,22): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(167,22): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(167,44): error TS1005: '(' expected.
node_modules/@types/angular/index.d.ts(167,45): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(167,54): error TS1005: ')' expected.
node_modules/@types/angular/index.d.ts(169,21): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(169,29): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(169,35): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(170,30): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(170,36): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(171,19): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(171,33): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(171,52): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(172,22): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(172,31): error TS1005: ';' expected.
node_modules/@types/angular/index.d.ts(185,39): error TS1109: Expression expected.
node_modules/@types/angular/index.d.ts(243,41): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(244,41): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(1199,23): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(1199,37): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(1212,23): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(1349,41): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(1350,41): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(2069,55): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(2073,54): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(2083,55): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(2088,57): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(2102,48): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(2185,22): error TS1005: ',' expected.
node_modules/@types/angular/index.d.ts(2257,1): error TS1128: Declaration or statement expected.
node_modules/@types/jasmine/index.d.ts(132,30): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(132,32): error TS1005: '>' expected.
node_modules/@types/jasmine/index.d.ts(132,34): error TS1005: ';' expected.
node_modules/@types/jasmine/index.d.ts(132,36): error TS1109: Expression expected.
node_modules/@types/jasmine/index.d.ts(132,61): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(132,69): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(132,70): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(132,93): error TS1005: '(' expected.

npm ERR! Linux 4.4.0-137-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/mytasklist/quickstart/npm-debug.log

npm ERR! Linux 4.4.0-137-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/mytasklist/quickstart/node_modules/npm-debug.log

**Comment by sabarisan96** [comment]
I'm using Ubuntu 16.04 operating system
