### ISSUE TITLE
Update to angular 4.1

### ISSUE THREAD

**Issue by mcarlospc** [angular/quickstart#452]
It seems that angular 4.1 is released, any plan to update this to use angular 4.1?

**Comment by tmirun** [comment]
same question +1

**Comment by MAYDAY1993** [comment]
+1

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
