### ISSUE TITLE
New NPM Module -- File Not Found 404 

### ISSUE THREAD

**Issue by PrithiviMelio** [angular/quickstart#453]
Not able to import new custom module

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
