### ISSUE TITLE
GET http://localhost:3001/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js/animations 404 (Not Found)

### ISSUE THREAD

**Issue by AnnDon** [angular/quickstart#454]
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
heroes:18 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3001/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js/animations
	Error: XHR error (404 Not Found) loading http://localhost:3001/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js/animations
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3001/node_modules/zone.js/dist/zone.js:1230:39) [<root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3001/node_modules/zone.js/dist/zone.js:460:38) [<root>]
	Error loading http://localhost:3001/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js/animations as "@angular/platform-browser/animations" from http://localhost:3001/app/app.module.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3001/node_modules/zone.js/dist/zone.js:1230:39) [<root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3001/node_modules/zone.js/dist/zone.js:460:38) [<root>]
	Error loading http://localhost:3001/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js/animations as "@angular/platform-browser/animations" from http://localhost:3001/app/app.module.js

**Comment by ayyazzafar** [comment]
I am also facing same issue. 
Why is that happening?
What exactly do we need to enable this feature?

**Comment by ayyazzafar** [comment]
By the I added these three lines in systemjs.config.js:

`  '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
  '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
  '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',   `

https://github.com/mgechev/angular-seed/issues/1880#issuecomment-290557768

**Comment by cacothi** [comment]
This issue is still happening with me after installign AngularMaterial, I have the following:

on the app.module.ts

import { BrowserAnimationsModule, NoopAnimationsModule } from '/animations';

imports: [ BrowserModule, MaterialModule, HttpModule, BrowserAnimationsModule, NoopAnimationsModule],

on the systemjs.config.js

  '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
  '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
  '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',  
getting the following error:

Error: (SystemJS) Cannot read property 'prototype' of undefined
TypeError: Cannot read property 'prototype' of undefined
at __extends (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:15:68)
at eval (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:328:5)
at Object.eval (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:337:2)
at Object.eval (http://localhost:3000/app/app.module.js:10:20)
at eval (http://localhost:3000/app/app.module.js:32:4)
Evaluating http://localhost:3000/app/app.module.js
Evaluating http://localhost:3000/main.js
Error loading http://localhost:3000/main.js
at __extends (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:15:68)
at eval (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:328:5)
at Object.eval (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:337:2)
at Object.eval (http://localhost:3000/app/app.module.js:10:20)
at eval (http://localhost:3000/app/app.module.js:32:4)
Evaluating http://localhost:3000/app/app.module.js
Evaluating http://localhost:3000/main.js
Error loading http://localhost:3000/main.js

**Comment by kedricz** [comment]
@cacothi I have the same issue. Have you solved the issue?

**Comment by welkinblue** [comment]
I have the same issue. Also, when I npm install @angular/animations, the package ends up in @angular/platform-browser instead of in its own @angular directory. So @ayyazzafar 's fix doesn't work for me.

**Comment by robert589** [comment]
how to solve this?

**Comment by parane** [comment]
when i update angular,i get this error

**Comment by priyodas12** [comment]
I am getting still 
zone.js:2744 GET http://localhost:55263/src/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js 404 (Not Found)
scheduleTask @ zone.js:2744
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:861
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:844
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2744
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:861
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:844
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
Promise resolved (async)
scheduleMicroTask @ zone.js:585
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:236
Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:842
ZoneAwarePromise.then @ zone.js:932
(anonymous) @ system.src.js:4789
import @ system.src.js:839
(anonymous) @ system.src.js:1801
(anonymous) @ index.html:18
index.html:18 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:55263/src/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js
	Error: XHR error (404 Not Found) loading http://localhost:55263/src/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js
	    at XMLHttpRequest.wrapFn (http://localhost:55263/node_modules/zone.js/dist/zone.js:1075:39)
	    at ZoneDelegate.invokeTask (http://localhost:55263/node_modules/zone.js/dist/zone.js:425:31)
	    at Zone.runTask (http://localhost:55263/node_modules/zone.js/dist/zone.js:192:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:55263/node_modules/zone.js/dist/zone.js:499:34)
	    at invokeTask (http://localhost:55263/node_modules/zone.js/dist/zone.js:1427:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:55263/node_modules/zone.js/dist/zone.js:1445:17)
	Error loading http://localhost:55263/src/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js as "@angular/platform-browser-dynamic" from http://localhost:55263/src/main.js
	    at XMLHttpRequest.wrapFn (http://localhost:55263/node_modules/zone.js/dist/zone.js:1075:39)
	    at ZoneDelegate.invokeTask (http://localhost:55263/node_modules/zone.js/dist/zone.js:425:31)
	    at Zone.runTask (http://localhost:55263/node_modules/zone.js/dist/zone.js:192:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:55263/node_modules/zone.js/dist/zone.js:499:34)
	    at invokeTask (http://localhost:55263/node_modules/zone.js/dist/zone.js:1427:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:55263/node_modules/zone.js/dist/zone.js:1445:17)
	Error loading http://localhost:55263/src/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js as "@angular/platform-browser-dynamic" from http://localhost:55263/src/main.js
(anonymous) @ index.html:18
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:844
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2744
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:861
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:844
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2744
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:861
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:844
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
Promise resolved (async)
scheduleMicroTask @ zone.js:585
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:236
Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:842
ZoneAwarePromise.then @ zone.js:932
(anonymous) @ system.src.js:4789
import @ system.src.js:839
(anonymous) @ system.src.js:1801
(anonymous) @ index.html:18
zone.js:2744 GET http://localhost:55263/src/node_modules/@angular/core/bundles/core.umd.js 404 (Not Found)
scheduleTask @ zone.js:2744
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:861
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:844
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2744
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:861
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:844
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2744
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:861
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:844
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2744
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:861
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:844
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
Promise resolved (async)
scheduleMicroTask @ zone.js:585
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:236
Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:842
ZoneAwarePromise.then @ zone.js:932
(anonymous) @ system.src.js:4789
import @ system.src.js:839
(anonymous) @ system.src.js:1801
(anonymous) @ index.html:18
zone.js:2744 GET http://localhost:55263/src/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js 404 (Not Found)
scheduleTask @ zone.js:2744
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:861
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:844
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2744
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:861
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:844
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2744
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:861
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:844
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2744
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:861
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:844
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
Promise resolved (async)
scheduleMicroTask @ zone.js:585
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:236
Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:842
ZoneAwarePromise.then @ zone.js:932
(anonymous) @ system.src.js:4789
import @ system.src.js:839
(anonymous) @ system.src.js:1801
(anonymous) @ index.html:18

**Comment by priyodas12** [comment]
oops I cleared browser cache and all errors gone,but how..

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)

**Comment by dummy64** [comment]
clear the browser cache

**Comment by Torquemada26** [comment]
I got it working its a combination of ayyazzafar comments on 11 May 2017 ie
step 1)
added these three lines in systemjs.config.js:

'@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js', '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js', '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',

Step 2) from a stackoverflow answer from here https://stackoverflow.com/questions/43118208/exception-on-using-ng2-tag-input

Make sure the @angular/animations package is installed (e.g. by running npm install @angular/animations). Then, in your app.module.ts

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

@NgModule({
  ...,
 imports:      [ BrowserModule, BrowserAnimationsModule],
  ...
})

**Comment by Hotalenw** [comment]
@ayyazzafar fix worked for me too.

**Comment by shravan199** [comment]
Clear your browser cache Ctrl + Shift + Del﻿. This worked for me.

**Comment by hamidnoahdi** [comment]
Hard Reload in chrome worked for me
