### ISSUE TITLE
I cant build this quickstart for production

### ISSUE THREAD

**Issue by emmyjay** [angular/quickstart#455]
Please i have finished an app with this quickstart but i cant build it for production any help please

**Comment by fhightower** [comment]
This can be closed as a duplicate of #461 .

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
