### ISSUE TITLE
Quickstart lacks the .angular-cli.json file

### ISSUE THREAD

**Issue by dhuntley1023** [angular/quickstart#456]
I'm new to Angular so not 100% sure if this is required to meet the mission of the Quickstart project, but it's a difference with the project created by the CLI.

**Comment by Foxandxss** [comment]
An angular application can be built using different tools. You have `System.js` which is what we use in this quickstart, you have `Webpack` which is also highly popular and used in other "quickstarts" like this and then you have the `CLI` which is another tool.

This quickstart is not an Angular CLI project so it doesn't have the `.angular-cli.json`.
