### ISSUE TITLE
npm start Fails on command tsc -p src/

### ISSUE THREAD

**Issue by WindSaber** [angular/quickstart#457]
I'm working with:

> node -v
> v7.10.0

> npm -v
> 4.2.0

I execute next commands
```
git clone https://github.com/angular/quickstart.git quickstart
cd quickstart/
```

```
npm install
angular-quickstart@1.0.0 C:\Users\onava\Documents\angular2tests\curso_fernando\quickstart
+-- @angular/common@4.0.3
+-- @angular/compiler@4.0.3
+-- @angular/core@4.0.3
+-- @angular/forms@4.0.3
+-- @angular/http@4.0.3

+-- @angular/platform-browser@4.0.3
+-- @angular/platform-browser-dynamic@4.0.3
+-- @angular/router@4.0.3
+-- angular-in-memory-web-api@0.3.2
+-- core-js@2.4.1
+-- rxjs@5.0.1
| `-- symbol-observable@1.0.4
+-- systemjs@0.19.40
| `-- when@3.7.8
`-- zone.js@0.8.10
```

```
npm start

> angular-quickstart@1.0.0 prestart C:\Users\onava\Documents\angular2tests\curso_fernando\quickstart
> npm run build


> angular-quickstart@1.0.0 build C:\Users\onava\Documents\angular2tests\curso_fernando\quickstart
> tsc -p src/

src/app/app.component.spec.ts(7,1): error TS2304: Cannot find name 'describe'.
src/app/app.component.spec.ts(12,3): error TS2304: Cannot find name 'beforeEach'.
src/app/app.component.spec.ts(19,3): error TS2304: Cannot find name 'beforeEach'.

src/app/app.component.spec.ts(25,3): error TS2304: Cannot find name 'it'.
src/app/app.component.spec.ts(25,39): error TS2304: Cannot find name 'expect'.
src/app/app.component.spec.ts(27,3): error TS2304: Cannot find name 'it'.
src/app/app.component.spec.ts(30,5): error TS2304: Cannot find name 'expect'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart

npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\onava\AppData\Roaming\npm-cache\_logs\2017-05-16T14_14_49_488Z-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build

npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\onava\AppData\Roaming\npm-cache\_logs\2017-05-16T14_14_49_519Z-debug.log
```

I saw that in the guide appears:

> Doesn't work in Bash for Windows which does not support servers as of January, 2017.

So I used:

- git bash terminal
- cmder 1.3.2
- babun 1.2.0

Always getting same error....

**Comment by Foxandxss** [comment]
Weird, those types comes from `@types/jasmine`

**Comment by WindSaber** [comment]
@Foxandxss  I tried to install it manually
`npm install @types/jasmine`

Then I run again 
`npm start`

Now the trace is:
```
npm start

> angular-quickstart@1.0.0 prestart C:\Users\onava\Documents\angular2tests\curso_fernando\quickstart
> npm run build


> angular-quickstart@1.0.0 build C:\Users\onava\Documents\angular2tests\curso_fernando\quickstart
> tsc -p src/



> angular-quickstart@1.0.0 start C:\Users\onava\Documents\angular2tests\curso_fernando\quickstart
> concurrently "npm run build:watch" "npm run serve"

"concurrently" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "npm run serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'concurrently "npm run build:watch" "npm run serve"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run build:watch" "npm run serve"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\onava\AppData\Roaming\npm-cache\_logs\2017-05-16T16_00_41_328Z-debug.log
```

Now I'll focus on this

**Comment by Foxandxss** [comment]
Weird, it is like your `npm install` didn't install everything. It is not finding `concurrently`

**Comment by WindSaber** [comment]
That's true @Foxandxss, probably it's a problem with my node installation....

Anyway, after running:
```
npm install @types/jasmine
npm install "concurrently"
npm install "lite-server"

```
The Hello Angular message finally appeared on my browser....

I'll leave the issue opened....as I'm new in angular, i'm not sure if it was an angular or a node problem...in this case I think it can be closed

Thanks

**Comment by WindSaber** [comment]
I wasn't so confortable with my last result so I decided to test the quickstart in another computer with a different configuration, node v6.10 and I got the same error.....

**Comment by AVGP** [comment]
Same issue here on OSX:

node.js 7.8.0
npm 4.2.0 (I also tried the npm5 beta, same result)

But I get a slightly different issue:

```
> tsc -p src/

node_modules/@types/jasmine/index.d.ts(9,18): error TS2300: Duplicate identifier 'describe'.
node_modules/@types/jasmine/index.d.ts(11,18): error TS2300: Duplicate identifier 'xdescribe'.
node_modules/@types/jasmine/index.d.ts(13,18): error TS2300: Duplicate identifier 'it'.
node_modules/@types/jasmine/index.d.ts(14,18): error TS2300: Duplicate identifier 'it'.
node_modules/@types/jasmine/index.d.ts(17,18): error TS2300: Duplicate identifier 'xit'.
node_modules/@types/jasmine/index.d.ts(18,18): error TS2300: Duplicate identifier 'xit'.
../../node_modules/@types/lodash/index.d.ts(12898,29): error TS2304: Cannot find name 'object'.
../../node_modules/@types/lodash/index.d.ts(19638,15): error TS2428: All declarations of 'WeakMap' must have identical type parameters.
../../node_modules/@types/lodash/index.d.ts(19638,33): error TS2304: Cannot find name 'object'.
../../node_modules/@types/mocha/index.d.ts(33,13): error TS2300: Duplicate identifier 'describe'.
../../node_modules/@types/mocha/index.d.ts(34,13): error TS2300: Duplicate identifier 'xdescribe'.
../../node_modules/@types/mocha/index.d.ts(39,13): error TS2300: Duplicate identifier 'it'.
../../node_modules/@types/mocha/index.d.ts(40,13): error TS2300: Duplicate identifier 'xit'.
```

**Comment by HarryCh94** [comment]
Happened to me when `npm install` didn't install devDependencies. 
Changing the NODE_ENV to development seems to fix the issue.

**Comment by jabbar86** [comment]
> angular@1.0.0 start C:\Users\Jabbar Memon\Downloads\Angular-2-Tutorials-master\Template
> tsc && concurrently "npm run tsc:w" "npm run lite"

app/app.module.ts(1,10): error TS2305: Module '"C:/Users/Jabbar Memon/Downloads/Angular-2-Tutorials-master/Template/node_modules/@angular/core/index"' has no exported member 'NgModule'.
app/app.module.ts(2,10): error TS2305: Module '"C:/Users/Jabbar Memon/Downloads/Angular-2-Tutorials-master/Template/node_modules/@angular/platform-browser/index"' has no exported member 'BrowserModule'.
app/app.module.ts(3,27): error TS2307: Cannot find module '@angular/forms'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jabbar Memon\AppData\Roaming\npm-cache\_logs\2017-09-15T06_10_13_145Z-debug.log

I am getting still Error And i have install as per @WindSaber . Then alsso getting error ...

**Comment by manuepeva** [comment]
Hello,

I had this same issue and I was a stuck because I didn´t know that the real bug it was in the npm installer, that didn´t download all the required files correctly. 

Anyway, WindSaber  got the solution and after trying this on git bash : 

npm install @types/jasmine
npm install "concurrently"
npm install "lite-server"

Finally, I solved the problem,

**Comment by jabbar86** [comment]
Still i am getting error @manuepeva ..

**Error File**
$ npm start

> angular@1.0.0 start E:\Mean Stack\Angular-2-Tutorials-master\Template
> tsc && concurrently "npm run tsc:w" "npm run lite"

node_modules/@angular/forms/src/directives/ng_model.d.ts(8,32): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/core/index"' has no exported member 'SimpleChanges'.
node_modules/@angular/forms/src/directives/reactive_directives/form_control_directive.d.ts(8,21): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/core/index"' has no exported member 'SimpleChanges'.
node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.d.ts(8,32): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/core/index"' has no exported member 'SimpleChanges'.
node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.d.ts(8,21): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/core/index"' has no exported member 'SimpleChanges'.
app/app.module.ts(1,10): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/core/index"' has no exported member 'NgModule'.
app/app.module.ts(2,10): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/platform-browser/index"' has no exported member 'BrowserModule'.
app/app.module.ts(3,10): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/forms/index"' has no exported member 'FormsModule'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jabbar Memon\AppData\Roaming\npm-cache\_logs\2017-09-20T05_05_20_744Z-debug.log

**Package.JSON**

{
  "name": "angular",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/compiler-cli": "^4.4.2",
    "@angular/core": "2.0.0-rc.1",
    "@angular/forms": "^0.2.0",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "@angular/upgrade": "2.0.0-rc.1",
    "angular2-in-memory-web-api": "0.0.7",
    "bootstrap": "^3.3.6",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.2",
    "concurrently": "^2.2.0",
    "lite-server": "^2.3.0",
    "typescript": "^1.8.10",
    "typings": "^0.8.1"
  }
}

**Comment by ZahScr** [comment]
I'm getting this error on $ npm start

**debug.log**

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.4.2
3 info using node@v6.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-quickstart@1.0.0~prestart: angular-quickstart@1.0.0
6 verbose lifecycle angular-quickstart@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle angular-quickstart@1.0.0~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/zachscragg/angular-tour-of-heroes/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle angular-quickstart@1.0.0~prestart: CWD: /Users/zachscragg/angular-tour-of-heroes
9 silly lifecycle angular-quickstart@1.0.0~prestart: Args: [ '-c', 'npm run build' ]
10 silly lifecycle angular-quickstart@1.0.0~prestart: Returned: code: 2  signal: null
11 info lifecycle angular-quickstart@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: angular-quickstart@1.0.0 prestart: `npm run build`
12 verbose stack Exit status 2
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:920:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
13 verbose pkgid angular-quickstart@1.0.0
14 verbose cwd /Users/zachscragg/angular-tour-of-heroes
15 verbose Darwin 14.5.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v6.11.3
18 verbose npm  v5.4.2
19 error code ELIFECYCLE
20 error errno 2
21 error angular-quickstart@1.0.0 prestart: `npm run build`
21 error Exit status 2
22 error Failed at the angular-quickstart@1.0.0 prestart script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 2, true ]

**This is my package.json file**

{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "build": "tsc -p src/",
    "build:watch": "tsc -p src/ -w",
    "build:e2e": "tsc -p e2e/",
    "serve": "lite-server -c=bs-config.json",
    "serve:e2e": "lite-server -c=bs-config.e2e.json",
    "prestart": "npm run build",
    "start": "concurrently \"npm run build:watch\" \"npm run serve\"",
    "pree2e": "npm run build:e2e",
    "e2e": "concurrently \"npm run serve:e2e\" \"npm run protractor\" --kill-others --success first",
    "preprotractor": "webdriver-manager update",
    "protractor": "protractor protractor.config.js",
    "pretest": "npm run build",
    "test": "concurrently \"npm run build:watch\" \"karma start karma.conf.js\"",
    "pretest:once": "npm run build",
    "test:once": "karma start karma.conf.js --single-run",
    "lint": "tslint ./src/**/*.ts -t verbose"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~4.3.4",
    "@angular/compiler": "~4.3.4",
    "@angular/core": "~4.3.4",
    "@angular/forms": "~4.3.4",
    "@angular/http": "~4.3.4",
    "@angular/platform-browser": "~4.3.4",
    "@angular/platform-browser-dynamic": "~4.3.4",
    "@angular/router": "~4.3.4",
    "angular-in-memory-web-api": "~0.3.0",
    "check-node-version": "^2.1.0",
    "core-js": "^2.4.1",
    "npm": "^5.4.2",
    "rxjs": "5.0.1",
    "systemjs": "0.19.40",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@types/jasmine": "^2.5.36",
    "@types/node": "^6.0.46",
    "canonical-path": "0.0.2",
    "concurrently": "^3.5.0",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "lite-server": "^2.3.0",
    "lodash": "^4.16.4",
    "protractor": "~4.0.14",
    "rimraf": "^2.5.4",
    "tslint": "^3.15.1",
    "typescript": "~2.1.0"
  },
  "repository": {}
}

**Comment by rayets123** [comment]
Sorry, WindSaber's  solution is not work for me :

npm install
npm install "concurrently"
npm install "lite-server"

the problem still remains

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)

**Comment by rayets123** [comment]
Thank you very much for informing me( ͡ ͜ʖ ͡ )

31 окт 2017 г. 16:51 пользователь "Jesús Rodríguez" <
notifications@github.com> написал:

Closed #457 <https://github.com/angular/quickstart/issues/457>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/angular/quickstart/issues/457#event-1318917471>, or mute
the thread

**Comment by SarvagyaS** [comment]
I was having the same error. I realised that the problem was with npm install,
I went into the quickstart folder and executed npm install again, it worked !

**Comment by shubhhankar** [comment]
@Foxandxss Please Help. I am getting the below error while running npm start commant for the first time after setup.

> angular-quickstart@1.0.0 start E:\Angular\Angular2Demo\Angular2Demo
> concurrently "npm run build:watch" "npm run serve"

E:\Angular\Angular2Demo\Angular2Demo\node_modules\concurrently\src\main.js:230
          spawnOpts.env = Object.assign({FORCE_COLOR: supportsColor.level}, pr
                                 ^
TypeError: undefined is not a function
    at E:\Angular\Angular2Demo\Angular2Demo\node_modules\concurrently\src\main.js:230:34
    at arrayMap (E:\Angular\Angular2Demo\Angular2Demo\node_modules\lodash\lodash.js:631:23)
    at Function.map (E:\Angular\Angular2Demo\Angular2Demo\node_modules\lodash\lodash.js:9546:14)
    at run (E:\Angular\Angular2Demo\Angular2Demo\node_modules\concurrently\src\main.js:221:22)
    at main (E:\Angular\Angular2Demo\Angular2Demo\node_modules\concurrently\src\main.js:72:5)
    at Object.<anonymous> (E:\Angular\Angular2Demo\Angular2Demo\node_modules\concurrently\src\main.js:512:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "npm run serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'concurrently "npm run build:watch" "npm run serve"'.
npm ERR! This is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run build:watch" "npm run serve"
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Angular\Angular2Demo\Angular2Demo\npm-debug.log

**Comment by rupesh4444** [comment]
I am getting error like this. please help me. I am stuck
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2019-08-30T16_58_33_064Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2019-08-30T16_58_33_195Z-debug.log
