### ISSUE TITLE
Repo's description speaks of angular 2

### ISSUE THREAD

**Issue by cluelessjoe** [angular/quickstart#459]
Hi 

The repo's description, on the landing page, is the following:
"Angular 2 QuickStart - source from the documentation"
I guess the 2 is too much ;)

cheers

**Comment by knitesh** [comment]
Agree

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
