### ISSUE TITLE
what command is used to build this quickstart for production

### ISSUE THREAD

**Issue by emmyjay** [angular/quickstart#461]

**Comment by fhightower** [comment]
When you start the app using `npm start`, the app is running in development mode and shows a console message that reads:

```
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
```

To run the app in production mode, you will need to add the following code to the [main.ts](https://github.com/angular/quickstart/blob/master/src/main.ts) file:

```typescript
import { enableProdMode } from '@angular2/core';

enableProdMode();
```

You'll find some discussion of this here: https://stackoverflow.com/questions/35721206/how-to-enable-production-mode-in-angular-2.

**Comment by emmyjay** [comment]
what if it is the latest angualar 4 quickstart not the cli

**Comment by fhightower** [comment]
The code in my comment _should_ work in the most recent version of this [quickstart](https://github.com/angular/quickstart/), although I haven't had a chance to try it yet. Give it a try and see if it works.

As to why the error message says `Angular 2`, I'm not sure.

**Comment by fhightower** [comment]
Does this work for you @emmyjay ?

**Comment by emmyjay** [comment]
nope it doesnt i tried it i was getting error

**Comment by fhightower** [comment]
Ok, I'll check it out.

**Comment by fhightower** [comment]
Ok, my original code had a problem with it. To run the app in production mode, your [main.ts](https://github.com/angular/quickstart/blob/master/src/main.ts) should have the following code:

```typescript
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';

enableProdMode();
platformBrowserDynamic().bootstrapModule(AppModule);
```

This works for me. Let me know if this works for you @emmyjay .

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
