### ISSUE TITLE
Failed at the angular-quickstart@1.0.0 start script 'concurrently "npm run build:watch" "npm run serve"'.

### ISSUE THREAD

**Issue by WanjyDan** [angular/quickstart#463]
Someone please help me solve this error.

angular-quickstart@1.0.0 start C:\Users\Dannie\Downloads\Compressed\quickstart-master
> concurrently "npm run build:watch" "npm run serve"

 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1018:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:390:7)
     at startup (bootstrap_node.js:150:9)
     at bootstrap_node.js:505:3
 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1018:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:390:7)
     at startup (bootstrap_node.js:150:9)
     at bootstrap_node.js:505:3
[1] npm run serve exited with code -4058

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "npm run serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'concurrently "npm run build:watch" "npm run serve"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run build:watch" "npm run serve"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Dannie\Downloads\Compressed\quickstart-master\npm-debug.log

![screenshot 44](https://cloud.githubusercontent.com/assets/23149113/26486260/065f8e60-4203-11e7-9bab-f5b0ca693ef9.png)

**Comment by AnneWQ** [comment]
run command separately temporarily worked for me.
`concurrently `
`npm run build:watch`
`npm run serve`

**Comment by WanjyDan** [comment]
Thanks @AnneWQ for the temporary fix.
I was able to fix it permanently by adding the following values to system variable PATH:
C:\Windows\System32
C:\Program Files\nodejs\

**Comment by Jay1989** [comment]
@WanjyDan its working for me... Thanks..

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)

**Comment by UtmostCreator** [comment]
> Thanks @AnneWQ for the temporary fix.
> I was able to fix it permanently by adding the following values to system variable PATH:
> C:\Windows\System32
> C:\Program Files\nodejs\

That's great, thanks!

But can you give me some URLs about PATHs in windows?
And why does this one need path to C:\Windows\System32?
