### ISSUE TITLE
Karma/Jasmine Tests not working after putting js files in separate directory

### ISSUE THREAD

**Issue by brandonkoch6** [angular/quickstart#469]
I've outputted the compiled .js files into a separate directory called 'dist', using the following changes:

In tsconfig.json (add) : "outDir": "../dist"
In bs-config.json (change) : "baseDir": ["dist", "src"],
In bs-config.e2e.json (change) : "baseDir": ["dist", "src"],

No change to systemjs.config.js.

This works for my e2e protractor tests, but I'm having difficulty figuring out how to modify the karma.conf.js to make the karma tests work again.  Any help would be appreciated.

Thanks!

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
