### ISSUE TITLE
 unable to access 'https://github.com/angular/quickstart/

### ISSUE THREAD

**Issue by bibermar** [angular/quickstart#47]
Did according https://github.com/angular/quickstart/blob/master/README.md
line in git shell:
$ git clone  https://github.com/angular/quickstart  my-proj
gives error:
**fatal: unable to access 'https://github.com/angular/quickstart/': Couldn't resolve host 'github.com'**
The url is accessible via browser

**Comment by Foxandxss** [comment]
That is something with your connection. Firewall or something.

**Comment by bibermar** [comment]
Thanks Jesus,
I can access the url via browser.
Wouldn’t firewall prevent browser access as well?

**Comment by Foxandxss** [comment]
if your browser has a proxy to access github, you can access it with the browser. You would need to setup the proxy for github in the CLI.

I would check that.

**Comment by bibermar** [comment]
Thank you Jesus,

I’m new in GIT.

Haw you setup the proxy for github in the CLI.?

Regards Roman

**Comment by Foxandxss** [comment]
I would check this http://stackoverflow.com/questions/20370294/could-not-resolve-host-github-com-error-while-cloning-remote-repository-in-git

**Comment by wardbell** [comment]
Sorry but this is not a general support site and your question is out of scope. Closing.
