### ISSUE TITLE
Failed to load resource: app/app.module

### ISSUE THREAD

**Issue by chinttttt** [angular/quickstart#470]
Hello, i am getting the subject error, while loading the index.html page from IISExpress, referring to the quick master project downloaded from this website. Appreciate your inputs.

" Error loading http://localhost:7041/src/app/app.module as "./app/app.module" from http://localhost:7041/src/main.js "

I am following the same directory structure. i.e src-> app-> app.module.ts and other ts files. 
main.js is available under src.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
