### ISSUE TITLE
npm ERR! Unexpected end of input at 1:42515

### ISSUE THREAD

**Issue by kaygeeklaas** [angular/quickstart#471]
Hi i seem to be getting this error every time i try to restore packages and goes on to show this error message as well **npm ERR! -replace":"^1.1.1","systemjs-plugin-babel":"0.0.17","systemjs-plugin-**.
Im using visual studio update 3

**Comment by Tbwas** [comment]
I am experiencing the same issue. Did you resolve it?

**Comment by glenster75** [comment]
`npm cache clean --force`
solved it for me

**Comment by Tbwas** [comment]
ok, thanks!

**Comment by jeanjoe** [comment]
Thanks man, this worked for me too

**Comment by baj9032** [comment]
@glenster75 : thank you.

**Comment by amitsinghr** [comment]
thank you it worked!

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)

**Comment by himharsh1997** [comment]
For me, it didn't work for me

**Comment by BenjaminNjoroge** [comment]
This happens mostly due to poor internet connection
