### ISSUE TITLE
Error TS2304:Cannot find name 'Set'

### ISSUE THREAD

**Issue by Thambi80** [angular/quickstart#473]
Hi All,

Getting below error while run my first Angular2 code. 

C:\xxxx\MVC\Angular2_Tutorial\Template>npm start

> angular-quickstart@1.0.0 start C:\xxx\MVC\Angular2_Tutorial\Template
> tsc && concurrently "npm run tsc:w" "npm run lite"

node_modules/@angular/compiler/src/compile_metadata.d.ts(347,20): error TS2304:Cannot find name 'Set'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(348,15): error TS2304:
Cannot find name 'Set'.
node_modules/@angular/compiler/src/offline_compiler.d.ts(15,26): error TS2304: C
annot find name 'Map'.
node_modules/@angular/compiler/src/offline_compiler.d.ts(16,38): error TS2304: C
annot find name 'Map'.
node_modules/@angular/compiler/src/output/output_ast.d.ts(424,63): error TS2304:
 Cannot find name 'Set'.
node_modules/@angular/compiler/src/template_parser/template_parser.d.ts(45,12):
error TS2304: Cannot find name 'Set'.
node_modules/@angular/compiler/src/view_compiler/compile_element.d.ts(33,16): er
ror TS2304: Cannot find name 'Map'.
node_modules/@angular/compiler/src/view_compiler/compile_query.d.ts(24,49): erro
r TS2304: Cannot find name 'Map'.
node_modules/@angular/compiler/src/view_compiler/compile_view.d.ts(29,18): error
 TS2304: Cannot find name 'Map'.
node_modules/@angular/compiler/src/view_compiler/compile_view.d.ts(52,16): error
 TS2304: Cannot find name 'Map'.
node_modules/@angular/compiler/src/view_compiler/compile_view.d.ts(54,13): error
 TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.
d.ts(24,15): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.
d.ts(28,16): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(88,123): error TS2304
: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(88,165): error TS2304
: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(2,25): error TS2304: Canno
t find name 'MapConstructor'.
node_modules/@angular/core/src/facade/collection.d.ts(3,25): error TS2304: Canno
t find name 'SetConstructor'.
node_modules/@angular/core/src/facade/collection.d.ts(5,27): error TS2304: Canno
t find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(5,39): error TS2304: Canno
t find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(8,9): error TS2304: Cannot
 find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(9,30): error TS2304: Canno
t find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(12,43): error TS2304: Cann
ot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(13,27): error TS2304: Cann
ot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(15,23): error TS2304: Cann
ot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(16,25): error TS2304: Cann
ot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(101,41): error TS2304: Can
not find name 'Set'.
node_modules/@angular/core/src/facade/collection.d.ts(102,22): error TS2304: Can
not find name 'Set'.
node_modules/@angular/core/src/facade/collection.d.ts(103,25): error TS2304: Can
not find name 'Set'.
node_modules/@angular/core/src/facade/lang.d.ts(12,17): error TS2304: Cannot fin
d name 'Map'.
node_modules/@angular/core/src/facade/lang.d.ts(13,17): error TS2304: Cannot fin
d name 'Set'.
node_modules/@angular/core/src/facade/lang.d.ts(51,59): error TS2304: Cannot fin
d name 'Map'.
node_modules/rxjs/Observable.d.ts(66,60): error TS2693: 'Promise' only refers to
 a type, but is being used as a value here.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "npm run tsc:w" "n
pm run lite" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2017-06-23T12_51_
03_131Z-debug.log

Could you please on to run my first Angular2.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
