### ISSUE TITLE
npm start error.please help me resolve this issue

### ISSUE THREAD

**Issue by OMADITYESH** [angular/quickstart#480]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-quickstart@1.0.0~prestart: angular-quickstart@1.0.0
6 verbose lifecycle angular-quickstart@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle angular-quickstart@1.0.0~prestart: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\SNSingh\Projects\myapp\node_modules\.bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\SNSingh\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\SNSingh\AppData\Roaming\npm
8 verbose lifecycle angular-quickstart@1.0.0~prestart: CWD: C:\Users\SNSingh\Projects\myapp
9 silly lifecycle angular-quickstart@1.0.0~prestart: Args: [ '/d /s /c', 'npm run build' ]
10 silly lifecycle angular-quickstart@1.0.0~prestart: Returned: code: 0  signal: null
11 info lifecycle angular-quickstart@1.0.0~start: angular-quickstart@1.0.0
12 verbose lifecycle angular-quickstart@1.0.0~start: unsafe-perm in lifecycle true
13 verbose lifecycle angular-quickstart@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\SNSingh\Projects\myapp\node_modules\.bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\SNSingh\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\SNSingh\AppData\Roaming\npm
14 verbose lifecycle angular-quickstart@1.0.0~start: CWD: C:\Users\SNSingh\Projects\myapp
15 silly lifecycle angular-quickstart@1.0.0~start: Args: [ '/d /s /c',
15 silly lifecycle   'concurrently "npm run build:watch" "npm run serve"' ]
16 silly lifecycle angular-quickstart@1.0.0~start: Returned: code: 1  signal: null
17 info lifecycle angular-quickstart@1.0.0~start: Failed to exec start script
18 verbose stack Error: angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "npm run serve"`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:891:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid angular-quickstart@1.0.0
20 verbose cwd C:\Users\SNSingh\Projects\myapp
21 error Windows_NT 6.1.7601
22 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
23 error node v6.11.1
24 error npm  v3.10.10
25 error code ELIFECYCLE
26 error angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "npm run serve"`
26 error Exit status 1
27 error Failed at the angular-quickstart@1.0.0 start script 'concurrently "npm run build:watch" "npm run serve"'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-quickstart package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     concurrently "npm run build:watch" "npm run serve"
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-quickstart
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-quickstart
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
