### ISSUE TITLE
error on NPM start and git clone

### ISSUE THREAD

**Issue by nvasilev1** [angular/quickstart#484]
Hello,

I am following this tutorial on setting up app:
 https://angular.io/guide/setup

If i try with clone, the following error message appears:

D:\temp\NV\nv-first>git clone https://github.com/angular/quickstart.git quicksta
rt
'git' is not recognized as an internal or external command,
operable program or batch file.

If I try with download, it is ok, but after installing NPM and writing start the following error appears:

D:\temp\NV\nv-first\quickstart>npm start

> angular-quickstart@1.0.0 prestart D:\temp\NV\nv-first\quickstart
> npm run build

> angular-quickstart@1.0.0 build D:\temp\NV\nv-first\quickstart
> tsc -p src/

../node_modules/@types/jasminewd2/index.d.ts(23,13): error TS2428: All declarati
ons of 'Matchers' must have identical type parameters.
../node_modules/@types/jasminewd2/index.d.ts(47,13): error TS2430: Interface 'Ar
rayLikeMatchers<T>' incorrectly extends interface 'Matchers<ArrayLike<T>>'.
  Types of property 'toBe' are incompatible.
    Type '(expected: any, expectationFailOutput?: any) => Promise<void>' is not
assignable to type '{ (expected: any, expectationFailOutput?: any): boolean; (ex
pected: any, expectationFailOutput?: ...'.
      Type 'Promise<void>' is not assignable to type 'boolean'.
../node_modules/@types/jasminewd2/index.d.ts(48,20): error TS2304: Cannot find n
ame 'Expected'.
../node_modules/@types/jasminewd2/index.d.ts(49,23): error TS2304: Cannot find n
ame 'Expected'.
node_modules/@types/jasmine/index.d.ts(33,41): error TS2314: Generic type 'Match
ers<T>' requires 1 type argument(s).
node_modules/@types/jasmine/index.d.ts(34,39): error TS2314: Generic type 'Match
ers<T>' requires 1 type argument(s).
node_modules/@types/jasmine/index.d.ts(159,24): error TS2314: Generic type 'Matc
hers<T>' requires 1 type argument(s).
node_modules/@types/jasmine/index.d.ts(339,14): error TS2314: Generic type 'Matc
hers<T>' requires 1 type argument(s).
node_modules/@types/jasmine/index.d.ts(396,24): error TS2314: Generic type 'Matc
hers<T>' requires 1 type argument(s).
node_modules/@types/jasmine/index.d.ts(409,30): error TS2314: Generic type 'Matc
hers<T>' requires 1 type argument(s).

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\temp\\NV\\node-v6.11.1-win-x64\\node.exe" "D:\\temp\\NV\\node
-v6.11.1-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart pa
ckage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\temp\NV\nv-first\quickstart\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\temp\\NV\\node-v6.11.1-win-x64\\node.exe" "D:\\temp\\NV\\node
-v6.11.1-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.

npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart pa
ckage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\temp\NV\nv-first\quickstart\npm-debug.log

Any ideas?

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
