### ISSUE TITLE
TS2559 Type 'By' has no properties in common with type 'Locator'

### ISSUE THREAD

**Issue by cmbenda** [angular/quickstart#486]
It seems even with TypeScript v2.3.3, (not the latest v2.4.1) This code has a bug.  Suggestions?

![image](https://user-images.githubusercontent.com/8538603/28982527-39487f8c-7924-11e7-9190-e5c1eeef6f3a.png)

![image](https://user-images.githubusercontent.com/8538603/28982597-6ec3f128-7924-11e7-8d69-2470e899d5be.png)

**Comment by mbanil** [comment]
Check if the version of Typescript installed is 'TypeScripts 2.2' .  You shouldn't get the error if you are using TypeScript 2.2 .

**Comment by ValentinHruzinski** [comment]
You can do: `import { Locator } from "protractor/built/locators";` and write `...(<Locator >by.css(...))`. But I can not say that this is a good solution

**Comment by RomkeVdMeulen** [comment]
Fortunately this was [fixed in Protractor 5.1.0](https://github.com/angular/protractor/blob/5.1.0/lib/locators.ts#L19).

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
