### ISSUE TITLE
About 'npm install' module version has been deprecated

### ISSUE THREAD

**Issue by qumuase** [angular/quickstart#496]
```
[express@2.5.11](./node_modules/.2.0.0-pre-I0Z7U9OV@weinre/node_modules/express) deprecate: express 2.x series is deprecated
[connect@1.9.2](./node_modules/.2.5.11@express/node_modules/connect) deprecate: connect 1.x series is deprecated
[minimatch@0.3.0](./node_modules/.3.2.11@glob/node_modules/minimatch) deprecate: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```
version has been deprecated.
Is it because it leads to 'npm start' failure?

**Comment by sboden** [comment]
No it doesn't. It seems the angular quickstart example is a 'little' behind the current state.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
