### ISSUE TITLE
Return the source in translate, instead of setting load.source directly

### ISSUE THREAD

**Issue by maximusk** [angular/quickstart#497]
Currently `systemjs-angular-loader.js` [assigns translated source to `load`](https://github.com/angular/quickstart/blob/master/src/systemjs-angular-loader.js#L24), however this behavior [will be deprecated soon](https://github.com/systemjs/systemjs/blob/9ae69b905f93df449357310b0b53de8c3e919e17/dist/system.src.js#L4597).

Do you guys accept PR? I'm willing to make a change.

**Comment by Foxandxss** [comment]
Uhm, we have the systemjs locked down because there was a breaking change that for some reason we didn't want (maybe plunker related).

So I am unsure if we are going to hit that deprecation. That being said, if the new version works with .40, I am all in :)

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
