### ISSUE TITLE
Source code in not available  

### ISSUE THREAD

**Issue by NikhilRPatil** [angular/quickstart#498]
As per u shown in video https://github.com/angular/ ..
here the code is different

**Comment by Foxandxss** [comment]
Sorry, which video?

**Comment by NikhilRPatil** [comment]
https://stackskills.com/courses/learn-angular-2-from-beginner-to-advanced/ 

in this u provide the github link ...it is not there

**Comment by Foxandxss** [comment]
Sorry, but that course is a third party course, not related to Google nor this Quickstart.

This quickstart was built for the angular.io examples.

So the right solution would be to ask the poeople at stackskills to update their videos.

**Comment by NikhilRPatil** [comment]
sir can u give me mini project link which is based on angular js ....
