### ISSUE TITLE
About angular_quickstart demo.

### ISSUE THREAD

**Issue by simechiang** [angular/quickstart#5]
Why I can not use `;` in `app.es6` file. It is not working, and browser do not throw any errors... I think it is a bug or you need to annotate: 'please do not use `;` at `@Template...`', Thank you.

![iw a tyq figy1 9 b8t](https://cloud.githubusercontent.com/assets/5195218/6661129/f46900b8-cbe1-11e4-99ec-f15adfd2428c.jpg)

> My english is not good. : (

**Comment by davideast** [comment]
Hello!

Annotations should not have trailing semicolons. This is the natural syntax of the language.  I don't feel that a callout is necessary either. None of the provided code has a trailing semicolon around annotations. If you use the code samples verbatim they will work as intended.

**Comment by simechiang** [comment]
Alright... Thank you !
