### ISSUE TITLE
Resolving issue 

### ISSUE THREAD

**Issue by Aswin1988** [angular/quickstart#500]
D:\Bootstrap\Bootstrap>npm start
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! path D:\Bootstrap\Bootstrap\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\Bootstrap\Bootstrap\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'D:\Bootstrap\Bootstrap\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Bootstrap\Bootstrap\npm-debug.log

D:\Bootstrap\Bootstrap>

**Comment by Foxandxss** [comment]
do you have a `package.json` in that folder? It says it doesn't exist.

**Comment by Aswin1988** [comment]
Thanks. I found it later. It was in another Drive. I m new to it. So do not know much about UI.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
