### ISSUE TITLE
Don't put generated/compiled files in the `src` directory

### ISSUE THREAD

**Issue by sampathsris** [angular/quickstart#501]
It would be less confusing if the generated `*.js`, and `*.js.map` files were put in a separate directory (e.g.: `build`, anything other than `src`), and have the `lite-server` serve from there. This will make the Angular component structure easy to grasp. Same goes for the `e2e` directory.

Please let me know if you think this is a valid concern.

**Comment by Foxandxss** [comment]
It is a valid concern, I had the same problem when I started working with this.

On the one hand, you can easily hide the `.js` and `.js.map` files at VScode (only if they have a matching .ts):

```
"**/*.js": { "when": "$(basename).ts"},
"**/*.js.map": true
```

That in your settings.

On the other hand, this project is going to be deprecated in October.

**Comment by anyayunli** [comment]
may I know why this project is gonna be deprecated? I just started angular4 with this guide.

**Comment by Foxandxss** [comment]
When we started writing the docs, we had SystemJS and we created all our documentation around that. We had a "quickstart" guide that was the entry point of the rest of the docs. That was the time when Angular CLI didnt exist.

Nowadays, we don't have that quickstart guide anymore and all the documentation is being adapted for the Angular CLI.

When that  happens, this repository will be deprecated. It served its purpose when we started, but today, Angular CLI is a better option in everything.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
