### ISSUE TITLE
Error and seem to have a different quickstart Master file

### ISSUE THREAD

**Issue by starter60** [angular/quickstart#502]
Hey ,

just starting this course but I have a few issues/ questions: 

The quickstart master code looks different in atom than in the videos. 

For example: 
- I dont have a typings.json; 
- in the index.html mine says "   System.import('main.js').catch(function(err){ console.error(err); });" & not "  System.import('app')"

Also my tmp file doesnt have an "app" folder after going through the steps 

And i get an error message in cmd:   C:\Users\Admin\Desktop\quickstart-master\npm-debug.log

Any advice or help would be greatly appreciated as I am new at this. 

Thank you!

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
