### ISSUE TITLE
http://localhost:3000/

### ISSUE THREAD

**Issue by Ukmandal** [angular/quickstart#521]
zone.js:1263 GET http://localhost:3000/app/ 404 (Not Found)
scheduleTask @ zone.js:1263
ZoneDelegate.scheduleTask @ zone.js:205
Zone.scheduleMacroTask @ zone.js:142
(anonymous) @ zone.js:1293
send @ VM614:3
fetchTextFromURL @ system.src.js:1156
(anonymous) @ system.src.js:1739
ZoneAwarePromise @ zone.js:467
(anonymous) @ system.src.js:1738
(anonymous) @ system.src.js:2764
(anonymous) @ system.src.js:3338
(anonymous) @ system.src.js:3605
(anonymous) @ system.src.js:3990
(anonymous) @ system.src.js:4453
(anonymous) @ system.src.js:4705
(anonymous) @ system.src.js:408
ZoneDelegate.invoke @ zone.js:192
Zone.run @ zone.js:85
(anonymous) @ zone.js:451
ZoneDelegate.invokeTask @ zone.js:225
Zone.runTask @ zone.js:125
drainMicroTaskQueue @ zone.js:357
Promise resolved (async)
scheduleQueueDrain @ zone.js:330
scheduleMicroTask @ zone.js:338
ZoneDelegate.scheduleTask @ zone.js:208
Zone.scheduleMicroTask @ zone.js:139
scheduleResolveOrReject @ zone.js:449
ZoneAwarePromise.then @ zone.js:525
(anonymous) @ system.src.js:4663
import @ system.src.js:872
(anonymous) @ system.src.js:1762
(anonymous) @ (index):24
(index):24 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/app
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (https://unpkg.com/zone.js@0.6.23/dist/zone.js:636:29)
	    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.6.23/dist/zone.js:225:37)
	    at Zone.runTask (https://unpkg.com/zone.js@0.6.23/dist/zone.js:125:47)
	    at XMLHttpRequest.ZoneTask.invoke (https://unpkg.com/zone.js@0.6.23/dist/zone.js:293:33)
	Error loading http://localhost:3000/app

**Comment by IOrlandoni** [comment]
> try to login from [https://localhosts.mobi/:3000](https://localhosts.mobi/:3000)  

if you get connection errors  reinstall your angular server.

**Comment by schulace** [comment]
This page is the second result for localhost:3000 on Google. what

**Comment by salim26** [comment]
fuvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
