### ISSUE TITLE
The TourOfHero - The Hero Editor || Quickstart || Error

### ISSUE THREAD

**Issue by nishantgiri** [angular/quickstart#523]
After making suggested changes in the 'The Hero Editor' I am getting following exception in the console.
Could someone please help on this. Enclosing the screenshots.

Looking forward to hearing from you.

Could not locate webpack:///(webpack)-dev-server/client* specified in source map data:application/json;charset=utf-8;base64,eyJ

![angular2-tourofheroes-angularerror2](https://user-images.githubusercontent.com/35130909/34607208-a623d16e-f238-11e7-8337-36ef2cd26d8f.gif)
![angular2-tourofheroes-angularerror](https://user-images.githubusercontent.com/35130909/34607117-25d5b6d0-f238-11e7-810d-a8b9b67cfbcf.gif)

**Comment by Foxandxss** [comment]
This repo is dead and completely unrelated with webpack

**Comment by nishantgiri** [comment]
thanks for your reply. I am totally new and doing this tutorial. Could u please elaborate what should I do to make it fix ?

**Comment by Foxandxss** [comment]
Yes, better use the angular/cli (https://github.com/angular/angular-cli) and start there. Won't give you any fishy error.

**Comment by nishantgiri** [comment]
I was using this tutorial "https://angular.io/tutorial/toh-pt1"

Is there any better one available for newbie like me ?

**Comment by Foxandxss** [comment]
No, it is perfect and it is written to be used with the angular cli.

**Comment by nishantgiri** [comment]
I have been following the same but unfortunately stuck on chapter 3. 'the Hero Editor'. So what link you would like to suggest to me ?

**Comment by Foxandxss** [comment]
Try to see why you get stuck and fix it. The tutorial is tested so it works.
