### ISSUE TITLE
Quickstart is in version 4 while current stable version is 5.2.1

### ISSUE THREAD

**Issue by meir-ohayon** [angular/quickstart#526]
Angular 5 is here for quite a long (current stable version is 5.2.1). For those like me that use to develop locally and not to use the CLI, see [here](https://angular.io/guide/setup#appendix-why-develop-locally) why to favor this setup approach, and want also to use the current stable version of angular, my suggestion is to download the plunker angular setup (by visiting <https://plnkr.co/> , clicking the 'Launch the Editor' button, then in the top menu choose New->Angular , after it will finish loading click the download button in the top right corner to download this setup as a zip file, extract it and for converting it to local development setup, like this project, follow [this](https://meir-ohayon.github.io/angular/2018/01/21/adjusting-angular-plunker-setup-for-local-development-setup.html) instructions that I made (it's a bit of work, but until this important project will be updated it may be quite fair solution).

**Comment by Foxandxss** [comment]
This repo was deprecated long ago (you can read it in the readme). The setup page you link is deprecated and due to be removed in a PR.

CLI is the recommended way now.
