### ISSUE TITLE
'start' task fails if there are compile errors

### ISSUE THREAD

**Issue by RickStrahl** [angular/quickstart#59]
The Start npm task fails if there are typescript compilation errors and this probably shouldn't happen.

Given that this is to start a running dev environment, the dev environment should be able to start up even if there are error since you will be compiling and fixing code incrementally.

I realize there probably is no fix for this since this is due to the compiler's exit code but this is something that should be addressed. It's a really confusing 'getting started error' - I was looking in all the wrong places for a solution because it looks like a node/npm version issue based on the error message.

**Comment by wardbell** [comment]
It's super annoying, Rick. I've complains to Typescript team that they really need to let us choose the severity.

I am very open to an alternative suggestion

**Comment by RickStrahl** [comment]
Do you really need the call to `tsc`? Seems to me the `tsc:w` watch task does a compile immediately - I see the same error, but the server starts up.

```json
"start": "concurrently \"npm run tsc:w\" \"npm run lite\" ",
```

**Comment by wardbell** [comment]
In the latest version, we run `tsc` FIRST and then concurrently `tsc:w` and `lite`.

Yes, that runs `twice` each time you start. But it avoids the race condition in which the server starts before the first tsc finishes.

**Comment by RickStrahl** [comment]
Thanks Ward,

No need to reply, but here is the way I think about this:

Yeah I hear 'ya about the race condition, but it still seems better that the server starts up with errors, rather than not starting at all - the compiler will catch up after all. The big issue is that it's not super obvious that it's a script compilation error that's holding up the server from running. 

What I would expect here is that the server *always* starts. if there is an error that error will show up either on the page (with console errors) or on the command line, but at that point I can fix and then see the change immediately. This is especially frustrating if you've had it work before assuming the server would always be there, and then fail another time because an error was introduced 'offline'. Then it's easy to miss the compile error and wonder why no server is loading :-)


Thanks.
