### ISSUE TITLE
Cannot `import {UpgradeAdapter} from 'angular2/upgrade'`

### ISSUE THREAD

**Issue by fenduru** [angular/quickstart#60]
After cloning this repository, the first thing I tried to do was `import {UpgradeAdapter} from 'angular2/upgrade'`, however this results in a 404 error from system.js trying to load `/angular/upgrade`

I can import other modules from angular2 just fine, so I'm not sure what the difference is with the upgrade module.

**Comment by Foxandxss** [comment]
You need to load the corresponding file in a script tag, like the router or HTTP. Also keep in mind this is a quickstart project.
