### ISSUE TITLE
 error TS2304: Cannot find name 'Promise'

### ISSUE THREAD

**Issue by toni-moreno** [angular/quickstart#63]
Hi. I would like to build a golang+angular2 web stack skeleton. In this way I've cloned this repo to use as angular2 skel.  but it seems not to be working . I simply did the following. 

```
#git clone  https://github.com/angular/quickstart  my-proj
#cd my-proj/
 #npm install
 #npm start
```` 
And we got this error.  How can I fix it ?

```
[root@grafanalab01 my-proj]# npm start

> angular2-quickstart@1.0.0 start /root/my-proj
> tsc && concurrently "tsc -w" "lite-server"

node_modules/angular2/platform/browser.d.ts(77,90): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/compiler/xhr.d.ts(6,23): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/compiler/xhr_mock.d.ts(10,23): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(83,60): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(83,146): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(96,51): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(96,147): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(133,90): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(171,81): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/change_detection/differs/default_keyvalue_differ.d.ts(23,15): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/change_detection/differs/default_keyvalue_differ.d.ts(25,16): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/change_detection/parser/locals.d.ts(3,14): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/change_detection/parser/locals.d.ts(4,42): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/debug/debug_node.d.ts(14,13): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/debug/debug_node.d.ts(24,17): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/debug/debug_node.d.ts(25,17): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/di/provider.d.ts(436,103): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/di/provider.d.ts(436,135): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/linker/compiler.d.ts(12,50): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/compiler.d.ts(16,41): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(108,136): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(156,150): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(197,128): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(203,127): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(204,141): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(205,119): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/render/api.d.ts(13,13): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/render/api.d.ts(14,84): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/async.d.ts(27,33): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/async.d.ts(28,45): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
node_modules/angular2/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
node_modules/angular2/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(99,41): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/collection.d.ts(100,22): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/collection.d.ts(101,25): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/lang.d.ts(4,17): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/lang.d.ts(5,17): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/lang.d.ts(71,59): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/promise.d.ts(2,14): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(11,50): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/mock/mock_application_ref.d.ts(12,80): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/platform/browser/browser_adapter.d.ts(75,33): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/platform/dom/dom_adapter.d.ts(85,42): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/testing/matchers.d.ts(4,37): error TS2503: Cannot find namespace 'jasmine'.
node_modules/angular2/src/testing/test_component_builder.d.ts(118,43): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(35,67): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(50,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(89,67): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(94,38): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(94,50): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(46,62): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(47,42): error TS2304: Cannot find name 'Iterator'.
node_modules/rxjs/Observable.d.ts(103,74): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(103,84): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(143,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(158,65): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(201,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(206,38): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(206,50): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/ForkJoinObservable.d.ts(6,50): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/ForkJoinObservable.d.ts(7,58): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/FromObservable.d.ts(7,38): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/FromObservable.d.ts(7,51): error TS2304: Cannot find name 'Iterator'.
node_modules/rxjs/observable/PromiseObservable.d.ts(9,31): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/PromiseObservable.d.ts(10,26): error TS2304: Cannot find name 'Promise'.
app/app.component.spec.ts(26,18): error TS2339: Property 'toEqual' does not exist on type 'NgMatchers'.
app/app.component.spec.ts(36,67): error TS2339: Property 'toBe' does not exist on type 'NgMatchers'.
app/app.component.spec.ts(46,30): error TS2339: Property 'toMatch' does not exist on type 'NgMatchers'.

npm ERR! Linux 2.6.32-573.8.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/root/.npm-global/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular2-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/my-proj/npm-debug.log
````

**Comment by Foxandxss** [comment]
Sounds like typings not installed. Check for a typings folder in your project.

**Comment by toni-moreno** [comment]
this is what my folder project has. ( the same as the repo).

```
[root@grafanalab01 my-proj]# ls -ltr
total 88
-rw-r--r--   1 root root  5641 Apr 16 15:16 README.md
-rw-r--r--   1 root root  1078 Apr 16 15:16 LICENSE
-rw-r--r--   1 root root   525 Apr 16 15:16 Dockerfile
-rw-r--r--   1 root root  1093 Apr 16 15:16 CHANGELOG.md
-rw-r--r--   1 root root  2504 Apr 16 15:16 wallaby.js
-rw-r--r--   1 root root   275 Apr 16 15:16 typings.json
-rw-r--r--   1 root root  1896 Apr 16 15:16 tslint.json
-rw-r--r--   1 root root   342 Apr 16 15:16 tsconfig.json
-rw-r--r--   1 root root  2305 Apr 16 15:16 styles.css
-rw-r--r--   1 root root  4978 Apr 16 15:16 protractor.config.js
-rw-r--r--   1 root root  1505 Apr 16 15:16 package.json
-rw-r--r--   1 root root  2709 Apr 16 15:16 karma-test-shim.js
-rw-r--r--   1 root root  3065 Apr 16 15:16 karma.conf.js
-rw-r--r--   1 root root  1200 Apr 16 15:16 index.html
-rw-r--r--   1 root root   281 Apr 16 15:16 e2e-spec.js
drwxr-xr-x 431 root root 16384 Apr 16 15:17 node_modules
drwxr-xr-x   2 root root  4096 Apr 16 15:17 app
```

the node_modules has the typings folder

```
[root@grafanalab01 my-proj]# ls -l node_modules/angular2/typings
total 12
-rw-r--r-- 1 root root  337 Apr 13 22:52 browser.d.ts
drwxr-xr-x 2 root root 4096 Apr 13 22:52 es6-collections
drwxr-xr-x 2 root root 4096 Apr 13 22:52 es6-promise
````

what to do now?

**Comment by Foxandxss** [comment]
For some reason the typings folder is not created.

Try

$ ./node_modules/.bin/typings install

And see if that creates it and works.

**Comment by toni-moreno** [comment]
OK ! , now it is working, Thanks a lot!!

![image](https://cloud.githubusercontent.com/assets/5883405/14582590/fa776db2-0409-11e6-81da-1e8807494e14.png)

Do you know why npm install didn't  install typings ?

**Comment by Foxandxss** [comment]
It should. I will check why it didn't.

**Comment by ashblue** [comment]
Just had this happen to me today. Guessing this isn't resolved.

**Comment by ashblue** [comment]
On a mac `$ ./node_modules/.bin/typings install` isn't running or solving my issue.

**Comment by masterrex** [comment]
Also had this issue, ./node_modules/.bin/typings install did the trick.

**Comment by ashblue** [comment]
Weird, typings install fix now works. Looks like I had to restart my computer for some odd reason.

**Comment by Devansh3790** [comment]
`$ ./node_modules/.bin/typings install' solved my problem but it had create a  "typings"  folder in my root folder.

**Comment by naczu** [comment]
@Foxandxss  I had the same problem and `$ ./node_modules/.bin/typings install' solved my problem. I thought that package.json already installed the typings. this is my package.json it is same as in 5 min Quickstart

`
{
 "name": "angular2-quickstart",
"version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common":  "2.0.0-rc.1",
    "@angular/compiler":  "2.0.0-rc.1",
    "@angular/core":  "2.0.0-rc.1",
    "@angular/http":  "2.0.0-rc.1",
    "@angular/platform-browser":  "2.0.0-rc.1",
    "@angular/platform-browser-dynamic":  "2.0.0-rc.1",
    "@angular/router":  "2.0.0-rc.1",
    "@angular/router-deprecated":  "2.0.0-rc.1",
    "@angular/upgrade":  "2.0.0-rc.1",
    "systemjs": "0.19.27",
    "core-js": "^2.4.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12",
    "angular2-in-memory-web-api": "0.0.10",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10",
    "typings":"^1.0.4"
  }
}
`

**Comment by Foxandxss** [comment]
node and npm versions are the problem here.

**Comment by rsORAU** [comment]
Could you please explain what you meant by the problem being with the node and npm versions?

**Comment by AliMD** [comment]
same issue !
i have error when try to manually install typings
```
typings ERR! message Unable to read typings for "node". You should check the entry paths in "node.d.ts" are up to date
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/6d0e826824da52204c1c93f92cecbc961ac84fa9/node/node.d.ts"
typings ERR! caused by connect ECONNREFUSED 10.10.34.36:443

typings ERR! cwd /Volumes/Repositories/school/angular2-quickstart
typings ERR! system Darwin 15.4.0
typings ERR! command "/DevTools/nodejs/bin/iojs" "/DevTools/npm/bin/typings" "i"
typings ERR! node -v v6.2.0
typings ERR! typings -v 1.0.4
```

I think its about firewall issue not angular

**Comment by VahidN** [comment]
@AliMD
10.10.34.36:443 is a private range IP, which means it's filtered/censored in your area (the whole raw.githubusercontent.com).

**Comment by benkeen** [comment]
Ran into the same issue today. Manually installing worked for me. (Mac OSX)

**Comment by puvaasam** [comment]
Make sure you are included typings.json file in root folder before doing npm install, because our npm install has dependency  (see "postinstall": "typings install", in package.json)

typings.json
...................
{
  "globalDependencies": {
    "core-js": "registry:dt/core-js#0.0.0+20160317120654",
    "jasmine": "registry:dt/jasmine#2.2.0+20160505161446",
    "node": "registry:dt/node#4.0.0+20160509154515"
  }
}

Then, do npm install from root folder

**Comment by BruceHem** [comment]
Omg why don't they put fixes with typings on the doc, people asking same question all over again

**Comment by whatbirdisthat** [comment]
for me it was my `tsconfig.json`: compilerOptions.target:"es5" ... it needed to be "es6"

**Comment by Foxandxss** [comment]
No, that is the bad solution. You need to add the typings.

**Comment by j5concur** [comment]
I had to add the following to the start of my main.ts in order for it to work properly:

```
///<reference path="../node_modules/typescript/lib/lib.es6.d.ts"/> 
```

**Comment by evvels2131** [comment]
`./node_modules/.bin/typings install` did the trick for me but it's still happening as of today

**Comment by bedrin** [comment]
[Solution](https://github.com/angular/quickstart/issues/63#issuecomment-235661066) by @j5concur worked for me

**Comment by bedrin** [comment]
Another way to fix it is to change `target` to `es6` in your `tsconfig.json`:
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false
    }
}
```

**Comment by thanhtruong0315** [comment]
@bedrin +1. Thanks. It works.

**Comment by rdvojmoc** [comment]
@thanhtruong0315 in my case there was a problem with IE11 if i changed target to es6.

**Comment by pavlyukpetr** [comment]
@bedrin yeah, thank. It works for me too

**Comment by LincolnLuiz** [comment]
@bedrin why dont function with es5?

**Comment by Kalanamith** [comment]
@bedrin  It worked and thank you for your answer , cheers

**Comment by layton-glympse** [comment]
@bedrin why would we just change the target to es6? Am I the only person who thinks that is nuts?
ES6 is not fully supported by any means in the browser. Compiling to ES6 will break your project. The reason setting your target to ES6 works is because ES6 natively supports promises.
The real solution here is to fix the library, not change our output to ES6.

**Comment by Kalanamith** [comment]
it worked on ES5 as well though had to set it to ES6  because it didnt run in the  first place . This should be a straight forward install and run

**Comment by bes1002t** [comment]
Using npm install --save-dev @types/core-js did it for me with ES5

**Comment by bedrin** [comment]
@layton-glympse I totally agree with you - I just needed a way to give it a quick start and this worked for me

**Comment by bofcarbon1** [comment]
compiling with 'tsc app.ts --target es6' will get rid of the 'promise' errors but create errors with imports

bofcarbon1:~/workspace/app/ch4/ts/ng-for/detailed-syntax (master) $ tsc app.ts --target es6 
app.ts(1,25): error TS2307: Cannot find module '@angular/core'.
app.ts(2,25): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.

**Comment by bofcarbon1** [comment]
Man I'm so sick of library dependency issues with node.js.  I can never focus on application code with this crap.

**Comment by app-sparkler** [comment]
I am on **Windows**.   `npm install -D typings` worked in my project.  Thanks!

**Comment by bofcarbon1** [comment]
Tried....
$ npm install -D typings

bofcarbon1:~/workspace/app/ch4/ts/ng-for/detailed-syntax (master) $ tsc app.ts 
../../../../../node_modules/@angular/core/src/application_ref.d.ts(79,88): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/application_ref.d.ts(137,42): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/application_ref.d.ts(196,33): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(26,16): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/di/reflective_provider.d.ts(115,123): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/di/reflective_provider.d.ts(115,165): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/facade/async.d.ts(34,33): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/facade/async.d.ts(35,45): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
../../../../../node_modules/@angular/core/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
../../../../../node_modules/@angular/core/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/facade/collection.d.ts(100,41): error TS2304: Cannot find name 'Set'.
../../../../../node_modules/@angular/core/src/facade/collection.d.ts(101,22): error TS2304: Cannot find name 'Set'.
../../../../../node_modules/@angular/core/src/facade/collection.d.ts(102,25): error TS2304: Cannot find name 'Set'.
../../../../../node_modules/@angular/core/src/facade/lang.d.ts(11,17): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Set'.
../../../../../node_modules/@angular/core/src/facade/lang.d.ts(68,59): error TS2304: Cannot find name 'Map'.
../../../../../node_modules/@angular/core/src/facade/promise.d.ts(9,14): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/facade/promise.d.ts(15,32): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/facade/promise.d.ts(16,38): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/facade/promise.d.ts(17,35): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/facade/promise.d.ts(17,93): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/facade/promise.d.ts(18,34): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/facade/promise.d.ts(18,50): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/facade/promise.d.ts(19,32): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/facade/promise.d.ts(19,149): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/facade/promise.d.ts(20,43): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/linker/compiler.d.ts(13,59): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/linker/component_resolver.d.ts(9,58): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/linker/component_resolver.d.ts(13,49): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(61,148): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(102,144): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(107,139): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(108,135): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(18,53): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(26,53): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/platform-browser-dynamic/index.d.ts(81,90): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/platform-browser-dynamic/index.d.ts(85,99): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/@angular/platform-browser-dynamic/index.d.ts(89,99): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
../../../../../node_modules/rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.
app.ts(8,7): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
bofcarbon1:~/workspace/app/ch4/ts/ng-for/detailed-syntax (master) $ 

...........

But you know it 'transpiles' or whatever anyway.   Not worth losing sleep over. It is what it is.

**Comment by filipesilva** [comment]
This project does not use the `typings` package anymore, so if you are experiencing a typings related problem the answer is not to do `npm install typings`. As @layton-glympse said, it is also not to target ES6 (for the reasons listed).

If you're experiencing `Cannot find name 'Promise'.`, it's most likely because you changed something from the base setup or did not finish installing the node packages. Do this:
- freshly clone this repository
- run `npm install` and make sure it finishes successfully
- copy the `app` folder of your existing project into this new project

**Comment by vignesh-subash** [comment]
Its working perfectly fine for me. thank you @filipesilva :) :)

**Comment by marcsyp** [comment]
For anyone arriving here looking for solutions to a similar problem, I was having the same problem with Ionic RC2-RC4, tried all kinds of things to fix it, including using npm to install typings, avoiding adding es6 as a target, etc... the thing that finally fixed it: updating the VS Code editor.  I had been postponing the updates for weeks, and for some reason, updating fixed it.  So go ahead and make sure your IDE is updated before you chase down all kinds of other solutions...

Marc

**Comment by piq9117** [comment]
I did `npm install --save @types/core-js` and it resolved my problem

**Comment by pedrocoder** [comment]
npm install --save @types/core-js   ------- resolve the problem

**Comment by VovanSuper** [comment]
The same ugly stuff I have in sample where I use webpack-stream (webpack from gulp tasks), ts2.1.0, @angular app with couple of loaders and plugins; 
So, thechnically, those not are the error, rather the warning by TS-compiler, but they not allowing finallization of webpack work, which really sucks. Way around could be to use: ```"skipLibCheck": true```  in tscofig, to say: "I know that all the settings/imports in my proj are cool; just dont' hassle.."

**Comment by costerik** [comment]
I haved the same issue and was solved it with this configuration.

package.json
{
"name": "angular_2_app",
"version": "1.0.0",
"description": "angular app for presentation",
"scripts": {
"build": "tsc --rootDir src/ --outDir build/"
},
"author": "Erik Ahumada",
"license": "ISC",
"dependencies": {
"@angular/common": "~4.0.0",
"@angular/compiler": "~4.0.0",
"@angular/core": "~4.0.0",
"@angular/forms": "~4.0.0",
"@angular/http": "~4.0.0",
"@angular/platform-browser": "~4.0.0",
"@angular/platform-browser-dynamic": "~4.0.0",
"@angular/router": "~4.0.0",
"@types/node": "^7.0.11",
"core-js": "^2.4.1",
"reflect-metadata": "^0.1.10",
"rxjs": "5.0.1",
"zone.js": "^0.8.4"
},
"devDependencies": {
"@types/core-js": "^0.9.39",
"typescript": "^2.2.1",
"typings": "^2.1.0",
"webpack": "^2.3.2"
}
}

tsconfig.json
{
"compilerOptions": {
"module": "commonjs",
"target": "es5",
"moduleResolution": "node",
"experimentalDecorators": true,
"emitDecoratorMetadata": true,
"lib": ["es2015", "dom"]
}
}

**Comment by yavin5** [comment]
One more thing to try: Add this to the top of your ts file that needs Promises, Maps, etc:

///<reference types="typescript/lib/lib.es6"/>

If you use this instead of ///<reference path="../../node_modules/whatever"/> then when you publish your code as a module, the reference still works!  This was very difficult and time consuming to figure out, and it appears to be magic.

**Comment by yangnianbing** [comment]
@costerik this help me too, i found when i add lib : ['es2015','dom'], all ok

**Comment by oddorphan** [comment]
@costerik Thanks! Helped me as well.  I noticed your 'typescript' and 'typings' dependencies were at a higher version.  That did it. :)

**Comment by Sayaren** [comment]
use <"lib": ["es2015", "dom"] > instead of <"lib": ["es5", "dom"]> works well.

**Comment by paigeflourin** [comment]
upgraded my dependencies to these fixed it for me 

"dependencies": {
"@angular/common": "~4.0.0",
"@angular/compiler": "~4.0.0",
"@angular/core": "~4.0.0",
"@angular/forms": "~4.0.0",
"@angular/http": "~4.0.0",
"@angular/platform-browser": "~4.0.0",
"@angular/platform-browser-dynamic": "~4.0.0",
"@angular/router": "~4.0.0",

**Comment by Alavi1412** [comment]
I have an error like this:
```

../../node_modules/@types/angularjs/angular-mocks.d.ts(6,26): error TS2307: Cannot find module 'angular'.
../../node_modules/@types/angularjs/angular-mocks.d.ts(65,49): error TS2304: Cannot find name 'IServiceProvider'.
../../node_modules/@types/angularjs/angular-mocks.d.ts(122,62): error TS2304: Cannot find name 'IScope'.
../../node_modules/@types/angularjs/index.d.ts(8,1): error TS2688: Cannot find type definition file for 'jquery'.
../../node_modules/@types/angularjs/index.d.ts(66,43): error TS2304: Cannot find name 'JQuery'.
../../node_modules/@types/angularjs/index.d.ts(987,43): error TS2304: Cannot find name 'JQuery'.
../../node_modules/@types/angularjs/index.d.ts(1206,19): error TS2304: Cannot find name 'JQuery'.
../../node_modules/@types/angularjs/index.d.ts(1231,26): error TS2304: Cannot find name 'JQuery'.
../../node_modules/@types/angularjs/index.d.ts(1828,46): error TS2304: Cannot find name 'JQueryStatic'.
../../node_modules/@types/angularjs/index.d.ts(1833,18): error TS2304: Cannot find name 'JQuery'.
../../node_modules/@types/angularjs/index.d.ts(1839,40): error TS2304: Cannot find name 'JQuery'.
../../node_modules/@types/angularjs/index.d.ts(1845,19): error TS2304: Cannot find name 'JQuery'.
../../node_modules/@types/angularjs/index.d.ts(1857,49): error TS2304: Cannot find name 'JQuery'.
../../node_modules/@types/angularjs/index.d.ts(1858,54): error TS2304: Cannot find name 'JQuery'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alavi/.npm/_logs/2017-09-20T08_21_14_248Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alavi/.npm/_logs/2017-09-20T08_21_14_305Z-debug.log

```

I just download the quickstart and use `npm install` and then `npm start`
What is the solution for me?
