### ISSUE TITLE
tsc compilation takes forever

### ISSUE THREAD

**Issue by kirjai** [angular/quickstart#73]
Firstly, really appreciate the repo, super helpful.

Unfortunately, recently, all of the sudden the `tsc:w` and `tsc` started taking extremely large amounts of time. Having ran `time command tsc` the output is just under 30 seconds!

Checked the typescript repo for any issues, only found suggestions to upgrade, however i am on the latest 1.8.10 version anyway. Node v4.4.2 should be handling that well as well. `node_modules` is definitely excluded. So really lost as to what might be causing this. Would appreciate any help or someone pointing me in the right direction.

Note: using the default tsconfig from this repo

**Comment by Foxandxss** [comment]
Weird, it shouldn't take that long. It takes 2 second for me.

I am using latest everything, including node and npm.

**Comment by kirjai** [comment]
It was fine with me at first as well, all snappy and great, but then all of the sudden it started taking ages.. I can't put my finger on what's changed. To be honest, it is most likely a Typescript issue, however maybe someone has stumbled upon the similar behaviour using this repository.

**Comment by kirjai** [comment]
Going to close this, as it doesn't really apply to repo, apologies on this.

To those stumbling upon this issue - I never actually managed to fix the problem. I have started from scratch, a brand new project, and I would paste in chunks of existing code to see if the problem re-appears, but it never did. Sorry this isn't that helpful.
