### ISSUE TITLE
node_modules/@angular/router-deprecated/ 404 (Not Found)

### ISSUE THREAD

**Issue by yuriychemodakovakv** [angular/quickstart#81]
I'm just following tour of heroes.
npm installed everything fresh 30 mins ago (with no errors) and here is what I have:

On https://angular.io/docs/ts/latest/tutorial/toh-pt5.html
Once I add 

`@RouteConfig([
  {
    path: '/heroes',
    name: 'Heroes',
    component: HeroesComponent
  }
])`

I get the following in my console:

`zone.js:101 GET http://localhost:3000/node_modules/@angular/router-deprecated/ 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM1894:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
(index):20 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/@angular/router-deprecated(…)`

If I copy all app/app.component.ts (v2) from tutorial page, I get completely the same.
Win 10, Chrome 49.
Please help. Thank you!

**Comment by Foxandxss** [comment]
We just released RC0. Let me put myself up to date and see what is going on.

**Comment by wardbell** [comment]
Should be fine now. Up to RC1 too

**Comment by yuriychemodakovakv** [comment]
Thank you!

**Comment by dboydor** [comment]
I'm getting the same thing with the tutorial.  What do I need to fix this?  I tried npm update, no luck

**Comment by Foxandxss** [comment]
show your package.json

**Comment by dboydor** [comment]
It used to be 2.0.0-rc.0, but I switched all to 2.0.0-rc.1.  I ran npm update, restarted the server, but still getting the 404.

{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common":  "2.0.0-rc.1",
    "@angular/compiler":  "2.0.0-rc.1",
    "@angular/core":  "2.0.0-rc.1",
    "@angular/http":  "2.0.0-rc.1",
    "@angular/platform-browser":  "2.0.0-rc.1",
    "@angular/platform-browser-dynamic":  "2.0.0-rc.1",
    "@angular/router-deprecated":  "2.0.0-rc.1",
    "@angular/upgrade":  "2.0.0-rc.1",

    "systemjs": "0.19.27",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12",

    "angular2-in-memory-web-api": "0.0.5",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10",
    "typings":"^0.8.1"
  }
}

**Comment by dboydor** [comment]
Funny, I see the subfolder node_modules/@angular/router-deprecated with files within it, in the filesystem.

However this url still returns a 404:
http://localhost:3000/node_modules/@angular/router-deprecated/

**Comment by Foxandxss** [comment]
show me your systemjs.config.js

**Comment by dboydor** [comment]
`(function(global) {

  // map tells the System loader where to look for things
  var map = {
    'app':                        'app', // 'dist',
    'rxjs':                       'node_modules/rxjs',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    '@angular':                   'node_modules/@angular'
  };

  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { defaultExtension: 'js' },
  };

  var packageNames = [
    '@angular/common',
    '@angular/compiler',
    '@angular/core',
    '@angular/http',
    '@angular/platform-browser',
    '@angular/platform-browser-dynamic',
    '@angular/router',
    '@angular/testing',
    '@angular/upgrade',
  ];

  // add package entries for angular packages in the form '@angular/common': { main: 'index.js', defaultExtension: 'js' }
  packageNames.forEach(function(pkgName) {
    packages[pkgName] = { main: 'index.js', defaultExtension: 'js' };
  });

  var config = {
    map: map,
    packages: packages
  }

  // filterSystemConfig - index.html's chance to modify config before we register it.
  if (global.filterSystemConfig) { global.filterSystemConfig(config); }

  System.config(config);

})(this);

`

**Comment by Foxandxss** [comment]
add @angular/router-deprecated along with the others there.

That will tell system.js where to find @angular/router-deprecated when you ask for it and not give a 404

**Comment by dboydor** [comment]
Cool.  You might want to update the tutorial because this file came straight from it.  Thanks again.

**Comment by Foxandxss** [comment]
which tutorial?

**Comment by dboydor** [comment]
https://angular.io/docs/ts/latest/tutorial/toh-pt5.html

**Comment by Foxandxss** [comment]
that part contains no package.json nor systemjs.config.js.

**Comment by dboydor** [comment]
Sorry, it's a continuation of the QuickStart tutorial which does configure those files.

https://angular.io/docs/js/latest/quickstart.html

And now, of course, it is all correct.  I know I'm looking crazy, but it wasn't like that a couple of days ago!

**Comment by Foxandxss** [comment]
It wasn't, we are changing too much stuff so that can happen. That is why I ask you, perhaps we left something out :)
