### ISSUE TITLE
'angular' is not in the npm registry

### ISSUE THREAD

**Issue by narensgh** [angular/quickstart#82]
while installing through **`npm install`**
I got below error

> npm http 404 https://registry.npmjs.org/angular/router-deprecated/2.0.0-rc.0
> npm ERR! 404 'angular' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it 

Please look into it. I'm stuck for getting started.

**Comment by Foxandxss** [comment]
We just released rc0 so we still need to do some adjustements. Give me a couple of hours until I figure things out.

**Comment by Foxandxss** [comment]
I got no error for that. Weird.

**Comment by aurrelhebert** [comment]
I have the same issue. Try with an import from 'angular2/core', this will fail. Same as npm install angular2

**Comment by narensgh** [comment]
I looked into npm-debug.log and got this.
 > http 404 https://registry.npmjs.org/angular/http/2.0.0-rc.0
 > silly registry.get cb [ 404,
 > silly registry.get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
 > silly registry.get     'content-type': 'application/json',
 > silly registry.get     'cache-control': 'max-age=0',
 > silly registry.get     'content-length': '40',
 > silly registry.get     'accept-ranges': 'bytes',
 > silly registry.get     date: 'Tue, 03 May 2016 09:45:51 GMT',
 > silly registry.get     via: '1.1 varnish',
 > silly registry.get     age: '0',
 > silly registry.get     connection: 'keep-alive',
 > silly registry.get     'x-served-by': 'cache-sin6927-SIN',
 > silly registry.get     'x-cache': 'MISS',
 > silly registry.get     'x-cache-hits': '0',
 > silly registry.get     'x-timer': 'S1462268751.066597,VS0,VE223' } ]
 > silly lockFile fed358bb-angular-http-2-0-0-rc-0 angular/http@2.0.0-rc.0
 > silly lockFile fed358bb-angular-http-2-0-0-rc-0 angular/http@2.0.0-rc.0
 > error 404 'angular' is not in the npm registry.
 > error 404 You should bug the author to publish it
 > error 404
 > error 404 Note that you can also install from a
 > error 404 tarball, folder, or http url, or git url.
 > error System Linux 3.13.0-68-generic
 > error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
 > error cwd /var/www/html/angular/basic
 > error node -v v0.10.25
 > error npm -v 1.3.10
 > error code E404
 > verbose exit [ 1, true ]

And then hit [https://registry.npmjs.org/angular/http/2.0.0-rc.0](https://registry.npmjs.org/angular/http/2.0.0-rc.0) into browser and gor response
> {"error":"not_found","reason":"missing"}

**Comment by narensgh** [comment]
hey, It's working now..!!
It was due to npm version issue.
