### ISSUE TITLE
Missing systemjs.config.js

### ISSUE THREAD

**Issue by ZenSoftware** [angular/quickstart#83]
Running **npm start** after a fresh **git clone** does not launch a working site.  The quickstart changes for Angular 2.0.0-rc.0 seems to be missing a systemjs.config.js that the index.html references.

**Comment by Foxandxss** [comment]
That has been fixed.

**Comment by ZenSoftware** [comment]
Thanks, much appreciated ^_^

**Comment by wardbell** [comment]
It's in now

**Comment by anastasia** [comment]
Seems like the quickstart guide might need to be updated as well (it references two different file names).

<img width="987" alt="screen shot 2016-05-06 at 2 50 20 pm" src="https://cloud.githubusercontent.com/assets/1494102/15083206/f43f3818-1399-11e6-91a9-0de0216dca5a.png">

<img width="1018" alt="screen shot 2016-05-06 at 2 48 57 pm" src="https://cloud.githubusercontent.com/assets/1494102/15083209/f819b10c-1399-11e6-8b6e-b0b1aa97b664.png">

<img width="646" alt="screen shot 2016-05-06 at 2 51 54 pm" src="https://cloud.githubusercontent.com/assets/1494102/15083246/23261318-139a-11e6-896f-127337274f88.png">

**Comment by Foxandxss** [comment]
There is a PR already to fix that. That is just a typo

**Comment by anastasia** [comment]
Yup! Sorry, I just meant to give a heads up about the typo. It threw me off for a second there.

**Comment by Foxandxss** [comment]
No worries, that is never a bad idea :)
