### ISSUE TITLE
module: commonjs

### ISSUE THREAD

**Issue by a2dude** [angular/quickstart#88]
Just curious why has the tsconfig setting 'module' been set to 'commonjs'?

This prevents the bundling of ts output into a single js file.

**Comment by wardbell** [comment]
We have other bundling approaches in mind. System.js does understand commonjs format and we are standardizing on that so that we can define module-relative template and style urls in our components like this:
```
@Component({
  moduleId: module.id, // commonjs reference to this module file
  selector: 'some-component',
  templateUrl: 'some-component.component.html',
  styleUrls: ['some-component.component.css']
})
export class SomeComponent {...}
```
