### ISSUE TITLE
Shadow DOM gone

### ISSUE THREAD

**Issue by dylanb** [angular/quickstart#9]
It seems as though the updates that happened about 8 hours ago changed the implementation significantly - there is no longer a shadow DOM associated with the elements on Chrome. Is this intentional or have I missed something that I need to do to enable it?

**Comment by vicb** [comment]
That's probably because the shadow dom strategy had been switched to emulated by default.

You can override the default: bootstrap(Comp, [bind (ShadowDomStrategy).toClass (NativeShadowDomStrategy]);

Sorry for the formatting, I'm on a tablet

**Comment by dylanb** [comment]
In case others want to know how to do this:

```
import {bind} from 'angular2/di';
import {ShadowDomStrategy, NativeShadowDomStrategy} from 'angular2/src/core/compiler/shadow_dom_strategy';

bootstrap(MyApp, [bind(ShadowDomStrategy).toClass(NativeShadowDomStrategy)]);
```
