### ISSUE TITLE
Cannot find 'angular/compiler'

### ISSUE THREAD

**Issue by liquidkey** [angular/quickstart#90]
Hi,

I'm on windows 7 and when I run npm install I get the follow error.

'angular/compiler' is not in the npm registry.

How do I install angular 2.0 using npm ?

![image](https://cloud.githubusercontent.com/assets/2971973/15050723/4cb33de4-12ed-11e6-9074-db5d16b95d36.png)

**Comment by kazemihabib** [comment]
hi,your node version is so old. upgrade your node and npm.

**Comment by wardbell** [comment]
Using the RC1 now. Should be installing `@angular/...`. Are you really using this quick start?
