### ISSUE TITLE
 Error: XHR error (404 Not Found) loading http://localhost:3000/app/main.js(…)

### ISSUE THREAD

**Issue by beebase** [angular/quickstart#92]
Getting this error after literally pasting all code from the quickstart tutorial on the site

https://angular.io/docs/ts/latest/quickstart.html

```
Navigated to http://localhost:3000/
zone.js:101 GET http://localhost:3000/app/main.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM293:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474
(index):19 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/app/main.js(…)
```

**Comment by beebase** [comment]
Never mind, my bad. Typo in main.ts
import { AppComponent } from './app.component**.ts**     (.ts should not be there)

Not so literally pasted after all :-/

**Comment by ishwar25667** [comment]
I am getting same error but i import AppComponent as it is from angular.io quick start tutorial. Could you give me solution for the same. it would be highly appreciable.

**Comment by filipesilva** [comment]
@ishwar25667 can you open a new issue with your terror as it appears in the Chrome console?

**Comment by jusmat** [comment]
@ishwar25667 @filipesilva it is systemjs.config.js causing this issue. `app: {
        main: './app.js',
        defaultExtension: 'js'
      },` points to `./app.js`, while it should point to `app.main.js`

**Comment by anuradharathnayake** [comment]
lk
