### ISSUE TITLE
Bundling RC files

### ISSUE THREAD

**Issue by VahidN** [angular/quickstart#96]
I think it's necessary to mention "How to bundle RC files using systemjs.json.js file". Because without this step, using systemjs.json.js file, will produce hundreds of round trips to the server, which is unacceptable. These gulp tasks, using `gulp-typescript` and `systemjs-builder`, will automate this job:

```javascript
var
    gulp = require("gulp"),
     tsc = require("gulp-typescript"),
     SystemBuilder = require("systemjs-builder");

var appFolder = "./app";
var outFolder = "wwwroot";

gulp.task("tsc", () => {
    var tsProject = tsc.createProject("./tsconfig.json");
    var tsResult = gulp.src([
         appFolder + "/**/*.ts"
    ])
    .pipe(tsc(tsProject), undefined, tsc.reporter.fullReporter());

    return tsResult.js.pipe(gulp.dest("build/"));
});

gulp.task("system-build", ["tsc"], () => {
    var builder = new SystemBuilder();

    return builder.loadConfig("systemjs.config.js")
        .then(() => builder.buildStatic(appFolder, outFolder + "/js/bundle.js"))
        .then(() => del("build"));
});
```

**Comment by Foxandxss** [comment]
This is just a quickstart project, if you want something that can be bundled and put into production, we suggest the angular-cli.

**Comment by tragiclifestories** [comment]
@Foxandxss Unfortunately, those are exactly the outstanding items on the [ng-cli alpha milestone](https://github.com/angular/angular-cli/milestones/alpha.0) - on top of which, the docs point newbies here for the time being. Is there no way people would consider a simple script to create one big bundle, pending the better solution in the CLI?

**Comment by Foxandxss** [comment]
You can consider a simple script to do that. This project is a quickstart, the needed bits to get you started. You can use it and extend it your needs if you want to.

But from this concrete repository, we are not going to extend it in that way.

**Comment by VahidN** [comment]
I've attached my `gulpfile.js` file for those who are looking for a simple solution to start. Its `devDependencies` are mentioned in the `package.json` file.
[BundlingRCfiles.zip](https://github.com/angular/quickstart/files/254559/BundlingRCfiles.zip)

**Comment by adamwuyu** [comment]
@VahidN I used your files, deleted the old node-modules folder,  "npm install" is fine. But "gulp" get many errors, do you have any idea? 

/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/application_ref.d.ts(39,88): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/application_ref.d.ts(99,42): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/application_ref.d.ts(174,33): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(26,16): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/di/reflective_provider.d.ts(105,123): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/di/reflective_provider.d.ts(105,165): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/async.d.ts(27,33): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/async.d.ts(28,45): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/collection.d.ts(100,41): error TS2304: Cannot find name 'Set'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/collection.d.ts(101,22): error TS2304: Cannot find name 'Set'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/collection.d.ts(102,25): error TS2304: Cannot find name 'Set'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/lang.d.ts(4,17): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/lang.d.ts(5,17): error TS2304: Cannot find name 'Set'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/lang.d.ts(70,59): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/promise.d.ts(2,14): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/promise.d.ts(11,50): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/linker/component_resolver.d.ts(8,53): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/linker/component_resolver.d.ts(12,44): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(62,148): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(103,144): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(108,139): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(109,135): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/reflection/reflector.d.ts(28,22): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/reflection/reflector.d.ts(30,15): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/reflection/reflector.d.ts(32,15): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/reflection/reflector.d.ts(34,15): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/reflection/reflector.d.ts(36,16): error TS2304: Cannot find name 'Set'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/core/src/testability/testability.d.ts(40,20): error TS2304: Cannot find name 'Map'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/@angular/platform-browser-dynamic/platform_browser_dynamic.d.ts(75,90): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
/Users/adam/Sites/test/angular2/quickstart/node_modules/rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.

**Comment by wardbell** [comment]
I'm very sympathetic. I hate all those files too. I don't mind that you've proposed a solution. But I can't accept it as part of the quickstart because we have other plans for coping with this, even during development.  I'm so sorry.  Please keep contributing.

**Comment by VahidN** [comment]
@adamwuyu `Cannot find name 'Promise'` means you should add this line at the top of the main.ts file:
```javascript
/// <reference path="../typings/browser/ambient/es6-shim/index.d.ts" />
```

**Comment by adamwuyu** [comment]
@VahidN Great, adding that line can solve all the error message. I guess the  index.html shold be like:
![snip20160510_3](https://cloud.githubusercontent.com/assets/2903328/15138747/7c44f004-16c4-11e6-9048-808f9dab293a.gif)


And the system.config.js should be like:
![snip20160510_4](https://cloud.githubusercontent.com/assets/2903328/15138793/c67da102-16c4-11e6-9779-135bf6a6c845.gif)


The app successfuly statup, just with one error message about zone, do you konw why?  May be it is not related to your solution...
![snip20160510_1](https://cloud.githubusercontent.com/assets/2903328/15138616/9ec50c0a-16c3-11e6-8249-f32a627eeaa2.gif)

**Comment by VahidN** [comment]
after bundling, your index.html file, should look like this:
```html
<!DOCTYPE html>
<html>
<head>
    <base href="/">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Application</title>

    <link href="wwwroot/css/bootstrap.css" rel="stylesheet" />

    <script src="wwwroot/js/shims.js"></script>
</head>

<body>
    <div>
        <my-app>Loading App...</my-app>
    </div>

    <script src="wwwroot/js/jquery/dist/jquery.min.js"></script>
    <script src="wwwroot/js/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="wwwroot/js/bundle.js"></script>
</body>
</html>
```

**Comment by adamwuyu** [comment]
@VahidN  Many Thanks, you saved my day!

**Comment by filipesilva** [comment]
@vahidn I think the documentation isn't updated, but bundling is available in the CLI for prod builds via `ng build -prod`.

**Comment by adamwuyu** [comment]
@filipesilva "ng build -prod" generated some files in dis folder. I used dist folder as website root. The website can start up, just with 279 404 errors. It seems the website is still trying to load those js files. Do you know where I can config this?

**Comment by adamwuyu** [comment]
@filipesilva It really works, thanks!

**Comment by VahidN** [comment]
@filipesilva `ng build -prod` doesn't embedded all of the application's .js files in the final `main.js` file. 
But the above gulp tasks, create a single `js/bundle.js` file which contains all of the angular2 related files + application's files (all of them).

**Comment by adamwuyu** [comment]
@VahidN ，first I used you way. It works fine except in Chrome. In Chrome, if I use the bundle.js, there will be errors. It will be great, if you can solve this issue.

**Comment by VahidN** [comment]
A better solution: [Introduction to Webpack](https://angular.io/docs/ts/latest/guide/webpack.html)
It's also able to embed all of the .html and .css files too, using the **require** method:
```typescript
import { Component } from '@angular/core';
import '../../public/css/styles.css';

@Component({
      selector: 'my-app',
      template: require('./app.component.html'),
      styles: [require('./app.component.css')]
})
export class AppComponent { }
```
