### ISSUE TITLE
Quickstart npm start errors

### ISSUE THREAD

**Issue by CCChristphe** [angular/quickstart#99]
![angularerror](https://cloud.githubusercontent.com/assets/17857017/15155555/d979338e-1697-11e6-97c2-11e0e01851dd.PNG)

So I got the quickstart from angular.io and whenever I stop the project and try running it again (with npm start) I always get these errors. I've deleted it and restarted 5 times and still keep getting these errors. What should I do?

**Comment by Foxandxss** [comment]
That error is not any helpful. What node & npm versions do you have?

**Comment by CCChristphe** [comment]
node 4.4.0 and npm 2.14.20

**Comment by Foxandxss** [comment]
Bump to 5.x and 3.x

**Comment by CCChristphe** [comment]
Why would I need to update if it already worked earlier?

**Comment by Foxandxss** [comment]
Dependencies are always updated and they could stop supporting an old node and npm version.

**Comment by rmoen** [comment]
@Foxandxss you can see the node and npm versions in the screen dump provided.

**Comment by Foxandxss** [comment]
@rmoen true, I didn't see it, my bad.

**Comment by rmoen** [comment]
I also have the same issue but I'm running latest npm and node.
`npm ERR! Linux 3.19.0-58-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular2-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-quickstart package,
npm ERR! not with npm itself.
`

**Comment by Foxandxss** [comment]
Node 6 is giving a lot of issues not only here but in other projects, even 6.1 I personally not recommend them yet.

**Comment by rmoen** [comment]
@Foxandxss I will downgrade.  Which version are you recommending?

**Comment by Foxandxss** [comment]
Latest 5.x for the time being.

**Comment by rmoen** [comment]
@Foxandxss can you be specific ?

**Comment by rmoen** [comment]
@Foxandxss 5.11.1 ?

**Comment by Foxandxss** [comment]
Yes, that is "latest" :)

**Comment by rmoen** [comment]
@Foxandxss confirmed this fixes the issue for me.  Thank you. @CCChristphe you should be able to resolve your issues by upgrading to 5.11.1 and running npm install.

**Comment by CCChristphe** [comment]
So I went to the node.js site and version they have it 4.x.x for windows. How do I update via bash

**Comment by happyshandilya** [comment]
I have similar issue,  I have got the latest version , still it doesn't work 
![quickstart error](https://cloud.githubusercontent.com/assets/14132091/15158030/5132d1ce-16ab-11e6-9946-28118e6765ce.PNG)

**Comment by rmoen** [comment]
@happyshandilya i'm on npm 3.3.6 if that helps.  Otherwise I'm not sure.  @CCChristphe you can upgrade your node to whatever version you want with npm.  Google how to upgrade node with npm.

**Comment by codestellar** [comment]
@happyshandilya it is working for me. But I am interested in analyzing the issue. I had typescript already installed globally. Can you please attach the npm-debug.log here?

**Comment by happyshandilya** [comment]
@codestellar it's working for me , thanks:)

**Comment by shandilya3** [comment]
It's working with node v4.4.3 and npm3.8.8,  well, ideally it should work for all the versions.

**Comment by BrendanErquiaga** [comment]
I have had inconsistent results with this, currently my latest project trying to use the quickstart fails to run. 

I have tried:

node v4.4.4, npm 3.8.6
node v5.11.1, npm v3.9,
node v6.1, npm v3.9

With every version I get the same:

```
npm ERR! angular2-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" 
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular2-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-serv
er" '.
```

**Comment by codestellar** [comment]
@BrendanErquiaga Have you installed TypeScript globally? [TypeScript](https://www.npmjs.com/package/typescript)

**Comment by BrendanErquiaga** [comment]
@codestellar Yes, just checked.

**Comment by codestellar** [comment]
@BrendanErquiaga Are you running the command npm install? Because I don't see any issues in running this app

**Comment by BrendanErquiaga** [comment]
Yea any time I try a new version of node & npm, I run npm install. 

For clarification, the quickstart app runs. But if I add a few components of my own, it sometimes stops working. And once a particular version has stopped running it never starts again. 

Now if I copy those same components into a NEW project, sometimes it will be fine. 

At this point I've changed line 6 of the package json to look like this

```
"start": "concurrently \"tsc -w\" \"lite-server\" ",
```

Removing the 'tsc &&' seems to make it work for me. I have no idea what that's doing but it is my current work around.

**Comment by soskode** [comment]
Thanks BrendanErquiaga , Changing line 6 of the package json to look like 

"start": "concurrently \"tsc -w\" \"lite-server\" ",

worked for me
